using Meridian.Contracts.Workstation;

namespace Meridian.Ui.Shared.Services;

public sealed class ReportWriterDatasetSourceService
{
    private const int DefaultRecordLimit = 200;
    private const string RetainedReportingRowsSourceId = "retained-reporting-rows";
    private const string PortfolioReportingCutsSourceId = "portfolio-reporting-cuts";
    private const string TopNContributionAnalyticsSourceId = "topn-contribution-analytics";
    private const string CrossFundConsolidationSourceId = "cross-fund-consolidation";
    private const string CertifiedOperationalDataMartSourceId = "certified-operational-data-mart";
    private const string DefaultRefreshCadence = "On retained workflow refresh";
    private const string DefaultOwner = "Reporting operations";
    private static readonly IReadOnlyDictionary<string, ReportWriterFieldCatalogEntry> KnownFields =
        new Dictionary<string, ReportWriterFieldCatalogEntry>(StringComparer.OrdinalIgnoreCase)
        {
            ["dataset"] = new("dataset", "Dataset", "dimension", "string", "All", "Source dataset family for the row."),
            ["cutId"] = new("cutId", "Cut ID", "dimension", "string", "Portfolio cuts", "Stable portfolio reporting cut identifier."),
            ["analyticsId"] = new("analyticsId", "Analytics ID", "dimension", "string", "Top-N analytics", "Stable analytics row identifier."),
            ["consolidationId"] = new("consolidationId", "Consolidation ID", "dimension", "string", "Cross-fund consolidation", "Stable consolidation row identifier."),
            ["label"] = new("label", "Label", "dimension", "string", "All", "Display label for the reporting row."),
            ["kind"] = new("kind", "Kind", "dimension", "string", "All", "Reporting row kind such as fund, strategy, user tag, or analytics type."),
            ["scope"] = new("scope", "Scope", "dimension", "string", "All", "Reporting scope used for grouping and drilldown."),
            ["strategy"] = new("strategy", "Strategy", "dimension", "string", "Portfolio cuts", "Strategy tag for strategy-level reporting cuts."),
            ["security"] = new("security", "Security", "dimension", "string", "Top-N analytics", "Security or instrument label where available."),
            ["symbol"] = new("symbol", "Symbol", "dimension", "string", "Top-N analytics", "Ticker or symbol where available."),
            ["classification"] = new("classification", "Classification", "dimension", "string", "Top-N analytics", "Sector, factor, or classification bucket."),
            ["currency"] = new("currency", "Currency", "dimension", "string", "All", "ISO currency for monetary values."),
            ["rank"] = new("rank", "Rank", "dimension", "integer", "Top-N analytics", "Top-N rank for winner and laggard rows."),
            ["grossExposure"] = new("grossExposure", "Gross exposure", "metric", "decimal", "Portfolio cuts", "Gross portfolio exposure."),
            ["netExposure"] = new("netExposure", "Net exposure", "metric", "decimal", "Portfolio cuts", "Net portfolio exposure."),
            ["longMarketValue"] = new("longMarketValue", "Long market value", "metric", "decimal", "Portfolio cuts", "Long-side market value."),
            ["shortMarketValue"] = new("shortMarketValue", "Short market value", "metric", "decimal", "Portfolio cuts", "Short-side market value."),
            ["totalCash"] = new("totalCash", "Total cash", "metric", "decimal", "Portfolio cuts", "Cash available for the cut."),
            ["pendingSettlement"] = new("pendingSettlement", "Pending settlement", "metric", "decimal", "Portfolio cuts", "Pending settlement amount."),
            ["realizedPnl"] = new("realizedPnl", "Realized P&L", "metric", "decimal", "Portfolio reporting", "Realized profit and loss."),
            ["unrealizedPnl"] = new("unrealizedPnl", "Unrealized P&L", "metric", "decimal", "Portfolio reporting", "Unrealized profit and loss."),
            ["totalPnl"] = new("totalPnl", "Total P&L", "metric", "decimal", "Portfolio reporting", "Total profit and loss."),
            ["pnl"] = new("pnl", "P&L", "metric", "decimal", "Portfolio reporting", "Profit and loss source field for contribution grids."),
            ["shadowNav"] = new("shadowNav", "Shadow NAV", "metric", "decimal", "Portfolio cuts", "Parallel shadow NAV value."),
            ["shadowNavVariance"] = new("shadowNavVariance", "Shadow NAV variance", "metric", "decimal", "Portfolio cuts", "Variance between shadow NAV and supporting source values."),
            ["contributionPercent"] = new("contributionPercent", "Contribution %", "generated", "decimal", "Top-N analytics", "Signed contribution percentage generated by analytics or contribution grids."),
            ["heatMapIntensity"] = new("heatMapIntensity", "Heat-map intensity", "metric", "decimal", "Top-N analytics", "Absolute contribution intensity for heat-map style reporting."),
            ["sourceCount"] = new("sourceCount", "Source count", "metric", "integer", "All", "Count of source-backed records supporting the row."),
            ["sourceRunIds"] = new("sourceRunIds", "Source run IDs", "dimension", "string", "Certified data mart", "Pipe-delimited source run or retained version identifiers supporting the row."),
            ["rowLineageKey"] = new("rowLineageKey", "Row lineage key", "dimension", "string", "Certified data mart", "Stable lineage key for tracing this row back to source evidence."),
            ["lineageManifest"] = new("lineageManifest", "Lineage manifest", "dimension", "string", "Certified data mart", "Manifest pointer for retained row-level lineage."),
            ["evidenceIndex"] = new("evidenceIndex", "Evidence index", "dimension", "string", "Certified data mart", "Evidence index pointer for source support and downstream drill-through."),
            ["validationState"] = new("validationState", "Validation state", "dimension", "string", "Certified data mart", "Validation posture for the row."),
            ["reconciliationState"] = new("reconciliationState", "Reconciliation state", "dimension", "string", "Certified data mart", "Reconciliation posture for the row."),
            ["certificationState"] = new("certificationState", "Certification state", "dimension", "string", "Certified data mart", "Certification readiness for the row."),
            ["permittedConsumers"] = new("permittedConsumers", "Permitted consumers", "dimension", "string", "Certified data mart", "Pipe-delimited approved downstream consumers."),
            ["fundCount"] = new("fundCount", "Fund count", "metric", "integer", "Cross-fund consolidation", "Number of funds included in the consolidation row."),
            ["entityCount"] = new("entityCount", "Entity count", "metric", "integer", "Cross-fund consolidation", "Number of entities included in the consolidation row."),
            ["accountCount"] = new("accountCount", "Account count", "metric", "integer", "Cross-fund consolidation", "Number of accounts included in the consolidation row."),
            ["runCount"] = new("runCount", "Run count", "metric", "integer", "Cross-fund consolidation", "Number of retained runs included in the row."),
            ["asOfUtc"] = new("asOfUtc", "As of UTC", "dimension", "datetime", "Top-N analytics", "Source timestamp for analytics rows."),
            ["asOf"] = new("asOf", "As of", "dimension", "datetime", "Portfolio cuts", "Source timestamp for portfolio cuts."),
            ["versionStamp"] = new("versionStamp", "Version stamp", "dimension", "string", "All", "Stable version stamp for audit and export lineage."),
            ["tags"] = new("tags", "Tags", "dimension", "string", "All", "Pipe-delimited user and system tags."),
            ["readinessSummary"] = new("readinessSummary", "Readiness summary", "dimension", "string", "All", "Readiness text for delivery and export review.")
        };

    private readonly ReportPackWorkflowService? _workflowService;

    public ReportWriterDatasetSourceService(ReportPackWorkflowService? workflowService = null)
    {
        _workflowService = workflowService;
    }

    public IReadOnlyList<IReadOnlyDictionary<string, string>> BuildDatasetRows(
        ReportAccessQueryContext? accessContext = null,
        int recordLimit = DefaultRecordLimit)
    {
        var records = ReportPackRunReadService.FilterWorkflowRecords(
            _workflowService?.ListRecords(Math.Clamp(recordLimit, 1, 500)) ?? [],
            accessContext);
        var portfolioCuts = ReportPackRunReadService.BuildPortfolioReportingCuts(records);
        var analyticsRows = ReportPackRunReadService.BuildPortfolioReportingAnalyticsRows(portfolioCuts);
        var crossFundRows = ReportPackRunReadService.BuildCrossFundConsolidations(portfolioCuts);

        return BuildDatasetRows(portfolioCuts, analyticsRows, crossFundRows);
    }

    public IReadOnlyList<IReadOnlyDictionary<string, string>> BuildDatasetRowsForSource(
        string? sourceId,
        ReportAccessQueryContext? accessContext = null,
        int recordLimit = DefaultRecordLimit)
    {
        if (string.IsNullOrWhiteSpace(sourceId) || IsCombinedSourceId(sourceId))
        {
            return BuildDatasetRows(accessContext, recordLimit);
        }

        var records = ReportPackRunReadService.FilterWorkflowRecords(
            _workflowService?.ListRecords(Math.Clamp(recordLimit, 1, 500)) ?? [],
            accessContext);
        var portfolioCuts = ReportPackRunReadService.BuildPortfolioReportingCuts(records);
        var normalizedSourceId = sourceId.Trim();
        if (string.Equals(normalizedSourceId, CertifiedOperationalDataMartSourceId, StringComparison.OrdinalIgnoreCase))
        {
            var combinedRows = BuildDatasetRows(portfolioCuts, ReportPackRunReadService.BuildPortfolioReportingAnalyticsRows(portfolioCuts), ReportPackRunReadService.BuildCrossFundConsolidations(portfolioCuts));
            return BuildCertifiedDataMartRows(normalizedSourceId, combinedRows);
        }

        if (string.Equals(normalizedSourceId, PortfolioReportingCutsSourceId, StringComparison.OrdinalIgnoreCase))
        {
            return portfolioCuts
                .Select(ReportPackRunReadService.BuildReportWriterPortfolioCutRow)
                .ToArray();
        }

        if (string.Equals(normalizedSourceId, TopNContributionAnalyticsSourceId, StringComparison.OrdinalIgnoreCase))
        {
            return ReportPackRunReadService.BuildPortfolioReportingAnalyticsRows(portfolioCuts)
                .Select(ReportPackRunReadService.BuildReportWriterAnalyticsRow)
                .ToArray();
        }

        if (string.Equals(normalizedSourceId, CrossFundConsolidationSourceId, StringComparison.OrdinalIgnoreCase))
        {
            return ReportPackRunReadService.BuildCrossFundConsolidations(portfolioCuts)
                .Select(ReportPackRunReadService.BuildReportWriterCrossFundRow)
                .ToArray();
        }

        throw new ArgumentException($"Unknown report-writer dataset source '{sourceId}'.", nameof(sourceId));
    }

    public static string? GetKnownDatasetSourceLabel(string? sourceId)
    {
        if (string.IsNullOrWhiteSpace(sourceId))
        {
            return "Retained reporting rows";
        }

        var normalizedSourceId = sourceId.Trim();
        if (string.Equals(normalizedSourceId, RetainedReportingRowsSourceId, StringComparison.OrdinalIgnoreCase))
        {
            return "Retained reporting rows";
        }

        if (string.Equals(normalizedSourceId, PortfolioReportingCutsSourceId, StringComparison.OrdinalIgnoreCase))
        {
            return "Portfolio reporting cuts";
        }

        if (string.Equals(normalizedSourceId, TopNContributionAnalyticsSourceId, StringComparison.OrdinalIgnoreCase))
        {
            return "Top-N contribution analytics";
        }

        if (string.Equals(normalizedSourceId, CrossFundConsolidationSourceId, StringComparison.OrdinalIgnoreCase))
        {
            return "Cross-fund consolidation";
        }

        if (string.Equals(normalizedSourceId, CertifiedOperationalDataMartSourceId, StringComparison.OrdinalIgnoreCase))
        {
            return "Certified operational data mart";
        }

        return null;
    }

    public IReadOnlyList<WorkstationReportWriterFieldPayload> BuildFieldCatalog(
        ReportAccessQueryContext? accessContext = null,
        int recordLimit = DefaultRecordLimit) =>
        BuildFieldCatalog(BuildDatasetRows(accessContext, recordLimit));

    public static IReadOnlyList<WorkstationReportWriterDatasetSourcePayload> BuildDatasetSources(
        IReadOnlyList<PortfolioReportingCutDto> portfolioCuts,
        IReadOnlyList<PortfolioReportingAnalyticsRowDto> analyticsRows,
        IReadOnlyList<CrossFundReportingConsolidationDto> crossFundRows)
    {
        var portfolioRows = portfolioCuts
            .Select(ReportPackRunReadService.BuildReportWriterPortfolioCutRow)
            .ToArray();
        var analyticsDatasetRows = analyticsRows
            .Select(ReportPackRunReadService.BuildReportWriterAnalyticsRow)
            .ToArray();
        var crossFundDatasetRows = crossFundRows
            .Select(ReportPackRunReadService.BuildReportWriterCrossFundRow)
            .ToArray();
        var combinedRows = portfolioRows
            .Concat(analyticsDatasetRows)
            .Concat(crossFundDatasetRows)
            .ToArray();

        return
        [
            ..BuildDatasetSource(
                RetainedReportingRowsSourceId,
                "Retained reporting rows",
                "Source-backed portfolio cuts, Top-N/contribution analytics, and cross-fund consolidation rows available to no-code report-writer previews.",
                combinedRows,
                ["portfolio-cuts", "top-n", "contribution", "cross-fund"]),
            ..BuildDatasetSource(
                PortfolioReportingCutsSourceId,
                "Portfolio reporting cuts",
                "Fund, strategy, and user-tag exposure, cash, P&L, shadow-NAV, and source-count rows.",
                portfolioRows,
                ["portfolio-cuts", "exposure", "cash", "pnl", "shadow-nav"]),
            ..BuildDatasetSource(
                TopNContributionAnalyticsSourceId,
                "Top-N contribution analytics",
                "Security, strategy, and factor analytics rows with Top-N ranking, P&L contribution, and heat-map intensity.",
                analyticsDatasetRows,
                ["top-n", "contribution", "analytics", "pnl"]),
            ..BuildDatasetSource(
                CrossFundConsolidationSourceId,
                "Cross-fund consolidation",
                "Company, fund, and entity roll-up rows for cross-fund reporting and benchmarking.",
                crossFundDatasetRows,
                ["cross-fund", "consolidation", "benchmark"]),
            ..BuildDatasetSource(
                CertifiedOperationalDataMartSourceId,
                "Certified operational data mart",
                "Row-level lineage index for retained reporting rows published as a certified operational data mart candidate for downstream warehouse, reporting, audit, and operator consumers.",
                BuildCertifiedDataMartRows(CertifiedOperationalDataMartSourceId, combinedRows),
                ["certified-data-mart", "lineage", "evidence-index", "warehouse", "reporting"])
        ];
    }

    private static IReadOnlyList<WorkstationReportWriterDatasetSourcePayload> BuildDatasetSource(
        string sourceId,
        string label,
        string description,
        IReadOnlyList<IReadOnlyDictionary<string, string>> rows,
        IReadOnlyList<string> tags)
    {
        if (rows.Count == 0)
        {
            return [];
        }

        var fields = BuildFieldCatalog(rows);
        var hasRowLineage = rows.Any(static row => row.ContainsKey("rowLineageKey"));
        var hasEvidenceIndex = rows.Any(static row => row.ContainsKey("evidenceIndex"));

        return
        [
            new WorkstationReportWriterDatasetSourcePayload(
                sourceId,
                label,
                description,
                rows.Count,
                fields,
                rows,
                tags,
                CertificationState: BuildCertificationState(rows),
                ValidationState: BuildValidationState(rows),
                ReconciliationState: BuildReconciliationState(rows),
                RefreshCadence: DefaultRefreshCadence,
                Owner: DefaultOwner,
                Version: BuildSourceVersion(sourceId, rows),
                ReleaseApproval: BuildReleaseApproval(rows),
                LineageManifest: BuildLineageManifest(sourceId),
                SourceRunIds: BuildSourceRunIds(sourceId, rows),
                PermittedConsumers: BuildPermittedConsumers(tags),
                RowLineageKeyField: hasRowLineage ? "rowLineageKey" : null,
                EvidenceIndexField: hasEvidenceIndex ? "evidenceIndex" : null)
        ];
    }

    private static IReadOnlyList<IReadOnlyDictionary<string, string>> BuildCertifiedDataMartRows(
        string sourceId,
        IReadOnlyList<IReadOnlyDictionary<string, string>> rows)
    {
        return rows
            .Select((row, index) =>
            {
                var dataset = GetRowValue(row, "dataset") ?? "reporting-row";
                var stableId = FirstRowValue(row, "cutId", "analyticsId", "consolidationId", "label")
                    ?? $"{dataset}:row-{index + 1}";
                var sourceRunId = FirstRowValue(row, "sourceRunIds", "versionStamp", "cutId", "analyticsId", "consolidationId")
                    ?? $"{sourceId}:row-{index + 1}";
                var enriched = new Dictionary<string, string>(row, StringComparer.OrdinalIgnoreCase)
                {
                    ["sourceRunIds"] = sourceRunId,
                    ["rowLineageKey"] = $"{sourceId}:{dataset}:{stableId}",
                    ["lineageManifest"] = BuildLineageManifest(sourceId),
                    ["evidenceIndex"] = $"/api/workstation/evidence/search?dataset={Uri.EscapeDataString(dataset)}&row={Uri.EscapeDataString(stableId)}",
                    ["validationState"] = IsSourceBackedRow(row) ? "Passed" : "ReviewRequired",
                    ["reconciliationState"] = BuildRowReconciliationState(row),
                    ["certificationState"] = IsSourceBackedRow(row) ? "SourceBacked" : "ReviewRequired",
                    ["permittedConsumers"] = string.Join("|", BuildPermittedConsumers(["reporting", "warehouse", "audit", "operations"]))
                };

                return enriched;
            })
            .ToArray();
    }

    private static string BuildCertificationState(IReadOnlyList<IReadOnlyDictionary<string, string>> rows) =>
        rows.Count > 0 && rows.All(IsSourceBackedRow) ? "SourceBacked" : "ReviewRequired";

    private static string BuildValidationState(IReadOnlyList<IReadOnlyDictionary<string, string>> rows) =>
        rows.Count > 0 && rows.All(IsSourceBackedRow) ? "Passed" : "ReviewRequired";

    private static string BuildReconciliationState(IReadOnlyList<IReadOnlyDictionary<string, string>> rows) =>
        rows.Count > 0 && rows.All(IsReconciliationLinkedRow) ? "Linked" : "ReviewRequired";

    private static string BuildReleaseApproval(IReadOnlyList<IReadOnlyDictionary<string, string>> rows) =>
        rows.Count > 0 && rows.All(IsSourceBackedRow)
            ? "Source-backed rows are eligible for governed report approval."
            : "Controller review is required before certification.";

    private static string BuildSourceVersion(string sourceId, IReadOnlyList<IReadOnlyDictionary<string, string>> rows)
    {
        var sourceRunIds = BuildSourceRunIds(sourceId, rows);
        return $"{sourceId}:rows-{rows.Count}:sources-{sourceRunIds.Count}";
    }

    private static string BuildLineageManifest(string sourceId) =>
        $"/api/workstation/reporting?datasetSourceId={Uri.EscapeDataString(sourceId)}#lineage-manifest";

    private static IReadOnlyList<string> BuildSourceRunIds(
        string sourceId,
        IReadOnlyList<IReadOnlyDictionary<string, string>> rows)
    {
        var ids = rows
            .Select(static row => FirstRowValue(row, "sourceRunIds", "versionStamp", "cutId", "analyticsId", "consolidationId"))
            .Where(static value => !string.IsNullOrWhiteSpace(value))
            .Select(static value => value!)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .Take(25)
            .ToArray();

        return ids.Length == 0 ? [$"{sourceId}:rows-{rows.Count}"] : ids;
    }

    private static IReadOnlyList<string> BuildPermittedConsumers(IReadOnlyList<string> tags)
    {
        var consumers = new List<string> { "Reporting", "Audit" };
        if (tags.Any(static tag => tag.Contains("warehouse", StringComparison.OrdinalIgnoreCase)
                                  || tag.Contains("data-mart", StringComparison.OrdinalIgnoreCase)
                                  || tag.Contains("ledger", StringComparison.OrdinalIgnoreCase)))
        {
            consumers.Add("DataWarehouse");
        }

        if (tags.Any(static tag => tag.Contains("operations", StringComparison.OrdinalIgnoreCase)
                                  || tag.Contains("portfolio", StringComparison.OrdinalIgnoreCase)
                                  || tag.Contains("cross-fund", StringComparison.OrdinalIgnoreCase)))
        {
            consumers.Add("Operations");
        }

        if (tags.Any(static tag => tag.Contains("investment", StringComparison.OrdinalIgnoreCase)
                                  || tag.Contains("top-n", StringComparison.OrdinalIgnoreCase)))
        {
            consumers.Add("Investment");
        }

        return consumers.Distinct(StringComparer.OrdinalIgnoreCase).ToArray();
    }

    private static bool IsSourceBackedRow(IReadOnlyDictionary<string, string> row)
    {
        var sourceCountText = GetRowValue(row, "sourceCount");
        return string.IsNullOrWhiteSpace(sourceCountText)
               || (int.TryParse(sourceCountText, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var sourceCount)
                   && sourceCount > 0);
    }

    private static bool IsReconciliationLinkedRow(IReadOnlyDictionary<string, string> row)
    {
        var readyText = GetRowValue(row, "isReady");
        return string.IsNullOrWhiteSpace(readyText)
               || bool.TryParse(readyText, out var ready) && ready;
    }

    private static string BuildRowReconciliationState(IReadOnlyDictionary<string, string> row) =>
        IsReconciliationLinkedRow(row) ? "Linked" : "ReviewRequired";

    private static string? FirstRowValue(IReadOnlyDictionary<string, string> row, params string[] keys)
    {
        foreach (var key in keys)
        {
            var value = GetRowValue(row, key);
            if (!string.IsNullOrWhiteSpace(value))
            {
                return value;
            }
        }

        return null;
    }

    private static string? GetRowValue(IReadOnlyDictionary<string, string> row, string key) =>
        row.TryGetValue(key, out var value) && !string.IsNullOrWhiteSpace(value) ? value.Trim() : null;

    public static IReadOnlyList<WorkstationReportWriterFieldPayload> BuildFieldCatalog(
        IReadOnlyList<IReadOnlyDictionary<string, string>> rows)
    {
        ArgumentNullException.ThrowIfNull(rows);
        return rows
            .SelectMany(static row => row.Keys)
            .Where(static field => !string.IsNullOrWhiteSpace(field))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .Select(BuildFieldPayload)
            .OrderBy(static field => FieldRoleOrder(field.Role))
            .ThenBy(static field => field.Label, StringComparer.OrdinalIgnoreCase)
            .ThenBy(static field => field.Name, StringComparer.OrdinalIgnoreCase)
            .ToArray();
    }

    public static IReadOnlyList<IReadOnlyDictionary<string, string>> BuildDatasetRows(
        WorkstationReportingPayload reporting)
    {
        ArgumentNullException.ThrowIfNull(reporting);
        return BuildDatasetRows(
            reporting.PortfolioCuts ?? [],
            reporting.AnalyticsRows ?? [],
            reporting.CrossFundConsolidations ?? []);
    }

    public static IReadOnlyList<IReadOnlyDictionary<string, string>> BuildDatasetRows(
        IReadOnlyList<PortfolioReportingCutDto> portfolioCuts,
        IReadOnlyList<PortfolioReportingAnalyticsRowDto> analyticsRows,
        IReadOnlyList<CrossFundReportingConsolidationDto> crossFundRows)
    {
        var rows = new List<IReadOnlyDictionary<string, string>>(
            portfolioCuts.Count + analyticsRows.Count + crossFundRows.Count);
        rows.AddRange(portfolioCuts.Select(ReportPackRunReadService.BuildReportWriterPortfolioCutRow));
        rows.AddRange(analyticsRows.Select(ReportPackRunReadService.BuildReportWriterAnalyticsRow));
        rows.AddRange(crossFundRows.Select(ReportPackRunReadService.BuildReportWriterCrossFundRow));
        return rows;
    }

    private static bool IsCombinedSourceId(string sourceId) =>
        string.Equals(sourceId.Trim(), RetainedReportingRowsSourceId, StringComparison.OrdinalIgnoreCase);

    private static WorkstationReportWriterFieldPayload BuildFieldPayload(string field)
    {
        var normalizedField = field.Trim();
        if (KnownFields.TryGetValue(normalizedField, out var known))
        {
            return new WorkstationReportWriterFieldPayload(
                known.Name,
                known.Label,
                known.Role,
                known.DataType,
                known.Dataset,
                known.Description);
        }

        var dataType = GuessFieldDataType(normalizedField);
        var role = dataType is "decimal" or "integer" ? "metric" : "dimension";
        return new WorkstationReportWriterFieldPayload(
            normalizedField,
            FormatFieldLabel(normalizedField),
            role,
            dataType,
            "Report writer dataset",
            "Field discovered from the source-backed report-writer dataset.");
    }

    private static int FieldRoleOrder(string role) =>
        role.Equals("dimension", StringComparison.OrdinalIgnoreCase) ? 0
        : role.Equals("metric", StringComparison.OrdinalIgnoreCase) ? 1
        : role.Equals("generated", StringComparison.OrdinalIgnoreCase) ? 2
        : 3;

    private static string GuessFieldDataType(string field)
    {
        var normalized = field.ToLowerInvariant();
        if (normalized.Contains("count", StringComparison.Ordinal) || normalized == "rank")
        {
            return "integer";
        }

        if (normalized.Contains("pnl", StringComparison.Ordinal)
            || normalized.Contains("cash", StringComparison.Ordinal)
            || normalized.Contains("value", StringComparison.Ordinal)
            || normalized.Contains("exposure", StringComparison.Ordinal)
            || normalized.Contains("nav", StringComparison.Ordinal)
            || normalized.Contains("percent", StringComparison.Ordinal)
            || normalized.Contains("intensity", StringComparison.Ordinal)
            || normalized.Contains("settlement", StringComparison.Ordinal)
            || normalized.Contains("variance", StringComparison.Ordinal))
        {
            return "decimal";
        }

        if (normalized.Contains("date", StringComparison.Ordinal) || normalized.Contains("asof", StringComparison.Ordinal))
        {
            return "datetime";
        }

        return "string";
    }

    private static string FormatFieldLabel(string field)
    {
        var spaced = field
            .Replace('_', ' ')
            .Replace('-', ' ');
        var chars = new List<char>(spaced.Length + 8);
        for (var index = 0; index < spaced.Length; index++)
        {
            var current = spaced[index];
            if (index > 0 && char.IsUpper(current) && char.IsLower(spaced[index - 1]))
            {
                chars.Add(' ');
            }

            chars.Add(current);
        }

        var label = new string(chars.ToArray()).Trim();
        return string.IsNullOrWhiteSpace(label) ? field : char.ToUpperInvariant(label[0]) + label[1..];
    }

    private sealed record ReportWriterFieldCatalogEntry(
        string Name,
        string Label,
        string Role,
        string DataType,
        string Dataset,
        string? Description);
}
