using Meridian.Contracts.Workstation;

namespace Meridian.Ui.Shared.Services;

public sealed class ReportWriterDatasetSourceService
{
    private const int DefaultRecordLimit = 200;
    private static readonly IReadOnlyDictionary<string, ReportWriterFieldCatalogEntry> KnownFields =
        new Dictionary<string, ReportWriterFieldCatalogEntry>(StringComparer.OrdinalIgnoreCase)
        {
            ["dataset"] = new("dataset", "Dataset", "dimension", "string", "All", "Source dataset family for the row."),
            ["cutId"] = new("cutId", "Cut ID", "dimension", "string", "Portfolio cuts", "Stable portfolio reporting cut identifier."),
            ["analyticsId"] = new("analyticsId", "Analytics ID", "dimension", "string", "Top-N analytics", "Stable analytics row identifier."),
            ["consolidationId"] = new("consolidationId", "Consolidation ID", "dimension", "string", "Cross-fund consolidation", "Stable consolidation row identifier."),
            ["label"] = new("label", "Label", "dimension", "string", "All", "Display label for the reporting row."),
            ["kind"] = new("kind", "Kind", "dimension", "string", "All", "Reporting row kind such as fund, strategy, user tag, or analytics type."),
            ["scope"] = new("scope", "Scope", "dimension", "string", "All", "Reporting scope used for grouping and drilldown."),
            ["strategy"] = new("strategy", "Strategy", "dimension", "string", "Portfolio cuts", "Strategy tag for strategy-level reporting cuts."),
            ["security"] = new("security", "Security", "dimension", "string", "Top-N analytics", "Security or instrument label where available."),
            ["symbol"] = new("symbol", "Symbol", "dimension", "string", "Top-N analytics", "Ticker or symbol where available."),
            ["classification"] = new("classification", "Classification", "dimension", "string", "Top-N analytics", "Sector, factor, or classification bucket."),
            ["currency"] = new("currency", "Currency", "dimension", "string", "All", "ISO currency for monetary values."),
            ["rank"] = new("rank", "Rank", "dimension", "integer", "Top-N analytics", "Top-N rank for winner and laggard rows."),
            ["grossExposure"] = new("grossExposure", "Gross exposure", "metric", "decimal", "Portfolio cuts", "Gross portfolio exposure."),
            ["netExposure"] = new("netExposure", "Net exposure", "metric", "decimal", "Portfolio cuts", "Net portfolio exposure."),
            ["longMarketValue"] = new("longMarketValue", "Long market value", "metric", "decimal", "Portfolio cuts", "Long-side market value."),
            ["shortMarketValue"] = new("shortMarketValue", "Short market value", "metric", "decimal", "Portfolio cuts", "Short-side market value."),
            ["totalCash"] = new("totalCash", "Total cash", "metric", "decimal", "Portfolio cuts", "Cash available for the cut."),
            ["pendingSettlement"] = new("pendingSettlement", "Pending settlement", "metric", "decimal", "Portfolio cuts", "Pending settlement amount."),
            ["realizedPnl"] = new("realizedPnl", "Realized P&L", "metric", "decimal", "Portfolio reporting", "Realized profit and loss."),
            ["unrealizedPnl"] = new("unrealizedPnl", "Unrealized P&L", "metric", "decimal", "Portfolio reporting", "Unrealized profit and loss."),
            ["totalPnl"] = new("totalPnl", "Total P&L", "metric", "decimal", "Portfolio reporting", "Total profit and loss."),
            ["pnl"] = new("pnl", "P&L", "metric", "decimal", "Portfolio reporting", "Profit and loss source field for contribution grids."),
            ["shadowNav"] = new("shadowNav", "Shadow NAV", "metric", "decimal", "Portfolio cuts", "Parallel shadow NAV value."),
            ["shadowNavVariance"] = new("shadowNavVariance", "Shadow NAV variance", "metric", "decimal", "Portfolio cuts", "Variance between shadow NAV and supporting source values."),
            ["contributionPercent"] = new("contributionPercent", "Contribution %", "generated", "decimal", "Top-N analytics", "Signed contribution percentage generated by analytics or contribution grids."),
            ["heatMapIntensity"] = new("heatMapIntensity", "Heat-map intensity", "metric", "decimal", "Top-N analytics", "Absolute contribution intensity for heat-map style reporting."),
            ["sourceCount"] = new("sourceCount", "Source count", "metric", "integer", "All", "Count of source-backed records supporting the row."),
            ["fundCount"] = new("fundCount", "Fund count", "metric", "integer", "Cross-fund consolidation", "Number of funds included in the consolidation row."),
            ["entityCount"] = new("entityCount", "Entity count", "metric", "integer", "Cross-fund consolidation", "Number of entities included in the consolidation row."),
            ["accountCount"] = new("accountCount", "Account count", "metric", "integer", "Cross-fund consolidation", "Number of accounts included in the consolidation row."),
            ["runCount"] = new("runCount", "Run count", "metric", "integer", "Cross-fund consolidation", "Number of retained runs included in the row."),
            ["asOfUtc"] = new("asOfUtc", "As of UTC", "dimension", "datetime", "Top-N analytics", "Source timestamp for analytics rows."),
            ["asOf"] = new("asOf", "As of", "dimension", "datetime", "Portfolio cuts", "Source timestamp for portfolio cuts."),
            ["versionStamp"] = new("versionStamp", "Version stamp", "dimension", "string", "All", "Stable version stamp for audit and export lineage."),
            ["tags"] = new("tags", "Tags", "dimension", "string", "All", "Pipe-delimited user and system tags."),
            ["readinessSummary"] = new("readinessSummary", "Readiness summary", "dimension", "string", "All", "Readiness text for delivery and export review.")
        };

    private readonly ReportPackWorkflowService? _workflowService;

    public ReportWriterDatasetSourceService(ReportPackWorkflowService? workflowService = null)
    {
        _workflowService = workflowService;
    }

    public IReadOnlyList<IReadOnlyDictionary<string, string>> BuildDatasetRows(
        ReportAccessQueryContext? accessContext = null,
        int recordLimit = DefaultRecordLimit)
    {
        var records = ReportPackRunReadService.FilterWorkflowRecords(
            _workflowService?.ListRecords(Math.Clamp(recordLimit, 1, 500)) ?? [],
            accessContext);
        var portfolioCuts = ReportPackRunReadService.BuildPortfolioReportingCuts(records);
        var analyticsRows = ReportPackRunReadService.BuildPortfolioReportingAnalyticsRows(portfolioCuts);
        var crossFundRows = ReportPackRunReadService.BuildCrossFundConsolidations(portfolioCuts);

        return BuildDatasetRows(portfolioCuts, analyticsRows, crossFundRows);
    }

    public IReadOnlyList<WorkstationReportWriterFieldPayload> BuildFieldCatalog(
        ReportAccessQueryContext? accessContext = null,
        int recordLimit = DefaultRecordLimit) =>
        BuildFieldCatalog(BuildDatasetRows(accessContext, recordLimit));

    public static IReadOnlyList<WorkstationReportWriterFieldPayload> BuildFieldCatalog(
        IReadOnlyList<IReadOnlyDictionary<string, string>> rows)
    {
        ArgumentNullException.ThrowIfNull(rows);
        return rows
            .SelectMany(static row => row.Keys)
            .Where(static field => !string.IsNullOrWhiteSpace(field))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .Select(BuildFieldPayload)
            .OrderBy(static field => FieldRoleOrder(field.Role))
            .ThenBy(static field => field.Label, StringComparer.OrdinalIgnoreCase)
            .ThenBy(static field => field.Name, StringComparer.OrdinalIgnoreCase)
            .ToArray();
    }

    public static IReadOnlyList<IReadOnlyDictionary<string, string>> BuildDatasetRows(
        WorkstationReportingPayload reporting)
    {
        ArgumentNullException.ThrowIfNull(reporting);
        return BuildDatasetRows(
            reporting.PortfolioCuts ?? [],
            reporting.AnalyticsRows ?? [],
            reporting.CrossFundConsolidations ?? []);
    }

    private static IReadOnlyList<IReadOnlyDictionary<string, string>> BuildDatasetRows(
        IReadOnlyList<PortfolioReportingCutDto> portfolioCuts,
        IReadOnlyList<PortfolioReportingAnalyticsRowDto> analyticsRows,
        IReadOnlyList<CrossFundReportingConsolidationDto> crossFundRows)
    {
        var rows = new List<IReadOnlyDictionary<string, string>>(
            portfolioCuts.Count + analyticsRows.Count + crossFundRows.Count);
        rows.AddRange(portfolioCuts.Select(ReportPackRunReadService.BuildReportWriterPortfolioCutRow));
        rows.AddRange(analyticsRows.Select(ReportPackRunReadService.BuildReportWriterAnalyticsRow));
        rows.AddRange(crossFundRows.Select(ReportPackRunReadService.BuildReportWriterCrossFundRow));
        return rows;
    }

    private static WorkstationReportWriterFieldPayload BuildFieldPayload(string field)
    {
        var normalizedField = field.Trim();
        if (KnownFields.TryGetValue(normalizedField, out var known))
        {
            return new WorkstationReportWriterFieldPayload(
                known.Name,
                known.Label,
                known.Role,
                known.DataType,
                known.Dataset,
                known.Description);
        }

        var dataType = GuessFieldDataType(normalizedField);
        var role = dataType is "decimal" or "integer" ? "metric" : "dimension";
        return new WorkstationReportWriterFieldPayload(
            normalizedField,
            FormatFieldLabel(normalizedField),
            role,
            dataType,
            "Report writer dataset",
            "Field discovered from the source-backed report-writer dataset.");
    }

    private static int FieldRoleOrder(string role) =>
        role.Equals("dimension", StringComparison.OrdinalIgnoreCase) ? 0
        : role.Equals("metric", StringComparison.OrdinalIgnoreCase) ? 1
        : role.Equals("generated", StringComparison.OrdinalIgnoreCase) ? 2
        : 3;

    private static string GuessFieldDataType(string field)
    {
        var normalized = field.ToLowerInvariant();
        if (normalized.Contains("count", StringComparison.Ordinal) || normalized == "rank")
        {
            return "integer";
        }

        if (normalized.Contains("pnl", StringComparison.Ordinal)
            || normalized.Contains("cash", StringComparison.Ordinal)
            || normalized.Contains("value", StringComparison.Ordinal)
            || normalized.Contains("exposure", StringComparison.Ordinal)
            || normalized.Contains("nav", StringComparison.Ordinal)
            || normalized.Contains("percent", StringComparison.Ordinal)
            || normalized.Contains("intensity", StringComparison.Ordinal)
            || normalized.Contains("settlement", StringComparison.Ordinal)
            || normalized.Contains("variance", StringComparison.Ordinal))
        {
            return "decimal";
        }

        if (normalized.Contains("date", StringComparison.Ordinal) || normalized.Contains("asof", StringComparison.Ordinal))
        {
            return "datetime";
        }

        return "string";
    }

    private static string FormatFieldLabel(string field)
    {
        var spaced = field
            .Replace('_', ' ')
            .Replace('-', ' ');
        var chars = new List<char>(spaced.Length + 8);
        for (var index = 0; index < spaced.Length; index++)
        {
            var current = spaced[index];
            if (index > 0 && char.IsUpper(current) && char.IsLower(spaced[index - 1]))
            {
                chars.Add(' ');
            }

            chars.Add(current);
        }

        var label = new string(chars.ToArray()).Trim();
        return string.IsNullOrWhiteSpace(label) ? field : char.ToUpperInvariant(label[0]) + label[1..];
    }

    private sealed record ReportWriterFieldCatalogEntry(
        string Name,
        string Label,
        string Role,
        string DataType,
        string Dataset,
        string? Description);
}
