using System.Text.Json.Serialization;

namespace Meridian.Contracts.Operations;

/// <summary>
/// Origin classification carried by any figure or read model that can be produced from something
/// other than real operational data. The point of the signal is fail-closed honesty: no operator,
/// on either client, may mistake simulated, seeded, or sample output for real data. Every read
/// model that can originate from non-real data carries this signal and propagates it outward;
/// surfaces that only ever show real data may default to <see cref="Real"/>.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter<DataProvenance>))]
public enum DataProvenance : byte
{
    /// <summary>Real operational data captured from a durable production source.</summary>
    Real = 0,

    /// <summary>
    /// Deterministically generated by a simulation, paper, or backtest path (e.g. a synthetic
    /// streaming source or a shadow-book valuation). Numbers move, but none of it is real.
    /// </summary>
    Simulated = 1,

    /// <summary>
    /// Deterministically seeded fixture data shipped so a new operator can explore the product
    /// without credentials (e.g. demo-mode market snapshots).
    /// </summary>
    Seeded = 2,

    /// <summary>Illustrative sample or placeholder data with no operational meaning.</summary>
    Sample = 3
}

/// <summary>
/// Shared helpers for reasoning about and rendering a <see cref="DataProvenance"/> signal. Kept in
/// the contracts layer so both clients, the API endpoints, and the DI policy render one label.
/// </summary>
public static class DataProvenanceExtensions
{
    /// <summary>True for anything other than real operational data.</summary>
    public static bool IsNonReal(this DataProvenance provenance) => provenance != DataProvenance.Real;

    /// <summary>
    /// True when the provenance must be surfaced as a persistent, non-dismissable operator badge.
    /// </summary>
    public static bool RequiresBadge(this DataProvenance provenance) => provenance.IsNonReal();

    /// <summary>
    /// Short, uppercase operator-facing label (e.g. <c>SIMULATED</c>). Returns <c>null</c> for real
    /// data so callers can treat "no label" and "real" identically.
    /// </summary>
    public static string? Label(this DataProvenance provenance) => provenance switch
    {
        DataProvenance.Simulated => "SIMULATED",
        DataProvenance.Seeded => "SEEDED",
        DataProvenance.Sample => "SAMPLE",
        _ => null
    };

    /// <summary>Lower-case token used on the wire and by clients (e.g. <c>simulated</c>).</summary>
    public static string Token(this DataProvenance provenance) => provenance switch
    {
        DataProvenance.Simulated => "simulated",
        DataProvenance.Seeded => "seeded",
        DataProvenance.Sample => "sample",
        _ => "real"
    };

    /// <summary>
    /// Parses a loose provenance token (case-insensitive). Unknown tokens fall back to
    /// <see cref="DataProvenance.Simulated"/> — never <see cref="DataProvenance.Real"/> — so an
    /// unrecognized value can never be silently upgraded into "real".
    /// </summary>
    public static DataProvenance ParseTokenOrSimulated(string? token) => token?.Trim().ToLowerInvariant() switch
    {
        "real" or "live" => DataProvenance.Real,
        "seeded" or "seed" or "demo" or "fixture" => DataProvenance.Seeded,
        "sample" or "placeholder" => DataProvenance.Sample,
        null or "" => DataProvenance.Simulated,
        _ => DataProvenance.Simulated
    };

    /// <summary>
    /// Folds many origins into the one a derived figure must carry: the strongest non-real
    /// provenance among the inputs, or <see cref="DataProvenance.Real"/> only when every input is
    /// real. A derived figure — a valuation draft, a NAV, a report pack — is never more real than
    /// its least-real input, so this is the single rule every derivation uses.
    /// </summary>
    /// <remarks>
    /// "Strongest" follows the <see cref="DataProvenance"/> ordering, where a lower value is the
    /// stronger claim: <see cref="DataProvenance.Simulated"/> outranks
    /// <see cref="DataProvenance.Seeded"/>, which outranks <see cref="DataProvenance.Sample"/>.
    /// </remarks>
    public static DataProvenance Strongest(IEnumerable<DataProvenance> provenances)
    {
        ArgumentNullException.ThrowIfNull(provenances);

        var strongest = DataProvenance.Real;
        foreach (var provenance in provenances)
        {
            if (!provenance.IsNonReal())
            {
                continue;
            }

            if (strongest == DataProvenance.Real || provenance < strongest)
            {
                strongest = provenance;
            }
        }

        return strongest;
    }

    /// <summary>
    /// Unambiguous, structured simulated-origin markers, matched by exact (trimmed,
    /// case-insensitive) equality — never by substring — so legitimate values like
    /// "Sample Custodian" or "fixture-bank" are not mistaken for a simulated origin. An explicit
    /// provenance mark is always the primary gate; this token table is the shared safety net for a
    /// source that is labeled simulated while the record forgot to carry the mark. The ledger
    /// append boundary (`AccountingPostingCommandValidator`) enforces the same table.
    /// </summary>
    private static readonly string[] SimulatedOriginTokens =
    [
        "simulated", "simulation", "synthetic", "backtest",
        "seeded", "seed", "demo", "fixture",
        "sample", "placeholder"
    ];

    /// <summary>
    /// True when a source-system or source-type value is, exactly, one of the structured
    /// simulated-origin tokens.
    /// </summary>
    public static bool IsSimulatedOriginToken(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return false;
        }

        var trimmed = value.Trim();
        foreach (var token in SimulatedOriginTokens)
        {
            if (string.Equals(trimmed, token, StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }
}

/// <summary>
/// A persistent, non-dismissable provenance badge both clients render identically. Constructed only
/// for non-real provenance; <see cref="TryCreate"/> returns <c>null</c> for real data so a real
/// surface renders no badge at all.
/// </summary>
public sealed record DataProvenanceBadge(
    DataProvenance Provenance,
    string Label,
    string Detail)
{
    /// <summary>Provenance badges are always persistent and can never be dismissed by the operator.</summary>
    public bool Dismissable => false;

    /// <summary>
    /// Builds the badge for a non-real provenance, or <c>null</c> for <see cref="DataProvenance.Real"/>.
    /// </summary>
    public static DataProvenanceBadge? TryCreate(DataProvenance provenance, string? detail = null)
    {
        if (!provenance.IsNonReal())
        {
            return null;
        }

        return new DataProvenanceBadge(
            provenance,
            provenance.Label() ?? provenance.Token().ToUpperInvariant(),
            detail ?? DefaultDetail(provenance));
    }

    private static string DefaultDetail(DataProvenance provenance) => provenance switch
    {
        DataProvenance.Simulated =>
            "This data is simulated. Do not treat quotes, fills, valuations, or P&L as real.",
        DataProvenance.Seeded =>
            "This data is seeded demo data shipped without live credentials. It is not real market or account data.",
        DataProvenance.Sample =>
            "This is sample placeholder data with no operational meaning.",
        _ => string.Empty
    };
}
