using System.Text.Json;
using System.Text.Json.Serialization;
using Meridian.Contracts.Api;
using Meridian.Contracts.CertificatesOfDeposit;
using Meridian.Contracts.Commodities;
using Meridian.Contracts.CryptoCurrency;
using Meridian.Contracts.Deposits;
using Meridian.Contracts.Derivatives;
using Meridian.Contracts.Equity;
using Meridian.Contracts.FixedIncome;
using Meridian.Contracts.Futures;
using Meridian.Contracts.FxSpot;
using Meridian.Contracts.MoneyMarketFunds;
using Meridian.Contracts.Options;
using Meridian.Contracts.SecurityMaster;
using Meridian.Contracts.Workstation;

namespace Meridian.Core.Serialization;

[JsonSourceGenerationOptions(
    WriteIndented = false,
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    PropertyNameCaseInsensitive = true,
    GenerationMode = JsonSourceGenerationMode.Default)]
[JsonSerializable(typeof(SecurityAliasDto))]
[JsonSerializable(typeof(SecurityAliasDto[]))]
[JsonSerializable(typeof(List<SecurityAliasDto>))]
[JsonSerializable(typeof(SecurityDetailDto))]
[JsonSerializable(typeof(SecurityEvidenceLinkDto))]
[JsonSerializable(typeof(SecurityEvidenceLinkDto[]))]
[JsonSerializable(typeof(List<SecurityEvidenceLinkDto>))]
[JsonSerializable(typeof(SecurityEconomicDefinitionRecord))]
[JsonSerializable(typeof(SecurityIdentifierDto))]
[JsonSerializable(typeof(SecurityIdentifierDto[]))]
[JsonSerializable(typeof(List<SecurityIdentifierDto>))]
[JsonSerializable(typeof(SecurityValidationIssueDto))]
[JsonSerializable(typeof(SecurityValidationIssueDto[]))]
[JsonSerializable(typeof(List<SecurityValidationIssueDto>))]
[JsonSerializable(typeof(SecurityValidationReportDto))]
[JsonSerializable(typeof(SecurityValidationSnapshotRequestDto))]
[JsonSerializable(typeof(SecurityValidationSnapshotDto))]
[JsonSerializable(typeof(SecurityValidationGateResultDto))]
[JsonSerializable(typeof(SecurityAssetProfileDefinitionDto))]
[JsonSerializable(typeof(SecurityAssetProfileDefinitionDto[]))]
[JsonSerializable(typeof(List<SecurityAssetProfileDefinitionDto>))]
[JsonSerializable(typeof(SecurityAssetProfileFieldDefinitionDto))]
[JsonSerializable(typeof(SecurityAssetProfileFieldDefinitionDto[]))]
[JsonSerializable(typeof(List<SecurityAssetProfileFieldDefinitionDto>))]
[JsonSerializable(typeof(SecurityAssetProfileDateOrderRuleDto))]
[JsonSerializable(typeof(SecurityAssetProfileIdentifierPreferenceDto))]
[JsonSerializable(typeof(SecurityAssetProfileTermsDto))]
[JsonSerializable(typeof(SecurityAssetProfileApprovalMetadataDto))]
[JsonSerializable(typeof(SecurityAssetProfileDraftRequestDto))]
[JsonSerializable(typeof(SecurityAssetProfileApprovalRequestDto))]
[JsonSerializable(typeof(SecurityAssetProfileRollbackRequestDto))]
[JsonSerializable(typeof(SecurityAssetProfileGovernanceAuditEventDto))]
[JsonSerializable(typeof(SecurityAssetProfileLineageDto))]
[JsonSerializable(typeof(SecurityAssetProfileGovernanceResultDto))]
[JsonSerializable(typeof(SecurityAssetProfilePromotionSignalDto))]
[JsonSerializable(typeof(SecurityAssetProfilePromotionSignalDto[]))]
[JsonSerializable(typeof(List<SecurityAssetProfilePromotionSignalDto>))]
[JsonSerializable(typeof(SecurityAssetProfilePromotionCandidateDto))]
[JsonSerializable(typeof(SecurityAssetProfilePromotionCandidateDto[]))]
[JsonSerializable(typeof(List<SecurityAssetProfilePromotionCandidateDto>))]
[JsonSerializable(typeof(PreferredEquityTermsDto))]
[JsonSerializable(typeof(ConvertibleEquityTermsDto))]
[JsonSerializable(typeof(BondReferenceDto))]
[JsonSerializable(typeof(BondReferenceDto[]))]
[JsonSerializable(typeof(List<BondReferenceDto>))]
[JsonSerializable(typeof(BondLifecycleDto))]
[JsonSerializable(typeof(BondAccrualConventionDto))]
[JsonSerializable(typeof(OptionContractReferenceDto))]
[JsonSerializable(typeof(OptionContractReferenceDto[]))]
[JsonSerializable(typeof(List<OptionContractReferenceDto>))]
[JsonSerializable(typeof(OptionSeriesDto))]
[JsonSerializable(typeof(OptionSeriesDto[]))]
[JsonSerializable(typeof(List<OptionSeriesDto>))]
[JsonSerializable(typeof(OptionChainSnapshotDto))]
[JsonSerializable(typeof(EquityReferenceDto))]
[JsonSerializable(typeof(EquityReferenceDto[]))]
[JsonSerializable(typeof(List<EquityReferenceDto>))]
[JsonSerializable(typeof(FutureReferenceDto))]
[JsonSerializable(typeof(FutureReferenceDto[]))]
[JsonSerializable(typeof(List<FutureReferenceDto>))]
[JsonSerializable(typeof(FxSpotReferenceDto))]
[JsonSerializable(typeof(FxSpotReferenceDto[]))]
[JsonSerializable(typeof(List<FxSpotReferenceDto>))]
[JsonSerializable(typeof(FxSpotPairsForCurrencyDto))]
[JsonSerializable(typeof(SwapReferenceDto))]
[JsonSerializable(typeof(SwapReferenceDto[]))]
[JsonSerializable(typeof(List<SwapReferenceDto>))]
[JsonSerializable(typeof(SwapLegDto))]
[JsonSerializable(typeof(SwapLegDto[]))]
[JsonSerializable(typeof(List<SwapLegDto>))]
[JsonSerializable(typeof(CommodityReferenceDto))]
[JsonSerializable(typeof(CommodityReferenceDto[]))]
[JsonSerializable(typeof(List<CommodityReferenceDto>))]
[JsonSerializable(typeof(CryptoReferenceDto))]
[JsonSerializable(typeof(CryptoReferenceDto[]))]
[JsonSerializable(typeof(List<CryptoReferenceDto>))]
[JsonSerializable(typeof(DepositReferenceDto))]
[JsonSerializable(typeof(DepositReferenceDto[]))]
[JsonSerializable(typeof(List<DepositReferenceDto>))]
[JsonSerializable(typeof(MoneyMarketFundReferenceDto))]
[JsonSerializable(typeof(MoneyMarketFundReferenceDto[]))]
[JsonSerializable(typeof(List<MoneyMarketFundReferenceDto>))]
[JsonSerializable(typeof(CertificateOfDepositReferenceDto))]
[JsonSerializable(typeof(CertificateOfDepositReferenceDto[]))]
[JsonSerializable(typeof(List<CertificateOfDepositReferenceDto>))]
[JsonSerializable(typeof(TradingParametersDto))]
[JsonSerializable(typeof(CorporateActionDto))]
[JsonSerializable(typeof(CorporateActionDto[]))]
[JsonSerializable(typeof(List<CorporateActionDto>))]
[JsonSerializable(typeof(SecurityMasterEventEnvelope))]
[JsonSerializable(typeof(SecurityMasterEventEnvelope[]))]
[JsonSerializable(typeof(List<SecurityMasterEventEnvelope>))]
[JsonSerializable(typeof(SecurityProjectionRecord))]
[JsonSerializable(typeof(SecuritySearchRequest))]
[JsonSerializable(typeof(SecuritySnapshotRecord))]
[JsonSerializable(typeof(SecuritySummaryDto))]
[JsonSerializable(typeof(SecuritySummaryDto[]))]
[JsonSerializable(typeof(List<SecuritySummaryDto>))]
[JsonSerializable(typeof(CreateSecurityRequest))]
[JsonSerializable(typeof(List<CreateSecurityRequest>))]
[JsonSerializable(typeof(AmendSecurityTermsRequest))]
[JsonSerializable(typeof(AmendPreferredEquityTermsRequest))]
[JsonSerializable(typeof(AmendConvertibleEquityTermsRequest))]
[JsonSerializable(typeof(DeactivateSecurityRequest))]
[JsonSerializable(typeof(ResolveSecurityRequest))]
[JsonSerializable(typeof(UpsertSecurityAliasRequest))]
[JsonSerializable(typeof(OperatorOverridesDto))]
[JsonSerializable(typeof(OperatorOverridesPatchRequest))]
[JsonSerializable(typeof(SecurityOverrideAuditEntryDto))]
[JsonSerializable(typeof(SecurityOverrideAuditEntryDto[]))]
[JsonSerializable(typeof(List<SecurityOverrideAuditEntryDto>))]
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSerializable(typeof(Dictionary<string, JsonElement>))]
[JsonSerializable(typeof(SecurityClassificationSummaryDto))]
[JsonSerializable(typeof(SecurityEconomicDefinitionSummaryDto))]
[JsonSerializable(typeof(SecurityIdentityDrillInDto))]
[JsonSerializable(typeof(SecurityMasterTrustSnapshotDto))]
[JsonSerializable(typeof(SecurityMasterEconomicDefinitionDrillInDto))]
[JsonSerializable(typeof(SecurityMasterTrustPostureDto))]
[JsonSerializable(typeof(SecurityMasterSourceCandidateDto))]
[JsonSerializable(typeof(SecurityMasterConflictAssessmentDto))]
[JsonSerializable(typeof(SecurityMasterIdentifierSummaryDto))]
[JsonSerializable(typeof(SecurityMasterProviderSymbolMappingDto))]
[JsonSerializable(typeof(SecurityMasterProviderSymbolMappingDto[]))]
[JsonSerializable(typeof(List<SecurityMasterProviderSymbolMappingDto>))]
[JsonSerializable(typeof(SecurityMasterSchemaCompatibilityDto))]
[JsonSerializable(typeof(SecurityMasterChangeHistoryItemDto))]
[JsonSerializable(typeof(SecurityMasterChangeHistoryItemDto[]))]
[JsonSerializable(typeof(List<SecurityMasterChangeHistoryItemDto>))]
[JsonSerializable(typeof(SecurityMasterScheduleSummaryDto))]
[JsonSerializable(typeof(SecurityMasterScheduleBookDto))]
[JsonSerializable(typeof(SecurityMasterScheduleEventDto))]
[JsonSerializable(typeof(SecurityMasterScheduleEventDto[]))]
[JsonSerializable(typeof(List<SecurityMasterScheduleEventDto>))]
[JsonSerializable(typeof(SecurityMasterFactorPointDto))]
[JsonSerializable(typeof(SecurityMasterFactorPointDto[]))]
[JsonSerializable(typeof(List<SecurityMasterFactorPointDto>))]
[JsonSerializable(typeof(SecurityMasterScheduleProvenanceDto))]
[JsonSerializable(typeof(SecurityMasterScheduleProvenanceDto[]))]
[JsonSerializable(typeof(List<SecurityMasterScheduleProvenanceDto>))]
[JsonSerializable(typeof(SecurityMasterLotModelDto))]
[JsonSerializable(typeof(SecurityMasterOpenLotReadModelDto))]
[JsonSerializable(typeof(SecurityMasterOpenLotDto))]
[JsonSerializable(typeof(SecurityMasterOpenLotDto[]))]
[JsonSerializable(typeof(List<SecurityMasterOpenLotDto>))]
[JsonSerializable(typeof(SecurityMasterOpenLotProvenanceDto))]
[JsonSerializable(typeof(SecurityMasterOpenLotProvenanceDto[]))]
[JsonSerializable(typeof(List<SecurityMasterOpenLotProvenanceDto>))]
[JsonSerializable(typeof(SecurityMasterDownstreamImpactDto))]
[JsonSerializable(typeof(SecurityMasterImpactLinkDto))]
[JsonSerializable(typeof(SecurityMasterRecommendedActionDto))]
[JsonSerializable(typeof(BulkResolveSecurityMasterConflictsRequest))]
[JsonSerializable(typeof(BulkResolveSecurityMasterConflictsResult))]
[JsonSerializable(typeof(SecurityMasterWorkstationDto))]
[JsonSerializable(typeof(SecurityMasterWorkstationDto[]))]
[JsonSerializable(typeof(List<SecurityMasterWorkstationDto>))]
[JsonSerializable(typeof(SecurityMasterIngestStatusResponse))]
[JsonSerializable(typeof(SecurityMasterActiveImportStatusResponse))]
[JsonSerializable(typeof(SecurityMasterCompletedImportStatusResponse))]
[JsonSerializable(typeof(EdgarIngestRequest))]
[JsonSerializable(typeof(EdgarIngestResult))]
[JsonSerializable(typeof(EdgarFilerRecord))]
[JsonSerializable(typeof(EdgarFilerRecord[]))]
[JsonSerializable(typeof(List<EdgarFilerRecord>))]
[JsonSerializable(typeof(EdgarAddress))]
[JsonSerializable(typeof(EdgarFormerName))]
[JsonSerializable(typeof(EdgarTickerAssociation))]
[JsonSerializable(typeof(EdgarTickerAssociation[]))]
[JsonSerializable(typeof(List<EdgarTickerAssociation>))]
[JsonSerializable(typeof(EdgarFilingSummary))]
[JsonSerializable(typeof(EdgarSecurityDataRecord))]
[JsonSerializable(typeof(EdgarDebtOfferingTerms))]
[JsonSerializable(typeof(EdgarDebtOfferingTerms[]))]
[JsonSerializable(typeof(List<EdgarDebtOfferingTerms>))]
[JsonSerializable(typeof(EdgarFundHolding))]
[JsonSerializable(typeof(EdgarFundHolding[]))]
[JsonSerializable(typeof(List<EdgarFundHolding>))]
[JsonSerializable(typeof(EdgarXbrlFact))]
[JsonSerializable(typeof(EdgarXbrlFact[]))]
[JsonSerializable(typeof(List<EdgarXbrlFact>))]
[JsonSerializable(typeof(IssuerFactSnapshot))]
[JsonSerializable(typeof(EdgarFactsRecord))]
[JsonSerializable(typeof(EdgarReferenceDataManifest))]
public partial class SecurityMasterJsonContext : JsonSerializerContext
{
    public static readonly JsonSerializerOptions HighPerformanceOptions = new()
    {
        TypeInfoResolver = Default,
        WriteIndented = false,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        PropertyNameCaseInsensitive = true
    };
}
