"""Render deterministic schema-control manifests, documentation, and Mermaid sources."""

from __future__ import annotations

import re
from collections import Counter
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from .common import fingerprint, write_json_if_changed, write_text_if_changed


GENERATED_NOTICE = (
    "<!-- Generated by build/scripts/schema-control.py. Do not edit directly. -->"
)
CONTRACT_DIAGRAM_PAGE_SIZE = 80
_SAFE_ID = re.compile(r"[^A-Za-z0-9_]")


def _safe_id(value: str) -> str:
    candidate = _SAFE_ID.sub("_", value)
    if not candidate or candidate[0].isdigit():
        candidate = f"n_{candidate}"
    return candidate


def _mermaid_type(value: str) -> str:
    generic = value.replace("<", "~").replace(">", "~")
    candidate = re.sub(r"[^A-Za-z0-9_~?\[\]]", "_", generic)
    return candidate or "unknown"


def _schema_items(catalog: Mapping[str, Any]) -> list[Mapping[str, Any]]:
    value = catalog.get("schemas", [])
    if isinstance(value, Mapping):
        return [
            {"name": key, **(item if isinstance(item, Mapping) else {})}
            for key, item in value.items()
        ]
    return [item for item in value if isinstance(item, Mapping)]


def _relations(schema: Mapping[str, Any]) -> list[Mapping[str, Any]]:
    if isinstance(schema.get("relations"), list):
        return [item for item in schema["relations"] if isinstance(item, Mapping)]
    result: list[Mapping[str, Any]] = []
    for category in (
        "tables",
        "views",
        "materialized_views",
        "sequences",
        "foreign_tables",
    ):
        values = schema.get(category, [])
        if isinstance(values, list):
            for item in values:
                if isinstance(item, Mapping):
                    result.append({"kind": category.removesuffix("s"), **item})
    return result


def _constraints(relation: Mapping[str, Any]) -> list[Mapping[str, Any]]:
    return [
        item
        for item in relation.get("constraints", []) or []
        if isinstance(item, Mapping)
    ]


def _constraint_type(item: Mapping[str, Any]) -> str:
    return str(item.get("type") or item.get("kind") or "").lower().replace("-", "_")


def _primary_key(relation: Mapping[str, Any]) -> list[str]:
    for constraint in _constraints(relation):
        if _constraint_type(constraint) in {"p", "primary", "primary_key"}:
            return [str(item) for item in constraint.get("columns", []) or []]
    value = relation.get("primary_key", [])
    return [str(item) for item in value] if isinstance(value, list) else []


def _foreign_keys(relation: Mapping[str, Any]) -> list[Mapping[str, Any]]:
    return [
        item
        for item in _constraints(relation)
        if _constraint_type(item) in {"f", "foreign", "foreign_key"}
    ]


def _type_items(contracts: Mapping[str, Any]) -> list[Mapping[str, Any]]:
    for key in ("types", "objects", "contracts"):
        value = contracts.get(key)
        if isinstance(value, list):
            return [item for item in value if isinstance(item, Mapping)]
        if isinstance(value, Mapping):
            return [
                {"full_name": name, **(item if isinstance(item, Mapping) else {})}
                for name, item in value.items()
            ]
    return []


def _contract_set_ids(item: Mapping[str, Any]) -> set[str]:
    raw = item.get("contract_sets") or item.get("sets") or item.get("modules") or []
    if isinstance(raw, str):
        return {raw}
    return {str(value) for value in raw}


def render_schema_mermaid(schema: Mapping[str, Any]) -> str:
    schema_name = str(schema.get("name") or schema.get("schema") or "schema")
    relations = sorted(_relations(schema), key=lambda item: str(item.get("name") or ""))
    lines = ["erDiagram"]
    edges: set[str] = set()
    for relation in relations:
        table_name = str(relation.get("name") or "")
        if not table_name:
            continue
        table_id = _safe_id(f"{schema_name}_{table_name}")
        columns = relation.get("columns", []) or []
        if columns:
            lines.append(f"    {table_id} {{")
            primary = set(_primary_key(relation))
            foreign = {
                str(column)
                for fk in _foreign_keys(relation)
                for column in fk.get("columns", []) or []
            }
            for column in columns:
                if not isinstance(column, Mapping):
                    continue
                name = str(column.get("name") or "column")
                data_type = _mermaid_type(
                    str(column.get("data_type") or column.get("type") or "unknown")
                )
                markers = []
                if name in primary:
                    markers.append("PK")
                if name in foreign:
                    markers.append("FK")
                suffix = f" {','.join(markers)}" if markers else ""
                lines.append(f"        {data_type} {_safe_id(name)}{suffix}")
            lines.append("    }")
        else:
            lines.append(f"    {table_id} {{")
            lines.append("        text catalogued_object")
            lines.append("    }")
        for fk in _foreign_keys(relation):
            target_schema = str(
                fk.get("referenced_schema") or fk.get("target_schema") or schema_name
            )
            target_table = str(
                fk.get("referenced_table")
                or fk.get("target_table")
                or fk.get("referenced_relation")
                or ""
            )
            if not target_table:
                continue
            target_id = _safe_id(f"{target_schema}_{target_table}")
            label = str(
                fk.get("name")
                or ", ".join(str(item) for item in fk.get("columns", []) or [])
            )
            edges.add(
                f'    {target_id} ||--o{{ {table_id} : "{label.replace(chr(34), chr(39))}"'
            )
    lines.extend(sorted(edges))
    return "\n".join(lines) + "\n"


def render_contract_mermaid(
    contract_set: Mapping[str, Any],
    types: list[Mapping[str, Any]],
    max_nodes: int | None = None,
) -> str:
    set_id = str(contract_set.get("id") or "contracts")
    selected = sorted(
        types, key=lambda item: str(item.get("full_name") or item.get("name") or "")
    )
    if max_nodes is not None:
        selected = selected[:max_nodes]
    names = {
        str(item.get("full_name") or item.get("name") or "")
        for item in selected
        if item.get("full_name") or item.get("name")
    }
    lines = [
        "classDiagram",
        f"    %% {set_id}: module mapping, not DTO/table equivalence",
    ]
    aliases: dict[str, str] = {}
    for item in selected:
        full_name = str(item.get("full_name") or item.get("name") or "")
        if not full_name:
            continue
        alias = _safe_id(full_name)
        aliases[full_name] = alias
        short_name = full_name.rsplit(".", 1)[-1]
        lines.append(f'    class {alias}["{short_name}"] {{')
        members = (
            item.get("members")
            or item.get("properties")
            or item.get("parameters")
            or []
        )
        for member in list(members)[:12]:
            if not isinstance(member, Mapping):
                continue
            member_name = _safe_id(str(member.get("name") or "member"))
            member_type = _mermaid_type(
                str(member.get("type") or member.get("type_name") or "object")
            )
            lines.append(f"        +{member_type} {member_name}")
        lines.append("    }")
    edges: set[str] = set()
    for item in selected:
        source = str(item.get("full_name") or item.get("name") or "")
        for raw_reference in item.get("references", []) or []:
            target = str(
                raw_reference.get("type")
                if isinstance(raw_reference, Mapping)
                else raw_reference
            )
            if (
                source in aliases
                and target in names
                and target in aliases
                and target != source
            ):
                edges.add(f"    {aliases[source]} --> {aliases[target]}")
    lines.extend(sorted(edges))
    return "\n".join(lines) + "\n"


def _schema_markdown(schema: Mapping[str, Any], diagram: str) -> str:
    schema_name = str(schema.get("name") or schema.get("schema") or "schema")
    relations = sorted(_relations(schema), key=lambda item: str(item.get("name") or ""))
    lines = [
        GENERATED_NOTICE,
        "",
        f"# `{schema_name}` schema",
        "",
        f"- Relations: {len(relations)}",
        f"- Functions/procedures: {len(schema.get('functions', []) or [])}",
        f"- Triggers: {len(schema.get('triggers', []) or [])}",
        f"- Row-level security policies: {len(schema.get('policies', []) or [])}",
        "",
        "The SQL migrations and the PostgreSQL catalog are authoritative. Object identifiers and hashes are normalized for review.",
        "",
        "```mermaid",
        diagram.rstrip(),
        "```",
        "",
        "| Relation | Kind | Columns | Primary key | Foreign keys | Indexes | Comment |",
        "| --- | --- | ---: | --- | ---: | ---: | --- |",
    ]
    for relation in relations:
        name = str(relation.get("name") or "")
        kind = str(relation.get("kind") or relation.get("relation_kind") or "table")
        pk = ", ".join(f"`{item}`" for item in _primary_key(relation)) or "-"
        comment = (
            str(relation.get("comment") or "-").replace("|", "\\|").replace("\n", " ")
        )
        lines.append(
            f"| `{name}` | {kind} | {len(relation.get('columns', []) or [])} | {pk} | "
            f"{len(_foreign_keys(relation))} | {len(relation.get('indexes', []) or [])} | {comment} |"
        )
    return "\n".join(lines) + "\n"


def _schema_catalog_markdown(
    catalog: Mapping[str, Any], config: Mapping[str, Any]
) -> str:
    schemas = sorted(
        _schema_items(catalog),
        key=lambda item: str(item.get("name") or item.get("schema") or ""),
    )
    migration_sets = [
        item
        for item in config.get("migration_sets", []) or []
        if isinstance(item, Mapping)
    ]
    by_schema: dict[str, list[Mapping[str, Any]]] = {}
    for item in migration_sets:
        by_schema.setdefault(str(item.get("schema") or ""), []).append(item)
    lines = [
        GENERATED_NOTICE,
        "",
        "# PostgreSQL schema catalog",
        "",
        "This catalog is extracted from a disposable PostgreSQL database after every registered migration is applied. It is not inferred from DTOs.",
        "",
        "| Physical schema | Logical migration modules | Relations | Functions | Triggers | Policies | Fingerprint |",
        "| --- | --- | ---: | ---: | ---: | ---: | --- |",
    ]
    for schema in schemas:
        name = str(schema.get("name") or schema.get("schema") or "")
        modules = (
            ", ".join(f"`{item.get('id')}`" for item in by_schema.get(name, [])) or "-"
        )
        schema_hash = str(schema.get("fingerprint") or fingerprint(schema))[:12]
        lines.append(
            f"| [`{name}`](modules/{name}.md) | {modules} | {len(_relations(schema))} | "
            f"{len(schema.get('functions', []) or [])} | {len(schema.get('triggers', []) or [])} | "
            f"{len(schema.get('policies', []) or [])} | `{schema_hash}` |"
        )
    lines.extend(
        [
            "",
            "## Default topology",
            "",
            "Direct Lending is a distinct migration module that is co-located in `security_master` by default. Module identity and physical schema identity are therefore both retained in the manifest.",
        ]
    )
    return "\n".join(lines) + "\n"


def _contract_catalog_markdown(
    contracts: Mapping[str, Any], config: Mapping[str, Any]
) -> str:
    types = _type_items(contracts)
    classifications = Counter(
        str(item.get("classification") or item.get("kind") or "unknown")
        for item in types
    )
    namespaces = Counter(str(item.get("namespace") or "(global)") for item in types)
    lines = [
        GENERATED_NOTICE,
        "",
        "# Meridian data-object catalog",
        "",
        "This is a source inventory of public DTOs and related contract objects. Database-to-contract links are explicit module associations; they do not assert one-to-one structural equivalence.",
        "",
        f"- Public contract objects: {len(types)}",
        f"- Namespaces: {len(namespaces)}",
        "",
        "## Classifications",
        "",
        "| Classification | Count |",
        "| --- | ---: |",
    ]
    for name, count in sorted(classifications.items()):
        lines.append(f"| `{name}` | {count} |")
    lines.extend(["", "## Database-adjacent diagrams", ""])
    for contract_set in config.get("contract_sets", []) or []:
        if not isinstance(contract_set, Mapping) or not contract_set.get("diagram"):
            continue
        set_id = str(contract_set.get("id") or "")
        mapped = [item for item in types if set_id in _contract_set_ids(item)]
        schemas = (
            ", ".join(f"`{item}`" for item in contract_set.get("schemas", []) or [])
            or "none"
        )
        lines.append(
            f"- [`{set_id}`](contracts/{set_id}.md): {len(mapped)} objects; mapped schemas: {schemas}."
        )
    return "\n".join(lines) + "\n"


def render_snapshot(
    output_root: Path,
    *,
    catalog: Mapping[str, Any],
    migrations: Mapping[str, Any],
    contracts: Mapping[str, Any],
    dependencies: Mapping[str, Any],
    policy_report: Mapping[str, Any],
    config: Mapping[str, Any],
) -> dict[str, Any]:
    """Write a complete candidate snapshot below ``output_root``."""

    manifest_root = output_root / "manifest"
    docs_root = output_root / "docs"
    reports_root = output_root / "reports"
    diagrams_root = docs_root / "diagrams"
    changed: list[str] = []

    def write_json(path: Path, value: Any) -> None:
        if write_json_if_changed(path, value):
            changed.append(path.relative_to(output_root).as_posix())

    def write_text(path: Path, value: str) -> None:
        if write_text_if_changed(path, value):
            changed.append(path.relative_to(output_root).as_posix())

    write_json(manifest_root / "catalog.json", catalog)
    write_json(manifest_root / "migrations.json", migrations)
    write_json(manifest_root / "contracts.json", contracts)
    write_json(manifest_root / "dependencies.json", dependencies)
    write_json(manifest_root / "policies.json", policy_report)

    schemas = sorted(
        _schema_items(catalog),
        key=lambda item: str(item.get("name") or item.get("schema") or ""),
    )
    for schema in schemas:
        schema_name = str(schema.get("name") or schema.get("schema") or "schema")
        write_json(manifest_root / "schemas" / f"{schema_name}.json", schema)
        diagram = render_schema_mermaid(schema)
        diagram_path = diagrams_root / f"{schema_name}.mmd"
        write_text(diagram_path, diagram)
        module_markdown = _schema_markdown(schema, diagram)
        write_text(docs_root / "modules" / f"{schema_name}.md", module_markdown)

    contract_types = _type_items(contracts)
    for contract_set in config.get("contract_sets", []) or []:
        if not isinstance(contract_set, Mapping) or not contract_set.get("diagram"):
            continue
        set_id = str(contract_set.get("id") or "contracts")
        selected = sorted(
            (item for item in contract_types if set_id in _contract_set_ids(item)),
            key=lambda item: str(item.get("full_name") or item.get("name") or ""),
        )
        pages = [
            selected[index : index + CONTRACT_DIAGRAM_PAGE_SIZE]
            for index in range(0, len(selected), CONTRACT_DIAGRAM_PAGE_SIZE)
        ] or [[]]
        common_lines = [
            GENERATED_NOTICE,
            "",
            f"# `{set_id}` data objects",
            "",
            "This is an explicit module association, not a claim that a DTO is identical to a table.",
            "",
            f"Mapped physical schemas: {', '.join(f'`{item}`' for item in contract_set.get('schemas', []) or []) or 'none'}.",
            f"Catalogued objects: {len(selected)}.",
        ]
        if len(pages) == 1:
            diagram = render_contract_mermaid(contract_set, pages[0])
            write_text(diagrams_root / f"contracts-{set_id}.mmd", diagram)
            markdown = "\n".join(
                [*common_lines, "", "```mermaid", diagram.rstrip(), "```", ""]
            )
        else:
            page_links: list[str] = []
            for page_index, page in enumerate(pages, start=1):
                page_slug = f"{set_id}-page-{page_index:02d}"
                diagram = render_contract_mermaid(contract_set, page)
                write_text(diagrams_root / f"contracts-{page_slug}.mmd", diagram)
                start = (page_index - 1) * CONTRACT_DIAGRAM_PAGE_SIZE + 1
                end = start + len(page) - 1
                page_markdown = "\n".join(
                    [
                        GENERATED_NOTICE,
                        "",
                        f"# `{set_id}` data objects - page {page_index} of {len(pages)}",
                        "",
                        f"Objects {start}-{end} of {len(selected)}. References crossing pages remain available in the dependency manifest.",
                        "",
                        "```mermaid",
                        diagram.rstrip(),
                        "```",
                        "",
                    ]
                )
                write_text(docs_root / "contracts" / f"{page_slug}.md", page_markdown)
                page_links.append(
                    f"- [Page {page_index}: objects {start}-{end}]({page_slug}.md)"
                )
            markdown = "\n".join(
                [
                    *common_lines,
                    "",
                    f"The catalog is split into {len(pages)} reviewable diagrams; no objects are omitted.",
                    "",
                    *page_links,
                    "",
                ]
            )
        write_text(docs_root / "contracts" / f"{set_id}.md", markdown)

    write_text(
        docs_root / "schema-catalog.md", _schema_catalog_markdown(catalog, config)
    )
    write_text(
        docs_root / "data-object-catalog.md",
        _contract_catalog_markdown(contracts, config),
    )
    index = "\n".join(
        [
            GENERATED_NOTICE,
            "",
            "# Generated database documentation",
            "",
            "- [PostgreSQL schema catalog](schema-catalog.md)",
            "- [DTO and data-object catalog](data-object-catalog.md)",
            "- [Dependency manifest](../../../database/manifest/dependencies.json)",
            "- [Schema-control workflow](../../engineering/README.md#postgresql-schema-control)",
            "",
        ]
    )
    write_text(docs_root / "README.md", index)
    write_json(reports_root / "policy-report.json", policy_report)

    artifact_index = {
        "format": "meridian.schema-artifacts.v1",
        "artifacts": sorted(
            path.relative_to(output_root).as_posix()
            for path in output_root.rglob("*")
            if path.is_file() and path.name != "render-manifest.json"
        ),
    }
    artifact_index["fingerprint"] = fingerprint(artifact_index)
    write_json(output_root / "render-manifest.json", artifact_index)
    return {
        "changed": sorted(changed),
        "artifact_count": len(artifact_index["artifacts"]),
    }
