### YamlMime:ManagedReference
items:
- uid: Meridian.Application.Credentials
  commentId: N:Meridian.Application.Credentials
  id: Meridian.Application.Credentials
  children:
  - Meridian.Application.Credentials.CredentialMetadata
  - Meridian.Application.Credentials.CredentialResult
  - Meridian.Application.Credentials.CredentialSource
  - Meridian.Application.Credentials.CredentialStoreExtensions
  - Meridian.Application.Credentials.CredentialType
  - Meridian.Application.Credentials.CredentialValidationResult
  - Meridian.Application.Credentials.ICredentialStore
  langs:
  - csharp
  - vb
  name: Meridian.Application.Credentials
  nameWithType: Meridian.Application.Credentials
  fullName: Meridian.Application.Credentials
  type: Namespace
  assemblies:
  - Meridian.Application
references:
- uid: Meridian.Application.Credentials.CredentialType
  commentId: T:Meridian.Application.Credentials.CredentialType
  parent: Meridian.Application.Credentials
  href: Meridian.Application.Credentials.CredentialType.html
  name: CredentialType
  nameWithType: CredentialType
  fullName: Meridian.Application.Credentials.CredentialType
- uid: Meridian.Application.Credentials.CredentialMetadata
  commentId: T:Meridian.Application.Credentials.CredentialMetadata
  parent: Meridian.Application.Credentials
  href: Meridian.Application.Credentials.CredentialMetadata.html
  name: CredentialMetadata
  nameWithType: CredentialMetadata
  fullName: Meridian.Application.Credentials.CredentialMetadata
- uid: Meridian.Application.Credentials.CredentialResult
  commentId: T:Meridian.Application.Credentials.CredentialResult
  parent: Meridian.Application.Credentials
  href: Meridian.Application.Credentials.CredentialResult.html
  name: CredentialResult
  nameWithType: CredentialResult
  fullName: Meridian.Application.Credentials.CredentialResult
- uid: Meridian.Application.Credentials.CredentialSource
  commentId: T:Meridian.Application.Credentials.CredentialSource
  parent: Meridian.Application.Credentials
  href: Meridian.Application.Credentials.CredentialSource.html
  name: CredentialSource
  nameWithType: CredentialSource
  fullName: Meridian.Application.Credentials.CredentialSource
- uid: Meridian.Application.Credentials.ICredentialStore
  commentId: T:Meridian.Application.Credentials.ICredentialStore
  parent: Meridian.Application.Credentials
  href: Meridian.Application.Credentials.ICredentialStore.html
  name: ICredentialStore
  nameWithType: ICredentialStore
  fullName: Meridian.Application.Credentials.ICredentialStore
- uid: Meridian.Application.Credentials.CredentialValidationResult
  commentId: T:Meridian.Application.Credentials.CredentialValidationResult
  href: Meridian.Application.Credentials.CredentialValidationResult.html
  name: CredentialValidationResult
  nameWithType: CredentialValidationResult
  fullName: Meridian.Application.Credentials.CredentialValidationResult
- uid: Meridian.Application.Credentials.CredentialStoreExtensions
  commentId: T:Meridian.Application.Credentials.CredentialStoreExtensions
  parent: Meridian.Application.Credentials
  href: Meridian.Application.Credentials.CredentialStoreExtensions.html
  name: CredentialStoreExtensions
  nameWithType: CredentialStoreExtensions
  fullName: Meridian.Application.Credentials.CredentialStoreExtensions
- uid: Meridian.Application.Credentials
  commentId: N:Meridian.Application.Credentials
  href: Meridian.html
  name: Meridian.Application.Credentials
  nameWithType: Meridian.Application.Credentials
  fullName: Meridian.Application.Credentials
  spec.csharp:
  - uid: Meridian
    name: Meridian
    href: Meridian.html
  - name: .
  - uid: Meridian.Application
    name: Application
    href: Meridian.Application.html
  - name: .
  - uid: Meridian.Application.Credentials
    name: Credentials
    href: Meridian.Application.Credentials.html
  spec.vb:
  - uid: Meridian
    name: Meridian
    href: Meridian.html
  - name: .
  - uid: Meridian.Application
    name: Application
    href: Meridian.Application.html
  - name: .
  - uid: Meridian.Application.Credentials
    name: Credentials
    href: Meridian.Application.Credentials.html
