using Meridian.Contracts.Ledger;

namespace Meridian.Ledger;

/// <summary>Cash-flow activity classification for a period cash movement.</summary>
public enum LedgerCashFlowCategory
{
    /// <summary>Cash generated by the entity's ongoing revenue/expense operations.</summary>
    Operating,

    /// <summary>Cash from acquiring or disposing of non-cash assets (securities, fixed assets).</summary>
    Investing,

    /// <summary>Cash from capital contributions, distributions, and borrowings.</summary>
    Financing,
}

/// <summary>One classified cash-flow line, aggregated by category and counterparty account.</summary>
public sealed record LedgerCashFlowLine(
    LedgerCashFlowCategory Category,
    string Description,
    LedgerAccountType CounterpartyType,
    decimal Amount);

/// <summary>
/// Direct-method statement of cash flows derived from the period's journal activity: each entry
/// touching a cash account attributes its net cash movement to operating, investing, or financing
/// activity by the account type of its counterpart legs. Reconciles beginning cash to ending cash.
/// </summary>
public sealed record LedgerCashFlowStatement(
    DateTimeOffset PeriodStart,
    DateTimeOffset AsOf,
    decimal BeginningCash,
    decimal EndingCash,
    decimal OperatingCashFlow,
    decimal InvestingCashFlow,
    decimal FinancingCashFlow,
    IReadOnlyList<LedgerCashFlowLine> Lines)
{
    /// <summary>Sum of operating, investing, and financing cash flows.</summary>
    public decimal NetCashFlow => OperatingCashFlow + InvestingCashFlow + FinancingCashFlow;

    /// <summary>Difference between the roll-forward and the observed ending cash. Zero when reconciled.</summary>
    public decimal ReconciliationVariance => BeginningCash + NetCashFlow - EndingCash;

    /// <summary>True when the statement ties beginning cash plus net flow to ending cash.</summary>
    public bool IsReconciled => Math.Abs(ReconciliationVariance) <= LedgerToleranceConstants.Balance;
}
