using FluentAssertions;
using Meridian.Contracts.Workstation;
using Meridian.Reporting;

namespace Meridian.Tests.Reporting;

public sealed class ReportWriterGridEngineTests
{
    [Fact]
    public void RenderGrids_BuildsPivotTopNContributionAndFormulaOutputs()
    {
        var rows = new[]
        {
            Row(("security", "AAPL"), ("sector", "Technology"), ("strategy", "Core"), ("marketValue", "100"), ("pnl", "15")),
            Row(("security", "MSFT"), ("sector", "Technology"), ("strategy", "Core"), ("marketValue", "200"), ("pnl", "5")),
            Row(("security", "TLT"), ("sector", "Rates"), ("strategy", "Hedge"), ("marketValue", "50"), ("pnl", "-3")),
            Row(("security", "GLD"), ("sector", "Commodities"), ("strategy", "Hedge"), ("marketValue", "50"), ("pnl", "2"))
        };
        var grids = new[]
        {
            new ReportWriterGridDefinitionDto(
                "sector-pivot",
                "Sector Pivot",
                ReportWriterGridKindDto.Pivot,
                RowFields: ["sector"],
                Metrics:
                [
                    new ReportWriterMetricDefinitionDto("marketValue", "marketValue"),
                    new ReportWriterMetricDefinitionDto("pnl", "pnl")
                ],
                Formulas:
                [
                    new ReportWriterFormulaDefinitionDto("returnPct", "{pnl} / {marketValue} * 100")
                ],
                SortBy: "marketValue"),
            new ReportWriterGridDefinitionDto(
                "top-winners",
                "Top Winners",
                ReportWriterGridKindDto.TopN,
                RowFields: ["security"],
                Metrics: [new ReportWriterMetricDefinitionDto("pnl", "pnl")],
                TopN: 2,
                SortBy: "pnl"),
            new ReportWriterGridDefinitionDto(
                "strategy-contribution",
                "Strategy Contribution",
                ReportWriterGridKindDto.Contribution,
                RowFields: ["strategy"],
                Metrics: [new ReportWriterMetricDefinitionDto("marketValue", "marketValue")])
        };

        var rendered = ReportWriterGridEngine.RenderGrids(grids, rows);

        rendered.Should().HaveCount(3);
        var pivot = rendered.Single(grid => grid.GridId == "sector-pivot");
        pivot.Columns.Select(column => column.Key).Should().ContainInOrder("sector", "marketValue", "pnl", "returnPct");
        pivot.Rows.Should().Contain(row =>
            row.Values["sector"] == "Technology" &&
            row.Values["marketValue"] == "300" &&
            row.Values["pnl"] == "20" &&
            row.Values["returnPct"] == "6.666667");
        pivot.Lineage.Should().NotBeNull();
        pivot.Lineage!.InputRowCount.Should().Be(4);
        pivot.Lineage.OutputRowCount.Should().Be(3);
        pivot.Lineage.SourceFields.Should().Equal("marketValue", "pnl", "sector");
        pivot.Lineage.Metrics.Should().Contain(metric =>
            metric.Name == "marketValue" &&
            metric.SourceField == "marketValue" &&
            metric.Function == ReportWriterAggregateFunctionDto.Sum.ToString());
        pivot.Lineage.Formulas.Should().Contain(formula =>
            formula.Name == "returnPct" &&
            formula.Expression == "{pnl} / {marketValue} * 100" &&
            formula.SourceFields.Count == 2 &&
            formula.SourceFields[0] == "marketValue" &&
            formula.SourceFields[1] == "pnl");
        pivot.DataDictionary.Should().NotBeNull();
        pivot.DataDictionary!.Should().Contain(field =>
            field.Key == "marketValue" &&
            field.SourceField == "marketValue" &&
            field.DataType == "decimal" &&
            !field.IsGenerated);
        pivot.DataDictionary.Should().Contain(field =>
            field.Key == "returnPct" &&
            field.Role == "formula" &&
            field.SourceField == "marketValue;pnl" &&
            field.IsGenerated &&
            field.Description.Contains("generated by the retained report-writer grid", StringComparison.OrdinalIgnoreCase));
        pivot.ValidationChecks.Should().NotBeNull();
        pivot.ValidationChecks!.Should().Contain(check =>
            check.CheckId == "column-dictionary" &&
            check.Status == "Passed");
        pivot.ValidationChecks.Should().Contain(check =>
            check.CheckId == "source-field-lineage" &&
            check.Status == "Passed");

        var top = rendered.Single(grid => grid.GridId == "top-winners");
        top.Rows.Select(row => row.Values["security"]).Should().Equal("AAPL", "MSFT");

        var contribution = rendered.Single(grid => grid.GridId == "strategy-contribution");
        contribution.Columns.Should().Contain(column => column.Key == "contributionPercent" && column.Role == "formula");
        contribution.Rows.Should().Contain(row =>
            row.Values["strategy"] == "Core" &&
            row.Values["marketValue"] == "300" &&
            row.Values["contributionPercent"] == "75");
    }

    [Fact]
    public void RenderGrids_PivotWithColumnFieldsBuildsCrosstabMetricColumns()
    {
        var rows = new[]
        {
            Row(("sector", "Technology"), ("region", "US"), ("marketValue", "100"), ("pnl", "10")),
            Row(("sector", "Technology"), ("region", "EU"), ("marketValue", "50"), ("pnl", "5")),
            Row(("sector", "Rates"), ("region", "US"), ("marketValue", "40"), ("pnl", "-2"))
        };
        var grids = new[]
        {
            new ReportWriterGridDefinitionDto(
                "sector-region-pivot",
                "Sector Region Pivot",
                ReportWriterGridKindDto.Pivot,
                RowFields: ["sector"],
                ColumnFields: ["region"],
                Metrics:
                [
                    new ReportWriterMetricDefinitionDto("marketValue", "marketValue"),
                    new ReportWriterMetricDefinitionDto("pnl", "pnl")
                ],
                Formulas:
                [
                    new ReportWriterFormulaDefinitionDto("returnPct", "{pnl} / {marketValue} * 100")
                ])
        };

        var rendered = ReportWriterGridEngine.RenderGrids(grids, rows).Single();

        rendered.Columns.Select(column => column.Key).Should().Equal(
            "sector",
            "US:marketValue",
            "US:pnl",
            "EU:marketValue",
            "EU:pnl",
            "returnPct");
        rendered.Rows.Should().HaveCount(2);
        rendered.Rows.Should().Contain(row =>
            row.Values["sector"] == "Technology" &&
            row.Values["US:marketValue"] == "100" &&
            row.Values["US:pnl"] == "10" &&
            row.Values["EU:marketValue"] == "50" &&
            row.Values["EU:pnl"] == "5" &&
            row.Values["returnPct"] == "10");
        rendered.Rows.Should().Contain(row =>
            row.Values["sector"] == "Rates" &&
            row.Values["US:marketValue"] == "40" &&
            row.Values["US:pnl"] == "-2" &&
            row.Values["EU:marketValue"] == "0" &&
            row.Values["EU:pnl"] == "0" &&
            row.Values["returnPct"] == "-5");
        rendered.Lineage.Should().NotBeNull();
        rendered.Lineage!.SourceFields.Should().Equal("marketValue", "pnl", "region", "sector");
    }

    [Fact]
    public void RenderGrids_ReportsFormulaAndNumericWarningsWithoutThrowing()
    {
        var rows = new[]
        {
            Row(("bucket", "Cash"), ("marketValue", "not-a-number"), ("pnl", "1")),
            Row(("bucket", "Equity"), ("marketValue", "0"), ("pnl", "2"))
        };
        var grids = new[]
        {
            new ReportWriterGridDefinitionDto(
                "bad-formula",
                "Bad Formula",
                ReportWriterGridKindDto.Pivot,
                RowFields: ["bucket"],
                Metrics:
                [
                    new ReportWriterMetricDefinitionDto("marketValue", "marketValue"),
                    new ReportWriterMetricDefinitionDto("pnl", "pnl")
                ],
                Formulas: [new ReportWriterFormulaDefinitionDto("returnPct", "{pnl} / {marketValue}")])
        };

        var rendered = ReportWriterGridEngine.RenderGrids(grids, rows).Single();

        rendered.Rows.Should().HaveCount(2);
        rendered.Lineage.Should().NotBeNull();
        rendered.Lineage!.InputRowCount.Should().Be(2);
        rendered.Lineage.OutputRowCount.Should().Be(2);
        rendered.Warnings.Should().Contain("Field 'marketValue' contained non-numeric values; affected cells were skipped.");
        rendered.Warnings.Should().Contain(warning => warning.StartsWith("Formula 'returnPct' could not be evaluated:", StringComparison.Ordinal));
        rendered.Rows.Should().Contain(row => row.Values["bucket"] == "Equity" && row.Values["returnPct"] == string.Empty);
    }

    [Fact]
    public void RenderGrids_FormulaLineageIncludesTotalAndBareIdentifierReferences()
    {
        var rows = new[]
        {
            Row(("sector", "Technology"), ("marketValue", "100"), ("pnl", "10")),
            Row(("sector", "Credit"), ("marketValue", "50"), ("pnl", "-5"))
        };
        var grids = new[]
        {
            new ReportWriterGridDefinitionDto(
                "formula-lineage",
                "Formula Lineage",
                ReportWriterGridKindDto.Pivot,
                RowFields: ["sector"],
                Metrics:
                [
                    new ReportWriterMetricDefinitionDto("marketValue", "marketValue"),
                    new ReportWriterMetricDefinitionDto("pnl", "pnl")
                ],
                Formulas:
                [
                    new ReportWriterFormulaDefinitionDto("weightPct", "{marketValue} / total(marketValue) * 100"),
                    new ReportWriterFormulaDefinitionDto("bareReturnPct", "pnl / marketValue * 100"),
                    new ReportWriterFormulaDefinitionDto("totalBraceCheck", "{pnl} / total({marketValue}) * 100")
                ])
        };

        var rendered = ReportWriterGridEngine.RenderGrids(grids, rows).Single();

        rendered.Warnings.Should().BeEmpty();
        rendered.Rows.Should().Contain(row =>
            row.Values["sector"] == "Technology" &&
            row.Values["weightPct"] == "66.666667" &&
            row.Values["bareReturnPct"] == "10" &&
            row.Values["totalBraceCheck"] == "6.666667");
        rendered.Lineage.Should().NotBeNull();
        rendered.Lineage!.Formulas.Should().Contain(formula =>
            formula.Name == "weightPct" &&
            formula.SourceFields.SequenceEqual(new[] { "marketValue" }));
        rendered.Lineage.Formulas.Should().Contain(formula =>
            formula.Name == "bareReturnPct" &&
            formula.SourceFields.SequenceEqual(new[] { "marketValue", "pnl" }));
        rendered.Lineage.Formulas.Should().Contain(formula =>
            formula.Name == "totalBraceCheck" &&
            formula.SourceFields.SequenceEqual(new[] { "marketValue", "pnl" }));
        rendered.Lineage.SourceFields.Should().Equal("marketValue", "pnl", "sector");
        rendered.DataDictionary.Should().NotBeNull();
        rendered.DataDictionary!.Should().Contain(field =>
            field.Key == "weightPct" &&
            field.IsGenerated &&
            field.SourceField == "marketValue");
        rendered.DataDictionary.Should().Contain(field =>
            field.Key == "totalBraceCheck" &&
            field.IsGenerated &&
            field.SourceField == "marketValue;pnl");
        rendered.ValidationChecks.Should().NotBeNull();
        rendered.ValidationChecks!.Should().OnlyContain(check => check.Status == "Passed");
    }

    [Fact]
    public void RenderGrids_CustomFormulaFunctionsEvaluateAndRetainSourceLineage()
    {
        var rows = new[]
        {
            Row(("strategy", "Core"), ("marketValue", "100"), ("pnl", "-12"), ("riskLimit", "10")),
            Row(("strategy", "Core"), ("marketValue", "0"), ("pnl", "4"), ("riskLimit", "7")),
            Row(("strategy", "Hedge"), ("marketValue", "50"), ("pnl", "5"), ("riskLimit", "9"))
        };
        var grids = new[]
        {
            new ReportWriterGridDefinitionDto(
                "formula-functions",
                "Formula Functions",
                ReportWriterGridKindDto.Pivot,
                RowFields: ["strategy"],
                Metrics:
                [
                    new ReportWriterMetricDefinitionDto("marketValue", "marketValue"),
                    new ReportWriterMetricDefinitionDto("pnl", "pnl"),
                    new ReportWriterMetricDefinitionDto("riskLimit", "riskLimit")
                ],
                Formulas:
                [
                    new ReportWriterFormulaDefinitionDto("absolutePnl", "abs({pnl})"),
                    new ReportWriterFormulaDefinitionDto("cappedRisk", "min(abs({pnl}), max({riskLimit}, 8))"),
                    new ReportWriterFormulaDefinitionDto("guardedReturn", "safeDivide({pnl}, {marketValue}, -999) * 100")
                ])
        };

        var rendered = ReportWriterGridEngine.RenderGrids(grids, rows).Single();

        rendered.Warnings.Should().BeEmpty();
        rendered.Rows.Should().Contain(row =>
            row.Values["strategy"] == "Core" &&
            row.Values["marketValue"] == "100" &&
            row.Values["pnl"] == "-8" &&
            row.Values["absolutePnl"] == "8" &&
            row.Values["cappedRisk"] == "8" &&
            row.Values["guardedReturn"] == "-8");
        rendered.Rows.Should().Contain(row =>
            row.Values["strategy"] == "Hedge" &&
            row.Values["marketValue"] == "50" &&
            row.Values["pnl"] == "5" &&
            row.Values["absolutePnl"] == "5" &&
            row.Values["cappedRisk"] == "5" &&
            row.Values["guardedReturn"] == "10");
        rendered.Lineage.Should().NotBeNull();
        rendered.Lineage!.Formulas.Should().Contain(formula =>
            formula.Name == "cappedRisk" &&
            formula.SourceFields.SequenceEqual(new[] { "pnl", "riskLimit" }));
        rendered.Lineage.Formulas.Should().Contain(formula =>
            formula.Name == "guardedReturn" &&
            formula.SourceFields.SequenceEqual(new[] { "marketValue", "pnl" }));
        rendered.Lineage.SourceFields.Should().Equal("marketValue", "pnl", "riskLimit", "strategy");
        rendered.DataDictionary.Should().Contain(field =>
            field.Key == "guardedReturn" &&
            field.Role == "formula" &&
            field.SourceField == "marketValue;pnl" &&
            field.IsGenerated);
        rendered.ValidationChecks.Should().NotBeNull();
        rendered.ValidationChecks!.Should().OnlyContain(check => check.Status == "Passed");
    }

    [Fact]
    public void RenderGrids_AppliesSavedFiltersAndReportsFilterLineage()
    {
        var rows = new[]
        {
            Row(("security", "AAPL"), ("sector", "Technology"), ("strategy", "Core"), ("marketValue", "100"), ("pnl", "15")),
            Row(("security", "MSFT"), ("sector", "Technology"), ("strategy", "Core"), ("marketValue", "200"), ("pnl", "5")),
            Row(("security", "TLT"), ("sector", "Rates"), ("strategy", "Hedge"), ("marketValue", "50"), ("pnl", "-3")),
            Row(("security", "GLD"), ("sector", "Commodities"), ("strategy", "Hedge"), ("marketValue", "50"), ("pnl", "2"))
        };
        var grids = new[]
        {
            new ReportWriterGridDefinitionDto(
                "core-sector-pivot",
                "Core Sector Pivot",
                ReportWriterGridKindDto.Pivot,
                RowFields: ["sector"],
                Metrics: [new ReportWriterMetricDefinitionDto("marketValue", "marketValue")],
                Filters:
                [
                    new ReportWriterFilterDefinitionDto(
                        "strategy",
                        ReportWriterFilterOperatorDto.Equals,
                        "Core",
                        "Core strategy only")
                ])
        };

        var rendered = ReportWriterGridEngine.RenderGrids(grids, rows).Single();

        rendered.Rows.Should().ContainSingle();
        rendered.Rows[0].Values["sector"].Should().Be("Technology");
        rendered.Rows[0].Values["marketValue"].Should().Be("300");
        rendered.Lineage.Should().NotBeNull();
        rendered.Lineage!.InputRowCount.Should().Be(4);
        rendered.Lineage.FilteredInputRowCount.Should().Be(2);
        rendered.Lineage.OutputRowCount.Should().Be(1);
        rendered.Lineage.SourceFields.Should().Equal("marketValue", "sector", "strategy");
        rendered.Lineage.Filters.Should().ContainSingle(filter =>
            filter.Field == "strategy" &&
            filter.Operator == ReportWriterFilterOperatorDto.Equals.ToString() &&
            filter.Value == "Core" &&
            filter.Label == "Core strategy only");
    }

    private static IReadOnlyDictionary<string, string> Row(params (string Key, string Value)[] values) =>
        values.ToDictionary(static value => value.Key, static value => value.Value, StringComparer.OrdinalIgnoreCase);
}
