// <auto-generated>
// Generated by build/scripts/generate-workspace-catalog-ts.py from src/Meridian.Contracts/Workstation/WorkstationWorkspaceCatalog.cs.
// </auto-generated>

export const WORKSPACE_DEFINITIONS = [
  {
    key: "trading",
    label: "Trading",
    description: "Paper cockpit readiness, sessions, orders, positions, replay, and promotion evidence.",
    status: "Review"
  },
  {
    key: "portfolio",
    label: "Portfolio",
    description: "Portfolio exposure, positions, attribution, fills, and run-level equity continuity.",
    status: "Preview"
  },
  {
    key: "accounting",
    label: "Accounting",
    description: "Ledger, cash-flow, reconciliation, Security Master coverage, and fund-account evidence.",
    status: "Review"
  },
  {
    key: "reporting",
    label: "Reporting",
    description: "Report packs, governed exports, loader scripts, data dictionaries, and approval posture.",
    status: "Review"
  },
  {
    key: "strategy",
    label: "Strategy",
    description: "Backtest runs, comparisons, run diffing, and paper-promotion review.",
    status: "Paper"
  },
  {
    key: "data",
    label: "Data",
    description: "Provider posture, backfill queues, symbol readiness, and data-quality handoffs.",
    status: "Live"
  },
  {
    key: "settings",
    label: "Settings",
    description: "Operator session context, shell preferences, integrations, and workstation setup checks.",
    status: "Setup"
  },
] as const;
