using FluentAssertions;
using Meridian.Ui.Shared.Endpoints;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.DependencyInjection;
using Xunit;

namespace Meridian.Tests.Integration.EndpointTests;

/// <summary>
/// The read-surface declaration ratchet (W9-GOV-008): every mapped GET route must either declare a
/// permission (<see cref="EndpointAuthorizationMetadata"/>) or declare that it is deliberately open
/// (<see cref="EndpointOpenReadMetadata"/>), or sit in the frozen baseline below.
/// <para>
/// The governed decision this enforces: the read surface is remediated <em>risk-based</em>, not
/// uniformly. Reads exposing account-scoped, position, or PII-bearing data get a permission; broad
/// workstation reads — reference data, catalogs, health — declare openness explicitly with a
/// stated reason rather than by omission. Neither state can be reached silently: a newly mapped
/// GET route carrying no declaration fails immediately, and the frozen inventory below only
/// shrinks as the burn-down classifies each family one way or the other.
/// </para>
/// </summary>
public sealed class EndpointReadDeclarationTests : EndpointIntegrationTestBase
{
    public EndpointReadDeclarationTests(EndpointTestFixture fixture)
        : base(fixture)
    {
    }

    /// <summary>
    /// Frozen 2026-08-16 read-surface inventory: GET routes mapped before the declaration
    /// requirement existed, pending risk classification. Tracked under W9-GOV-008 with the
    /// burn-down owned by the remainder-to-zero change. The ratchet only tightens: classify a
    /// route (permission or open-with-reason) and remove its entry.
    /// </summary>
    private static readonly HashSet<string> UndeclaredReadBaseline = new(StringComparer.OrdinalIgnoreCase)
    {
        "GET /api/accounting-system/export-packages",
        "GET /api/accounting-system/export-packages/{exportPackageId}/manifest",
        "GET /api/accounting-system/import/latest",
        "GET /api/accounting-system/mapping-profiles",
        "GET /api/accounting-system/migration-run-artifacts",
        "GET /api/accounting-system/migration-worker-plans",
        "GET /api/accounting-system/production-certification-profile",
        "GET /api/accounting-system/providers",
        "GET /api/accounting-system/reconciliation/latest",
        "GET /api/accounting-system/tenant-administration-profile",
        "GET /api/admin/cleanup/preview",
        "GET /api/admin/error-codes",
        "GET /api/admin/maintenance/history",
        "GET /api/admin/maintenance/run/{runId}",
        "GET /api/admin/maintenance/schedule",
        "GET /api/admin/quick-check",
        "GET /api/admin/retention",
        "GET /api/admin/retention/compliance-report",
        "GET /api/admin/show-config",
        "GET /api/admin/storage/permissions",
        "GET /api/admin/storage/tiers",
        "GET /api/admin/storage/usage",
        "GET /api/analytics/anomalies",
        "GET /api/analytics/compare",
        "GET /api/analytics/completeness",
        "GET /api/analytics/gaps",
        "GET /api/analytics/latency",
        "GET /api/analytics/latency/stats",
        "GET /api/analytics/quality-report",
        "GET /api/analytics/rate-limits",
        "GET /api/analytics/throughput",
        "GET /api/auth/access-assignments",
        "GET /api/auth/accounts",
        "GET /api/auth/audit",
        "GET /api/auth/desktop-launch/{ticket}",
        "GET /api/auth/me",
        "GET /api/auth/roles",
        "GET /api/backfill/checkpoints",
        "GET /api/backfill/checkpoints/resumable",
        "GET /api/backfill/checkpoints/validation",
        "GET /api/backfill/checkpoints/{jobId}",
        "GET /api/backfill/checkpoints/{jobId}/pending",
        "GET /api/backfill/completeness",
        "GET /api/backfill/gaps",
        "GET /api/backfill/validation",
        "GET /api/backfill/validation/{symbol}",
        "GET /api/backpressure",
        "GET /api/brokerage-connections/alpaca/status",
        "GET /api/brokerage-connections/robinhood/callback",
        "GET /api/brokerage-connections/robinhood/status",
        "GET /api/calendar/holidays",
        "GET /api/calendar/status",
        "GET /api/calendar/trading-days",
        "GET /api/canonicalization/config",
        "GET /api/canonicalization/parity",
        "GET /api/canonicalization/parity/{provider}",
        "GET /api/canonicalization/status",
        "GET /api/catalog/coverage",
        "GET /api/catalog/search",
        "GET /api/catalog/symbols",
        "GET /api/catalog/timeline",
        "GET /api/compliance/access-reviews",
        "GET /api/compliance/audit/extract",
        "GET /api/compliance/controls/attestation",
        "GET /api/config/data-sources",
        "GET /api/config/datasources",
        "GET /api/connections",
        "GET /api/credentials",
        "GET /api/credentials/{provider}",
        "GET /api/data/bbo/{symbol}",
        "GET /api/data/health",
        "GET /api/data/l3-orderbook/{symbol}",
        "GET /api/data/orderbook/{symbol}",
        "GET /api/data/orderflow/{symbol}",
        "GET /api/data/quotes-snapshot",
        "GET /api/data/quotes/{symbol}",
        "GET /api/data/trades/{symbol}",
        "GET /api/demo/historical/{symbol}",
        "GET /api/demo/market-data/{symbol}",
        "GET /api/demo/mode",
        "GET /api/demo/symbols",
        "GET /api/diagnostics/bundle",
        "GET /api/diagnostics/config",
        "GET /api/diagnostics/coordination",
        "GET /api/diagnostics/error-codes",
        "GET /api/diagnostics/metrics",
        "GET /api/diagnostics/providers",
        "GET /api/diagnostics/quick-check",
        "GET /api/diagnostics/show-config",
        "GET /api/diagnostics/storage",
        "GET /api/environment-designer/drafts",
        "GET /api/environment-designer/drafts/{draftId:guid}",
        "GET /api/environment-designer/runtime/current",
        "GET /api/environment-designer/runtime/versions/{versionId:guid}",
        "GET /api/environment-designer/versions",
        "GET /api/environment-designer/versions/current",
        "GET /api/environment-designer/versions/{versionId:guid}",
        "GET /api/errors",
        "GET /api/events/stream",
        "GET /api/export/formats",
        "GET /api/export/preview",
        "GET /api/fund-structure/accounting-view",
        "GET /api/fund-structure/businesses/{businessId:guid}/advisory-view",
        "GET /api/fund-structure/businesses/{businessId:guid}/fund-view",
        "GET /api/fund-structure/cash-flow-view",
        "GET /api/fund-structure/graph",
        "GET /api/fund-structure/ledger-mapping-view",
        "GET /api/fund-structure/legacy-graph",
        "GET /api/fund-structure/report-packs",
        "GET /api/fund-structure/report-packs/{reportId:guid}",
        "GET /api/fund-structure/report-packs/{reportId:guid}/evidence-bundle",
        "GET /api/fund-structure/report-packs/{reportId:guid}/ledger-provenance",
        "GET /api/fund-structure/reporting/packs/history",
        "GET /api/fund-structure/reporting/packs/{reportId:guid}/deliveries",
        "GET /api/fund-structure/reporting/packs/{reportId:guid}/deliveries/{attemptId:guid}/artifacts/{artifactName}",
        "GET /api/fund-structure/reporting/packs/{reportId:guid}/deliveries/{attemptId:guid}/package",
        "GET /api/fund-structure/reporting/runs",
        "GET /api/fund-structure/reporting/runs/{runId}/audit",
        "GET /api/fund-structure/reporting/runs/{runId}/report-writer-grids/{gridId}",
        "GET /api/fund-structure/reporting/runs/{runId}/stream",
        "GET /api/fund-structure/reporting/schedules",
        "GET /api/fund-structure/reporting/starter-kits",
        "GET /api/fund-structure/reporting/structured-exports/{exportId}",
        "GET /api/fund-structure/reporting/templates",
        "GET /api/fund-structure/workspace-view",
        "GET /api/health",
        "GET /api/health/detailed",
        "GET /api/health/diagnostics/bundle",
        "GET /api/health/events",
        "GET /api/health/metrics",
        "GET /api/health/providers",
        "GET /api/health/providers/{provider}/diagnostics",
        "GET /api/health/storage",
        "GET /api/health/summary",
        "GET /api/historical/",
        "GET /api/historical/symbols",
        "GET /api/historical/{symbol}/bars",
        "GET /api/historical/{symbol}/daterange",
        "GET /api/indices/{indexName}/constituents",
        "GET /api/lean/algorithms",
        "GET /api/lean/auto-export",
        "GET /api/lean/backtest/history",
        "GET /api/lean/backtest/{backtestId}/results",
        "GET /api/lean/backtest/{backtestId}/status",
        "GET /api/lean/config",
        "GET /api/lean/status",
        "GET /api/lean/symbol-map",
        "GET /api/lean/sync/status",
        "GET /api/ledger/accounting-configuration",
        "GET /api/ledger/accounting-configuration/audit",
        "GET /api/ledger/journal-automation/daily-mark-to-market-schedules",
        "GET /api/ledger/journal-automation/monthly-schedules",
        "GET /api/maintenance/executions",
        "GET /api/maintenance/executions/failed",
        "GET /api/maintenance/executions/{executionId}",
        "GET /api/maintenance/presets",
        "GET /api/maintenance/schedules",
        "GET /api/maintenance/schedules/summary",
        "GET /api/maintenance/schedules/{id}",
        "GET /api/maintenance/schedules/{id}/history",
        "GET /api/maintenance/schedules/{scheduleId}/executions",
        "GET /api/maintenance/schedules/{scheduleId}/summary",
        "GET /api/maintenance/statistics",
        "GET /api/maintenance/status",
        "GET /api/maintenance/task-types",
        "GET /api/messaging/activity",
        "GET /api/messaging/config",
        "GET /api/messaging/consumers",
        "GET /api/messaging/endpoints",
        "GET /api/messaging/errors",
        "GET /api/messaging/publishing",
        "GET /api/messaging/stats",
        "GET /api/messaging/status",
        "GET /api/oms/adapters/diagnostics",
        "GET /api/oms/audit",
        "GET /api/oms/messages",
        "GET /api/options/chains/{underlyingSymbol}",
        "GET /api/options/expirations/{underlyingSymbol}",
        "GET /api/options/quotes/{underlyingSymbol}",
        "GET /api/options/strikes/{underlyingSymbol}/{expiration}",
        "GET /api/options/summary",
        "GET /api/options/underlyings",
        "GET /api/packaging/contents",
        "GET /api/packaging/download/{fileName}",
        "GET /api/packaging/list",
        "GET /api/plaid/accounts",
        "GET /api/plaid/institutions/search",
        "GET /api/plaid/items",
        "GET /api/portfolio/cash-ladder/",
        "GET /api/portfolio/cash-ladder/scenarios",
        "GET /api/portfolio/{runId}/cash-flows",
        "GET /api/promotion/evaluate/{runId}",
        "GET /api/promotion/history",
        "GET /api/provider-routing/bindings",
        "GET /api/provider-routing/connections",
        "GET /api/provider-routing/trust-snapshots",
        "GET /api/providers/capabilities",
        "GET /api/providers/capability-matrix",
        "GET /api/providers/catalog",
        "GET /api/providers/catalog/{providerId}",
        "GET /api/providers/comparison",
        "GET /api/providers/connections",
        "GET /api/providers/dashboard",
        "GET /api/providers/failover",
        "GET /api/providers/failover-thresholds",
        "GET /api/providers/health",
        "GET /api/providers/ib/error-codes",
        "GET /api/providers/ib/limits",
        "GET /api/providers/ib/status",
        "GET /api/providers/latency",
        "GET /api/providers/metrics",
        "GET /api/providers/metrics/{providerId}",
        "GET /api/providers/modules",
        "GET /api/providers/modules/catalogue",
        "GET /api/providers/rate-limits",
        "GET /api/providers/readiness",
        "GET /api/providers/status",
        "GET /api/providers/{providerName}",
        "GET /api/providers/{providerName}/rate-limit-history",
        "GET /api/quant/templates",
        "GET /api/reference-data/certificates-of-deposit/by-issuer",
        "GET /api/reference-data/certificates-of-deposit/maturing-before",
        "GET /api/reference-data/certificates-of-deposit/{securityId:guid}",
        "GET /api/reference-data/commodities/by-exchange",
        "GET /api/reference-data/commodities/by-type",
        "GET /api/reference-data/commodities/{securityId:guid}",
        "GET /api/reference-data/edgar/facts/{cik}",
        "GET /api/reference-data/edgar/filers/{cik}",
        "GET /api/reference-data/edgar/security-data/{cik}",
        "GET /api/reference-data/equities/by-exchange",
        "GET /api/reference-data/equities/by-issuer",
        "GET /api/reference-data/equities/{securityId:guid}",
        "GET /api/reference-data/fxspot/by-currency",
        "GET /api/reference-data/fxspot/pairs/{pairCode}",
        "GET /api/reference-data/fxspot/{securityId:guid}",
        "GET /api/reference-data/money-market-funds/by-family",
        "GET /api/reference-data/money-market-funds/by-sweep-eligibility",
        "GET /api/reference-data/money-market-funds/{securityId:guid}",
        "GET /api/reference-data/options/chains/snapshot",
        "GET /api/reference-data/options/contracts/{contractSymbol}",
        "GET /api/reference-data/options/contracts/{contractSymbol}/underlying-linkage",
        "GET /api/reference-data/options/expiry-ladder",
        "GET /api/reference-data/options/series/{optionChainId}",
        "GET /api/reference-data/swaps/by-type",
        "GET /api/reference-data/swaps/maturing-before",
        "GET /api/reference-data/swaps/{securityId:guid}",
        "GET /api/replay/files",
        "GET /api/replay/preview",
        "GET /api/replay/stats",
        "GET /api/replay/{sessionId}/status",
        "GET /api/resilience/circuit-breakers",
        "GET /api/risk/escalations",
        "GET /api/risk/rules",
        "GET /api/risk/rules/{ruleName}/config",
        "GET /api/risk/rules/{ruleName}/status",
        "GET /api/sampling/estimate",
        "GET /api/sampling/saved",
        "GET /api/sampling/{sampleId}",
        "GET /api/sla/health",
        "GET /api/sla/metrics",
        "GET /api/sla/status",
        "GET /api/sla/status/{symbol}",
        "GET /api/sla/violations",
        "GET /api/status",
        "GET /api/strategies/status",
        "GET /api/strategies/{strategyId}/status",
        "GET /api/subscriptions/active",
        "GET /api/symbols",
        "GET /api/symbols/archived",
        "GET /api/symbols/monitored",
        "GET /api/symbols/search",
        "GET /api/symbols/statistics",
        "GET /api/symbols/{symbol}/depth",
        "GET /api/symbols/{symbol}/status",
        "GET /api/symbols/{symbol}/trades",
        "GET /api/v1/risk/escalations",
        "GET /api/v1/risk/rules",
        "GET /api/v1/risk/rules/{ruleName}/config",
        "GET /api/v1/risk/rules/{ruleName}/status",
        "GET /api/workstation/accounting",
        "GET /api/workstation/assets/{securityId:guid}/operations",
        "GET /api/workstation/collateral/exposure",
        "GET /api/workstation/data",
        "GET /api/workstation/data-operations",
        "GET /api/workstation/data/ingestion-operations",
        "GET /api/workstation/data/ingestion-operations/{jobId}",
        "GET /api/workstation/data/replacement-cost",
        "GET /api/workstation/data/storage-assurance",
        "GET /api/workstation/data/uploads/templates",
        "GET /api/workstation/data/uploads/templates/workbook",
        "GET /api/workstation/family-office/balance-sheet",
        "GET /api/workstation/family-office/entities",
        "GET /api/workstation/family-office/overview",
        "GET /api/workstation/family-office/ownership-graph",
        "GET /api/workstation/financial-record-explorers/{explorerId}",
        "GET /api/workstation/financial-record-explorers/{explorerId}/records/{recordId}",
        "GET /api/workstation/first-run/",
        "GET /api/workstation/governance",
        "GET /api/workstation/operations/continuity",
        "GET /api/workstation/operations/continuity/approval-policy-matrix",
        "GET /api/workstation/operations/continuity/close-calendar",
        "GET /api/workstation/operations/continuity/{workflowId:guid}",
        "GET /api/workstation/operations/continuity/{workflowId:guid}/breaks",
        "GET /api/workstation/operations/continuity/{workflowId:guid}/checklist",
        "GET /api/workstation/operations/continuity/{workflowId:guid}/close-readiness",
        "GET /api/workstation/operations/continuity/{workflowId:guid}/ledger-preview",
        "GET /api/workstation/operations/continuity/{workflowId:guid}/timeline",
        "GET /api/workstation/operations/private-capital-close-cockpit",
        "GET /api/workstation/operator/inbox",
        "GET /api/workstation/portfolio",
        "GET /api/workstation/portfolio/multi-asset-coverage",
        "GET /api/workstation/portfolio/summary",
        "GET /api/workstation/reconciliation/break-queue",
        "GET /api/workstation/reconciliation/break-queue/bulk/{bulkActionId}",
        "GET /api/workstation/reconciliation/break-queue/bulk/{bulkActionId}/result",
        "GET /api/workstation/reconciliation/break-queue/taxonomy",
        "GET /api/workstation/reconciliation/break-queue/{breakId}",
        "GET /api/workstation/reconciliation/break-queue/{breakId}/audit",
        "GET /api/workstation/reconciliation/break-queue/{breakId}/comments",
        "GET /api/workstation/reconciliation/break-queue/{breakId}/rebuilt-snapshot",
        "GET /api/workstation/reconciliation/calibration-summary",
        "GET /api/workstation/reconciliation/cases",
        "GET /api/workstation/reconciliation/margin-control",
        "GET /api/workstation/reconciliation/queue-status",
        "GET /api/workstation/reconciliation/runs/{reconciliationRunId}",
        "GET /api/workstation/reconciliation/statement-breaks",
        "GET /api/workstation/reconciliation/statement-connectors",
        "GET /api/workstation/reconciliation/statement-exceptions",
        "GET /api/workstation/reconciliation/statement-fetch-schedules",
        "GET /api/workstation/reconciliation/statement-mapping-profiles",
        "GET /api/workstation/reconciliation/statement-reconciliation-report/{workflowId}",
        "GET /api/workstation/reconciliation/statement-reconciliation-report/{workflowId}/artifacts/{artifactId}",
        "GET /api/workstation/reconciliation/statement-runs",
        "GET /api/workstation/reconciliation/statement-runs/{runId}",
        "GET /api/workstation/reconciliation/statement-runs/{runId}/breaks",
        "GET /api/workstation/reconciliation/statement-runs/{runId}/validation",
        "GET /api/workstation/reconciliation/statement-to-report/{workflowId}",
        "GET /api/workstation/reconciliation/statement-to-report/{workflowId}/artifacts/{artifactId}",
        "GET /api/workstation/research",
        "GET /api/workstation/research/briefing",
        "GET /api/workstation/runs/history",
        "GET /api/workstation/runs/lineage-timeline",
        "GET /api/workstation/runs/sweeps",
        "GET /api/workstation/runs/timeline",
        "GET /api/workstation/runs/{runId}/attribution",
        "GET /api/workstation/runs/{runId}/continuity",
        "GET /api/workstation/runs/{runId}/equity-curve",
        "GET /api/workstation/runs/{runId}/fills",
        "GET /api/workstation/runs/{runId}/ledger",
        "GET /api/workstation/runs/{runId}/ledger/journal",
        "GET /api/workstation/runs/{runId}/ledger/trial-balance",
        "GET /api/workstation/runs/{runId}/reconciliation",
        "GET /api/workstation/runs/{runId}/reconciliation/history",
        "GET /api/workstation/security-master/securities",
        "GET /api/workstation/security-master/securities/{securityId:guid}",
        "GET /api/workstation/security-master/securities/{securityId:guid}/economic-definition",
        "GET /api/workstation/security-master/securities/{securityId:guid}/history",
        "GET /api/workstation/security-master/securities/{securityId:guid}/identity",
        "GET /api/workstation/security-master/securities/{securityId:guid}/passport",
        "GET /api/workstation/security-master/securities/{securityId:guid}/trust-snapshot",
        "GET /api/workstation/session",
        "GET /api/workstation/settings/feature-capabilities",
        "GET /api/workstation/strategy",
        "GET /api/workstation/strategy/briefing",
        "GET /api/workstation/strategy/designer/drafts",
        "GET /api/workstation/strategy/designer/drafts/{documentId}",
        "GET /api/workstation/strategy/designer/field-catalog",
        "GET /api/workstation/strategy/designer/templates",
        "GET /api/workstation/strategy/engine/definitions",
        "GET /api/workstation/stream",
        "GET /api/workstation/trading",
        "GET /api/workstation/trading/readiness",
        "GET /api/workstation/workflow-summary",
        "GET /api/workstation/workflows",
        "GET /api/workstation/workflows/presets",
        "GET /health",
        "GET /health/detailed",
        "GET /healthz",
        "GET /live",
        "GET /livez",
        "GET /login",
        "GET /metrics",
        "GET /portal/reporting/access-grants/{grantId}/exchange",
        "GET /portal/reporting/packages/{packageId}",
        "GET /ready",
        "GET /readyz",
        "GET /setup/account",
        "GET /startup",
        "GET /startupz",
        "GET /workstation",
        "GET /workstation/{*path}",
    };

    [Fact]
    public void EveryMappedReadRoute_DeclaresPermissionOrOpenness_OrIsExplicitlyTracked()
    {
        var readRoutes = Fixture.Services.GetServices<EndpointDataSource>()
            .SelectMany(source => source.Endpoints)
            .OfType<RouteEndpoint>()
            .Where(endpoint =>
                (endpoint.Metadata.GetMetadata<HttpMethodMetadata>()?.HttpMethods ?? [])
                .Contains("GET", StringComparer.OrdinalIgnoreCase))
            .ToList();

        readRoutes.Should().NotBeEmpty();

        var undeclared = new List<string>();
        foreach (var endpoint in readRoutes)
        {
            var routeKey = $"GET /{(endpoint.RoutePattern.RawText ?? string.Empty).TrimStart('/')}";
            var declared =
                endpoint.Metadata.GetMetadata<EndpointAuthorizationMetadata>() is not null ||
                endpoint.Metadata.GetMetadata<EndpointOpenReadMetadata>() is not null;
            if (!declared)
                undeclared.Add(routeKey);
        }

        var undeclaredKeys = undeclared.ToHashSet(StringComparer.OrdinalIgnoreCase);
        var newViolations = undeclared
            .Where(key => !UndeclaredReadBaseline.Contains(key))
            .OrderBy(static key => key, StringComparer.Ordinal)
            .ToList();
        var remediated = UndeclaredReadBaseline
            .Where(key => !undeclaredKeys.Contains(key))
            .OrderBy(static key => key, StringComparer.Ordinal)
            .ToList();

        newViolations.Should().BeEmpty(
            "every newly mapped GET route must declare either a permission (RequirePermission / " +
            "RequireAnyPermission) or deliberate openness (DeclareOpenRead with a stated reason); " +
            "the frozen inventory only shrinks. Undeclared: {0}",
            string.Join("; ", newViolations));
        remediated.Should().BeEmpty(
            "these baseline reads now carry a declaration - remove them from " +
            "UndeclaredReadBaseline so the ratchet tightens: {0}",
            string.Join("; ", remediated));
    }
}
