using Meridian.Wpf.Views;

namespace Meridian.Wpf.Models;

public static partial class ShellNavigationCatalog
{
    private static readonly ShellPageDescriptor[] DataOperationsPages =
    [
        Page<DataOperationsWorkspaceShellPage>("DataOperationsShell", "Data Operations Workspace", "Queue-driven data workstation for providers, backfills, storage, and freshness review.", "data-operations", ShellNavigationSections.Overview, "\uEE94", 0, ShellNavigationVisibilityTier.Primary, ["data operations", "workspace", "queue"], ["Provider", "Backfill", "Storage", "DataQuality"], ["DataOperationsWorkspace"]),
        Page<ProviderPage>("Provider", "Providers", "Manage provider integrations, readiness, and operating posture.", "data-operations", ShellNavigationSections.Operations, "\uEC05", 10, ShellNavigationVisibilityTier.Primary, ["provider", "integrations"], ["ProviderHealth", "DataSources", "AddProviderWizard"], ["Providers"]),
        Page<BackfillPage>("Backfill", "Backfill", "Run and supervise gap-filling jobs with freshness and blocker visibility.", "data-operations", ShellNavigationSections.Operations, "\uE896", 20, ShellNavigationVisibilityTier.Primary, ["historical", "fill", "jobs"], ["CollectionSessions", "DataQuality", "Storage"]),
        Page<SymbolsPage>("Symbols", "Symbols", "Search, add, and curate the symbol catalog used across Meridian workflows.", "data-operations", ShellNavigationSections.Data, "\uE8AB", 30, ShellNavigationVisibilityTier.Primary, ["symbol", "catalog", "search"], ["SymbolMapping", "SymbolStorage", "SecurityMaster"]),
        Page<StoragePage>("Storage", "Storage", "Review storage posture, archive capacity, and persistence health.", "data-operations", ShellNavigationSections.Operations, "\uEE94", 40, ShellNavigationVisibilityTier.Primary, ["storage", "archive", "capacity"], ["StorageOptimization", "ArchiveHealth"]),
        Page<DataExportPage>("DataExport", "Data Export", "Package and export datasets for downstream consumption.", "data-operations", ShellNavigationSections.Data, "\uEDE1", 50, ShellNavigationVisibilityTier.Primary, ["export", "package"], ["ExportPresets", "AnalysisExport"]),
        Page<DataSourcesPage>("DataSources", "Data Sources", "Audit source connectivity, feed coverage, and readiness to collect.", "data-operations", ShellNavigationSections.Operations, "\uEC05", 60, ShellNavigationVisibilityTier.Secondary, ["sources", "connectivity"], ["Provider", "ProviderHealth"]),
        Page<SymbolMappingPage>("SymbolMapping", "Symbol Mapping", "Align vendor symbols and canonical Meridian identifiers.", "data-operations", ShellNavigationSections.Data, "\uE8AB", 70, ShellNavigationVisibilityTier.Secondary, ["mapping", "vendor"], ["Symbols", "SecurityMaster"]),
        Page<SymbolStoragePage>("SymbolStorage", "Symbol Storage", "Inspect symbol persistence and storage layout.", "data-operations", ShellNavigationSections.Data, "\uEE94", 80, ShellNavigationVisibilityTier.Secondary, ["symbol storage", "persistence"], ["Symbols", "Storage"]),
        Page<ScheduleManagerPage>("Schedules", "Schedules", "Coordinate scheduled collection, maintenance, and workstation jobs.", "data-operations", ShellNavigationSections.Operations, "\uE916", 90, ShellNavigationVisibilityTier.Secondary, ["schedule", "jobs"], ["Backfill", "CollectionSessions"]),
        Page<CollectionSessionPage>("CollectionSessions", "Collection Sessions", "Inspect recent ingest sessions and collector lifecycle state.", "data-operations", ShellNavigationSections.Operations, "\uE8EF", 100, ShellNavigationVisibilityTier.Secondary, ["collector", "sessions"], ["Backfill", "ProviderHealth"]),
        Page<PackageManagerPage>("PackageManager", "Package Manager", "Inspect datasets, packages, and installed workstation content.", "data-operations", ShellNavigationSections.Data, "\uE8B7", 110, ShellNavigationVisibilityTier.Secondary, ["packages", "content"], ["DataExport", "AnalysisExport"]),
        Page<DataBrowserPage>("DataBrowser", "Data Browser", "Inspect stored datasets and navigate raw time-series samples.", "data-operations", ShellNavigationSections.Data, "\uE721", 120, ShellNavigationVisibilityTier.Secondary, ["browser", "dataset"], ["DataSampling", "TimeSeriesAlignment"]),
        Page<DataCalendarPage>("DataCalendar", "Data Calendar", "Review date coverage, market calendars, and scheduling gaps.", "data-operations", ShellNavigationSections.Data, "\uE787", 130, ShellNavigationVisibilityTier.Secondary, ["calendar", "coverage"], ["TradingHours", "Backfill"]),
        Page<DataSamplingPage>("DataSampling", "Data Sampling", "Validate sample quality and inspect stored slices before export.", "data-operations", ShellNavigationSections.Data, "\uF1AD", 140, ShellNavigationVisibilityTier.Overflow, ["sampling", "quality"], ["DataBrowser", "DataQuality"]),
        Page<TimeSeriesAlignmentPage>("TimeSeriesAlignment", "Time Series Alignment", "Compare feeds and reconcile timestamp alignment issues.", "data-operations", ShellNavigationSections.Data, "\uE81E", 150, ShellNavigationVisibilityTier.Overflow, ["alignment", "timeseries"], ["DataSampling", "DataQuality"]),
        Page<ExportPresetsPage>("ExportPresets", "Export Presets", "Save and reuse export configurations across operator workflows.", "data-operations", ShellNavigationSections.Data, "\uE70B", 160, ShellNavigationVisibilityTier.Overflow, ["presets", "export"], ["DataExport", "AnalysisExport"]),
        Page<AnalysisExportPage>("AnalysisExport", "Analysis Export", "Generate analysis packages and handoff artifacts for downstream review.", "data-operations", ShellNavigationSections.Data, "\uEDE1", 170, ShellNavigationVisibilityTier.Overflow, ["analysis", "handoff"], ["AnalysisExportWizard", "DataExport"]),
        Page<AnalysisExportWizardPage>("AnalysisExportWizard", "Analysis Export Wizard", "Guide operators through structured analysis export setup.", "data-operations", ShellNavigationSections.Data, "\uE8B0", 180, ShellNavigationVisibilityTier.Overflow, ["wizard", "analysis"], ["AnalysisExport", "ExportPresets"]),
        Page<PortfolioImportPage>("PortfolioImport", "Portfolio Import", "Bring external portfolio snapshots into Meridian for downstream workflows.", "data-operations", ShellNavigationSections.Data, "\uE8B5", 190, ShellNavigationVisibilityTier.Overflow, ["import", "portfolio"], ["Symbols", "FundPortfolio"]),
        Page<IndexSubscriptionPage>("IndexSubscription", "Index Subscription", "Manage derived index subscriptions and coverage dependencies.", "data-operations", ShellNavigationSections.Data, "\uE8FD", 200, ShellNavigationVisibilityTier.Overflow, ["index", "subscription"], ["Symbols", "DataSources"]),
        Page<OptionsPage>("Options", "Options", "Inspect options and derivatives support surfaces.", "data-operations", ShellNavigationSections.Data, "\uE7C5", 210, ShellNavigationVisibilityTier.Overflow, ["options", "derivatives"], ["Symbols", "SecurityMaster"]),
        Page<AddProviderWizardPage>("AddProviderWizard", "Add Provider Wizard", "Guided flow for introducing a new provider integration.", "data-operations", ShellNavigationSections.Operations, "\uE710", 220, ShellNavigationVisibilityTier.Overflow, ["provider wizard", "setup"], ["Provider", "CredentialManagement"])
    ];
}
