using Meridian.Wpf.Views;

namespace Meridian.Wpf.Models;

public static partial class ShellNavigationCatalog
{
    private static readonly ShellPageDescriptor[] GovernancePages =
    [
        Page<GovernanceWorkspaceShellPage>("GovernanceShell", "Governance home", "Review controls, reconcile ledgers, and monitor audit readiness.", "governance", "Control Tower", "\uE8D7", 0, ShellNavigationVisibilityTier.Primary, ["governance", "home", "workspace", "review"], ["FundLedger", "FundReconciliation", "SecurityMaster", "Diagnostics"], ["GovernanceWorkspace"]),
        Page<FundLedgerPage>("FundLedger", "Fund operations", "Review journals, account activity, and control checkpoints.", "governance", "Fund Ops", "\uE82D", 10, ShellNavigationVisibilityTier.Primary, ["fund ledger", "journal", "operations", "review"], ["FundAccounts", "FundTrialBalance", "FundAuditTrail"], ["FundOperations"]),
        Page<FundAccountsPage>("FundAccounts", "Fund accounts", "Review balances, routing, and account status.", "governance", "Fund Ops", "\uE8C7", 20, ShellNavigationVisibilityTier.Primary, ["accounts", "balances", "review"], ["FundLedger", "FundBanking", "FundReconciliation"]),
        Page<FundLedgerPage>("FundReconciliation", "Fund reconciliation", "Reconcile breaks and review exception details.", "governance", "Fund Ops", "\uE7BA", 30, ShellNavigationVisibilityTier.Primary, ["reconciliation", "breaks", "reconcile"], ["FundTrialBalance", "FundAuditTrail", "Diagnostics"]),
        Page<SecurityMasterPage>("SecurityMaster", "Security master", "Review reference data and listing lifecycle changes.", "governance", "Assurance", "\uE72E", 40, ShellNavigationVisibilityTier.Primary, ["reference data", "security", "review"], ["Symbols", "SymbolMapping", "DataQuality"]),
        Page<DataQualityPage>("DataQuality", "Data quality", "Monitor validation alerts and resolve integrity issues.", "governance", "Assurance", "\uE73E", 50, ShellNavigationVisibilityTier.Primary, ["quality", "validation", "monitor"], ["ProviderHealth", "ArchiveHealth", "Diagnostics"]),
        Page<SystemHealthPage>("SystemHealth", "System health", "Monitor host health, dependencies, and readiness.", "governance", "Control Tower", "\uE9D9", 60, ShellNavigationVisibilityTier.Secondary, ["health", "system", "monitor"], ["Diagnostics", "ServiceManager"]),
        Page<DiagnosticsPage>("Diagnostics", "Diagnostics", "Review checks, latency, and service diagnostics.", "governance", "Control Tower", "\uE90F", 70, ShellNavigationVisibilityTier.Secondary, ["diagnostics", "troubleshooting", "review"], ["SystemHealth", "ServiceManager"]),
        Page<ProviderHealthPage>("ProviderHealth", "Provider health", "Monitor provider connectivity and recovery status.", "governance", "Assurance", "\uEB51", 80, ShellNavigationVisibilityTier.Secondary, ["provider health", "reachability", "monitor"], ["Provider", "DataQuality"]),
        Page<FundLedgerPage>("FundBanking", "Fund banking", "Review banking activity and fund cash-account balances.", "governance", "Fund Ops", "\uE825", 90, ShellNavigationVisibilityTier.Secondary, ["banking", "cash", "review"], ["FundAccounts", "FundCashFinancing"]),
        Page<FundLedgerPage>("FundPortfolio", "Fund portfolio", "Review fund positions and exposure changes.", "governance", "Fund Ops", "\uE821", 100, ShellNavigationVisibilityTier.Secondary, ["fund portfolio", "exposure", "review"], ["FundAccounts", "FundCashFinancing"]),
        Page<FundLedgerPage>("FundCashFinancing", "Fund cash and financing", "Review cash, financing, and liquidity metrics.", "governance", "Fund Ops", "\uEAFD", 110, ShellNavigationVisibilityTier.Secondary, ["cash financing", "liquidity", "review"], ["FundBanking", "FundPortfolio"]),
        Page<FundLedgerPage>("FundTrialBalance", "Fund trial balance", "Review trial-balance entries for the active fund.", "governance", "Fund Ops", "\uE8D2", 120, ShellNavigationVisibilityTier.Secondary, ["trial balance", "accounting", "review"], ["FundLedger", "FundReconciliation"]),
        Page<FundLedgerPage>("FundAuditTrail", "Fund audit trail", "Review approvals and audit history.", "governance", "Fund Ops", "\uE8D7", 130, ShellNavigationVisibilityTier.Secondary, ["audit", "approvals", "review"], ["FundLedger", "FundReconciliation"]),
        Page<FundLedgerPage>("FundReportPack", "Fund report pack", "Export governance report packs for stakeholder review.", "governance", "Fund Ops", "\uE8A5", 135, ShellNavigationVisibilityTier.Secondary, ["report pack", "reporting", "export"], ["FundCashFinancing", "FundAuditTrail", "FundTrialBalance"]),
        Page<ArchiveHealthPage>("ArchiveHealth", "Archive health", "Monitor archive integrity, retention, and data gaps.", "governance", "Assurance", "\uE73E", 140, ShellNavigationVisibilityTier.Secondary, ["archive", "retention", "monitor"], ["Storage", "RetentionAssurance"]),
        Page<StorageOptimizationPage>("StorageOptimization", "Storage optimization", "Configure retention settings and reduce storage footprint.", "governance", "Assurance", "\uE713", 150, ShellNavigationVisibilityTier.Overflow, ["optimization", "retention", "configure"], ["Storage", "ArchiveHealth"]),
        Page<RetentionAssurancePage>("RetentionAssurance", "Retention assurance", "Review retention-policy compliance and lifecycle status.", "governance", "Assurance", "\uE8A5", 160, ShellNavigationVisibilityTier.Overflow, ["retention", "policy", "review"], ["ArchiveHealth", "StorageOptimization"]),
        Page<ServiceManagerPage>("ServiceManager", "Service manager", "Monitor background services, logs, and restart controls.", "governance", "Control Tower", "\uECE7", 170, ShellNavigationVisibilityTier.Overflow, ["services", "logs", "monitor"], ["SystemHealth", "Diagnostics"]),
        Page<AdminMaintenancePage>("AdminMaintenance", "Admin maintenance", "Configure privileged maintenance tasks and safeguards.", "governance", "Control Tower", "\uE74D", 180, ShellNavigationVisibilityTier.Overflow, ["admin", "maintenance", "configure"], ["Diagnostics", "Settings"]),
        Page<EnvironmentDesignerPage>("EnvironmentDesigner", "Environment designer", "Configure operating models and publish controlled updates.", "governance", "Control Tower", "\uE70F", 185, ShellNavigationVisibilityTier.Overflow, ["environment", "designer", "configure"], ["AdminMaintenance", "GovernanceShell"]),
        Page<MessagingHubPage>("MessagingHub", "Messaging hub", "Review operator notifications and message delivery.", "governance", "Control Tower", "\uE715", 190, ShellNavigationVisibilityTier.Overflow, ["messaging", "notifications", "review"], ["NotificationCenter", "ActivityLog"]),
        Page<NotificationCenterPage>("NotificationCenter", "Notification center", "Review active alerts and system notifications.", "governance", "Control Tower", "\uE7F4", 200, ShellNavigationVisibilityTier.Overflow, ["notifications", "alerts", "review"], ["MessagingHub", "ActivityLog"], ["Alerts"]),
        Page<ActivityLogPage>("ActivityLog", "Activity log", "Review recent user actions and state changes.", "governance", "Control Tower", "\uE823", 210, ShellNavigationVisibilityTier.Overflow, ["activity", "history", "review"], ["NotificationCenter", "FundAuditTrail"]),
        Page<SettingsPage>("Settings", "Settings", "Configure workstation preferences and default connections.", "governance", "Support", "\uE713", 220, ShellNavigationVisibilityTier.Overflow, ["preferences", "settings", "configure"], ["CredentialManagement", "KeyboardShortcuts", "Help"], ["Preferences"]),
        Page<CredentialManagementPage>("CredentialManagement", "Credential management", "Configure provider credentials and verify secure access.", "governance", "Support", "\uE72E", 230, ShellNavigationVisibilityTier.Overflow, ["credentials", "security", "configure"], ["Settings", "AddProviderWizard"]),
        Page<KeyboardShortcutsPage>("KeyboardShortcuts", "Keyboard shortcuts", "Review and customize keyboard shortcuts.", "governance", "Support", "\uE765", 240, ShellNavigationVisibilityTier.Overflow, ["shortcuts", "keyboard", "review"], ["Help", "Settings"]),
        Page<HelpPage>("Help", "Help and support", "Review support guidance and troubleshooting resources.", "governance", "Support", "\uE897", 250, ShellNavigationVisibilityTier.Overflow, ["help", "support", "guidance"], ["KeyboardShortcuts", "Settings"]),
        Page<SetupWizardPage>("SetupWizard", "Setup wizard", "Configure workstation setup with guided steps.", "governance", "Support", "\uE8B0", 260, ShellNavigationVisibilityTier.Overflow, ["setup", "wizard", "configure"], ["Settings", "CredentialManagement"], hideFromDefaultPalette: true),
        Page<WorkspacePage>("Workspaces", "Workspaces", "Legacy workspace list for saved layouts.", "governance", "Legacy", "\uE8A9", 270, ShellNavigationVisibilityTier.Overflow, ["workspaces", "layouts", "legacy"], ["GovernanceShell"], hideFromDefaultPalette: true),
        Page<WelcomePage>("Welcome", "Welcome", "Review onboarding guidance for first-time setup.", "governance", "Support", "\uE80F", 280, ShellNavigationVisibilityTier.Overflow, ["welcome", "onboarding", "guidance"], ["SetupWizard", "Help"], hideFromDefaultPalette: true)
    ];
}
