using Meridian.Wpf.Features.Reporting.Shell;
using Meridian.Wpf.Features.Settings.Shell;
using Meridian.Wpf.Views;

namespace Meridian.Wpf.Models;

public static partial class ShellNavigationCatalog
{
    private static readonly ShellPageDescriptor[] AccountingPages =
    [
        Page<AccountingWorkspaceShellPage>("AccountingShell", "Accounting Workspace", "Review ledger, cash, reconciliation, trial balance, and audit workflows.", "accounting", "Launchpad", "\uE8D7", 0, ShellNavigationVisibilityTier.Primary, ["accounting", "ledger", "workspace", "control"], ["FundLedger", "FundReconciliation", "FundTrialBalance", "FundAuditTrail"], LegacyAccountingShellAliases),
        Page<FundStructureSetupPage>("FundStructureSetup", "Entity setup", "Create fund-structure entities, ownership links, and account handoff drafts.", "accounting", "Fund Ops", "\uE8EF", 5, ShellNavigationVisibilityTier.Primary, ["entity setup", "fund structure", "onboarding", "ownership"], ["FundLedger", "FundAccounts"], ["EntitySetup"]),
        Page<FundLedgerPage>("FundLedger", "Fund operations", "Review journal, account, and accounting readiness in one view.", "accounting", "Fund Ops", "\uE82D", 10, ShellNavigationVisibilityTier.Primary, ["fund ledger", "journal", "operations", "continuity", "close readiness"], ["FundAccounts", "FundTrialBalance", "FundAuditTrail", "FundStructureSetup"], ["FundOperations", "OperationsContinuity", "OperationsClose"]),
        Page<RunLedgerPage>("RunLedger", "Run ledger", "Review run postings and execution-linked cash movement.", "accounting", "Run Inspectors", "\uE82D", 20, ShellNavigationVisibilityTier.Primary, ["ledger", "postings", "review"], ["PositionBlotter", "RunRisk", "FundLedger"], ["LedgerInspector"]),
        Page<RunCashFlowPage>("RunCashFlow", "Run cash flow", "Review simulated cash, financing, and funding impacts.", "accounting", "Run Inspectors", "\uEAFD", 30, ShellNavigationVisibilityTier.Primary, ["cash flow", "cash", "financing"], ["RunPortfolio", "RunLedger"]),
        Page<FundLedgerPage>("FundBanking", "Fund banking", "Review banking readiness and fund cash-account detail.", "accounting", "Fund Ops", "\uE825", 40, ShellNavigationVisibilityTier.Secondary, ["banking", "cash"], ["FundAccounts", "FundCashFinancing"]),
        Page<FundLedgerPage>("FundCashFinancing", "Fund cash and financing", "Review fund cash, financing, and liquidity metrics.", "accounting", "Fund Ops", "\uEAFD", 50, ShellNavigationVisibilityTier.Secondary, ["cash financing", "liquidity"], ["FundBanking", "FundPortfolio"]),
        Page<AccountingConfigurePage>("FundAccountingConfigure", "Accounting configure", "Review books, chart, rules, manual journals, GL evidence, validation, audit readiness.", "accounting", "Fund Ops", "\uE713", 55, ShellNavigationVisibilityTier.Secondary, ["configure", "chart", "templates", "posting rules", "manual journals", "external GL", "audit"], ["FundLedger", "FundTrialBalance", "FundAuditTrail"]),
        Page<AccountingClosePage>("FundAccountingClose", "Accounting close", "Edit close plans, dependencies, sign-offs, adjustments, evidence, blockers, and locks.", "accounting", "Fund Ops", "\uE7C3", 57, ShellNavigationVisibilityTier.Secondary, ["close", "close plan", "dependencies", "sign-off", "late adjustments", "period lock", "evidence"], ["FundAccountingConfigure", "FundLedger", "FundAuditTrail"], ["AccountingClose", "CloseManagement"]),
        Page<FundLedgerPage>("FundTrialBalance", "Fund trial balance", "Review trial-balance detail for the active fund.", "accounting", "Fund Ops", "\uE8D2", 60, ShellNavigationVisibilityTier.Secondary, ["trial balance", "accounting"], ["FundLedger", "FundReconciliation", "FundAccountingConfigure"]),
        Page<FinancialRecordExplorerPage>("LedgerExplorer", "Ledger explorer", "Inspect ledger rows, proof actions, report usage, and audit relationships.", "accounting", "Fund Ops", "\uE8D2", 65, ShellNavigationVisibilityTier.Secondary, ["ledger explorer", "financial record", "proof", "trial balance"], ["FundLedger", "FundTrialBalance", "RunLedger", "FundAuditTrail"]),
        Page<FundLedgerPage>("FundReconciliation", "Fund reconciliation", "Inspect reconciliation runs, breaks, and review detail.", "accounting", "Fund Ops", "\uE7BA", 70, ShellNavigationVisibilityTier.Primary, ["reconciliation", "breaks"], ["FundTrialBalance", "FundAuditTrail", "Diagnostics"]),
        Page<FundLedgerPage>("FundAuditTrail", "Fund audit trail", "Inspect approvals, audit references, and accounting history.", "accounting", "Fund Ops", "\uE8D7", 80, ShellNavigationVisibilityTier.Secondary, ["audit", "approvals", "evidence"], ["FundLedger", "FundReconciliation", "LedgerExplorer"], ["EvidenceWorkbench", "AccountingApprovals"]),
        Page<FinancialRecordExplorerPage>("SecurityInstrumentExplorer", "Security and instrument explorer", "Inspect Security Master references for ledger and portfolio record relationships.", "accounting", "Fund Ops", "\uE72E", 90, ShellNavigationVisibilityTier.Secondary, ["security explorer", "instrument", "financial record", "proof"], ["SecurityMaster", "LedgerExplorer", "FundLedger", "PortfolioExplorer"])
    ];

    private static readonly ShellPageDescriptor[] ReportingPages =
    [
        Page<ReportingWorkspaceShellPage>("ReportingShell", "Reporting Workspace", "Prepare report packs, dashboards, analysis exports, and export presets.", "reporting", "Launchpad", "\uE8A5", 0, ShellNavigationVisibilityTier.Primary, ["reporting", "reports", "workspace", "export"], ["FundReportPack", "ReportRunStatus", "ReportLineProvenanceExplorer", "Dashboard", "AnalysisExport", "ExportPresets"]),
        Page<FundLedgerPage>("FundReportPack", "Fund report pack", "Preview report packs and downstream handoff readiness.", "reporting", "Report Packs", "\uE8A5", 10, ShellNavigationVisibilityTier.Primary, ["report pack", "reporting", "board pack"], ["ReportRunStatus", "ReportLineProvenanceExplorer", "FundCashFinancing", "FundAuditTrail", "FundTrialBalance"]),
        Page<DashboardPage>("ReportRunStatus", "Report run status", "Review run manifests, approval gates, retry audits, and dataset lineage.", "reporting", "Report Packs", "\uE9D9", 15, ShellNavigationVisibilityTier.Primary, ["report status", "approval", "lineage", "audit", "schedule"], ["FundReportPack", "ReportLineProvenanceExplorer", "Dashboard", "FundAuditTrail"]),
        Page<FinancialRecordExplorerPage>("ReportLineProvenanceExplorer", "Report-line provenance", "Drill from report lines to source records, journals, approvals, restatement evidence.", "reporting", "Report Packs", "\uE8D7", 18, ShellNavigationVisibilityTier.Secondary, ["report line", "provenance", "evidence", "drill-through"], ["FundReportPack", "ReportRunStatus", "FundAuditTrail", "FundReconciliation", "LedgerExplorer"]),
        Page<DashboardPage>("Dashboard", "Reporting dashboard", "Monitor holdings, quality exceptions, maturities, and export readiness.", "reporting", "Dashboard", "\uE71D", 20, ShellNavigationVisibilityTier.Primary, ["overview", "portfolio", "holdings", "quality"], ["ReportingShell", "DataQuality", "SecurityMaster"], hideFromDefaultPalette: true),
        Page<AnalysisExportPage>("AnalysisExport", "Analysis export", "Export analysis packages for downstream review.", "reporting", "Exports", "\uEDE1", 30, ShellNavigationVisibilityTier.Primary, ["analysis", "export", "review"], ["AnalysisExportWizard", "DataExport"]),
        Page<AnalysisExportWizardPage>("AnalysisExportWizard", "Analysis export wizard", "Configure analysis export steps with guided prompts.", "reporting", "Exports", "\uE8B0", 40, ShellNavigationVisibilityTier.Secondary, ["wizard", "analysis", "configure"], ["AnalysisExport", "ExportPresets"]),
        Page<ExportPresetsPage>("ExportPresets", "Export presets", "Configure reusable export settings.", "reporting", "Exports", "\uE70B", 50, ShellNavigationVisibilityTier.Secondary, ["presets", "export", "configure"], ["DataExport", "AnalysisExport"])
    ];

}
