using Meridian.Wpf.Views;

namespace Meridian.Wpf.Models;

public static partial class ShellNavigationCatalog
{
    private static readonly ShellPageDescriptor[] DataOperationsPages =
    [
        Page<DataOperationsWorkspaceShellPage>("DataOperationsShell", "Data Operations Workspace", "Monitor providers, review collection jobs, and export data products.", "data-operations", "Launchpad", "\uEE94", 0, ShellNavigationVisibilityTier.Primary, ["data operations", "home", "workspace", "monitor"], ["Provider", "ProviderHealth", "Backfill", "Storage", "DataQuality"], ["DataOperationsWorkspace"]),
        Page<ProviderPage>("Provider", "Providers", "Configure provider integrations and review readiness.", "data-operations", "Operations Queue", "\uEC05", 10, ShellNavigationVisibilityTier.Primary, ["provider", "integrations", "configure"], ["ProviderHealth", "DataSources", "AddProviderWizard"], ["Providers"]),
        Page<BackfillPage>("Backfill", "Backfill", "Monitor gap-fill jobs and review blockers.", "data-operations", "Operations Queue", "\uE896", 20, ShellNavigationVisibilityTier.Primary, ["historical", "backfill", "jobs", "monitor"], ["CollectionSessions", "DataQuality", "Storage"]),
        Page<SymbolsPage>("Symbols", "Symbols", "Review, add, and curate symbols used across workflows.", "data-operations", "Catalog", "\uE8AB", 30, ShellNavigationVisibilityTier.Primary, ["symbol", "catalog", "search", "review"], ["SymbolMapping", "SymbolStorage", "SecurityMaster"]),
        Page<StoragePage>("Storage", "Storage", "Monitor storage health, capacity, and retention.", "data-operations", "Platform", "\uEE94", 40, ShellNavigationVisibilityTier.Primary, ["storage", "archive", "capacity", "monitor"], ["StorageOptimization", "ArchiveHealth"]),
        Page<DataExportPage>("DataExport", "Data export", "Configure export jobs and deliver datasets.", "data-operations", "Packaging", "\uEDE1", 50, ShellNavigationVisibilityTier.Primary, ["export", "package", "configure"], ["ExportPresets", "AnalysisExport"]),
        Page<DataSourcesPage>("DataSources", "Data sources", "Review source connectivity and feed coverage.", "data-operations", "Operations Queue", "\uEC05", 60, ShellNavigationVisibilityTier.Secondary, ["sources", "connectivity", "review"], ["Provider", "ProviderHealth"]),
        Page<ProviderHealthPage>("ProviderHealth", "Provider Health", "Inspect provider reachability, degraded states, and recovery guidance.", "data-operations", "Operations Queue", "\uEB51", 65, ShellNavigationVisibilityTier.Secondary, ["provider health", "reachability"], ["Provider", "DataSources", "CollectionSessions", "DataQuality"]),
        Page<SymbolMappingPage>("SymbolMapping", "Symbol mapping", "Reconcile vendor symbols with Meridian identifiers.", "data-operations", "Catalog", "\uE8AB", 70, ShellNavigationVisibilityTier.Secondary, ["mapping", "vendor", "reconcile"], ["Symbols", "SecurityMaster"]),
        Page<SymbolStoragePage>("SymbolStorage", "Symbol storage", "Review symbol persistence and storage layout.", "data-operations", "Catalog", "\uEE94", 80, ShellNavigationVisibilityTier.Secondary, ["symbol storage", "persistence", "review"], ["Symbols", "Storage"]),
        Page<ScheduleManagerPage>("Schedules", "Schedules", "Configure collection and maintenance schedules.", "data-operations", "Platform", "\uE916", 90, ShellNavigationVisibilityTier.Secondary, ["schedule", "jobs", "configure"], ["Backfill", "CollectionSessions"]),
        Page<CollectionSessionPage>("CollectionSessions", "Collection sessions", "Monitor ingest sessions and collector state.", "data-operations", "Operations Queue", "\uE8EF", 100, ShellNavigationVisibilityTier.Secondary, ["collector", "sessions", "monitor"], ["Backfill", "ProviderHealth"]),
        Page<PackageManagerPage>("PackageManager", "Package manager", "Review datasets, packages, and installed content.", "data-operations", "Packaging", "\uE8B7", 110, ShellNavigationVisibilityTier.Secondary, ["packages", "content", "review"], ["DataExport", "AnalysisExport"]),
        Page<DataBrowserPage>("DataBrowser", "Data browser", "Review stored datasets and sample time-series records.", "data-operations", "Inspectors", "\uE721", 120, ShellNavigationVisibilityTier.Secondary, ["browser", "dataset", "review"], ["DataSampling", "TimeSeriesAlignment"]),
        Page<DataCalendarPage>("DataCalendar", "Data calendar", "Review date coverage and schedule gaps.", "data-operations", "Inspectors", "\uE787", 130, ShellNavigationVisibilityTier.Secondary, ["calendar", "coverage", "review"], ["TradingHours", "Backfill"]),
        Page<DataSamplingPage>("DataSampling", "Data sampling", "Review sample quality before export.", "data-operations", "Inspectors", "\uF1AD", 140, ShellNavigationVisibilityTier.Overflow, ["sampling", "quality", "review"], ["DataBrowser", "DataQuality"]),
        Page<TimeSeriesAlignmentPage>("TimeSeriesAlignment", "Time series alignment", "Reconcile timestamps across feeds and intervals.", "data-operations", "Inspectors", "\uE81E", 150, ShellNavigationVisibilityTier.Overflow, ["alignment", "timeseries", "reconcile"], ["DataSampling", "DataQuality"]),
        Page<ExportPresetsPage>("ExportPresets", "Export presets", "Configure reusable export settings.", "data-operations", "Packaging", "\uE70B", 160, ShellNavigationVisibilityTier.Overflow, ["presets", "export", "configure"], ["DataExport", "AnalysisExport"]),
        Page<AnalysisExportPage>("AnalysisExport", "Analysis export", "Export analysis packages for downstream review.", "data-operations", "Packaging", "\uEDE1", 170, ShellNavigationVisibilityTier.Overflow, ["analysis", "export", "review"], ["AnalysisExportWizard", "DataExport"]),
        Page<AnalysisExportWizardPage>("AnalysisExportWizard", "Analysis export wizard", "Configure analysis export steps with guided prompts.", "data-operations", "Packaging", "\uE8B0", 180, ShellNavigationVisibilityTier.Overflow, ["wizard", "analysis", "configure"], ["AnalysisExport", "ExportPresets"]),
        Page<PortfolioImportPage>("PortfolioImport", "Portfolio import", "Import external portfolio snapshots for reconciliation.", "data-operations", "Catalog", "\uE8B5", 190, ShellNavigationVisibilityTier.Overflow, ["import", "portfolio", "reconcile"], ["Symbols", "FundPortfolio"]),
        Page<IndexSubscriptionPage>("IndexSubscription", "Index subscription", "Configure derived index subscriptions and coverage.", "data-operations", "Catalog", "\uE8FD", 200, ShellNavigationVisibilityTier.Overflow, ["index", "subscription", "configure"], ["Symbols", "DataSources"]),
        Page<OptionsPage>("Options", "Options", "Review options and derivatives coverage.", "data-operations", "Catalog", "\uE7C5", 210, ShellNavigationVisibilityTier.Overflow, ["options", "derivatives", "review"], ["Symbols", "SecurityMaster"]),
        Page<AddProviderWizardPage>("AddProviderWizard", "Add provider wizard", "Configure a new provider integration step by step.", "data-operations", "Operations Queue", "\uE710", 220, ShellNavigationVisibilityTier.Overflow, ["provider wizard", "setup", "configure"], ["Provider", "CredentialManagement"])
    ];
}
