using Meridian.Wpf.Views;

namespace Meridian.Wpf.Models;

public static partial class ShellNavigationCatalog
{
    private static readonly ShellPageDescriptor[] GovernancePages =
    [
        Page<GovernanceWorkspaceShellPage>("GovernanceShell", "Governance Workspace", "Trust-critical review for accounts, ledger, reconciliation, and audit evidence.", "governance", "Governance", "\uE8D7", 0, ShellNavigationVisibilityTier.Primary, ["governance", "workspace", "control"], ["FundLedger", "FundReconciliation", "SecurityMaster", "Diagnostics"], ["GovernanceWorkspace"]),
        Page<FundLedgerPage>("FundLedger", "Fund Operations", "Review journal, account, and governance operations readiness in one view.", "governance", "Fund Ops", "\uE82D", 10, ShellNavigationVisibilityTier.Primary, ["fund ledger", "journal", "operations"], ["FundAccounts", "FundTrialBalance", "FundAuditTrail"], ["FundOperations"]),
        Page<FundAccountsPage>("FundAccounts", "Fund Accounts", "Inspect account balances, routing, and reconciliation readiness.", "governance", "Fund Ops", "\uE8C7", 20, ShellNavigationVisibilityTier.Primary, ["accounts", "balances"], ["FundLedger", "FundBanking", "FundReconciliation"]),
        Page<FundLedgerPage>("FundReconciliation", "Fund Operations: Reconciliation", "Inspect reconciliation runs, breaks, and exception detail within Fund Operations.", "governance", "Fund Ops", "\uE7BA", 30, ShellNavigationVisibilityTier.Primary, ["reconciliation", "breaks"], ["FundTrialBalance", "FundAuditTrail", "Diagnostics"]),
        Page<SecurityMasterPage>("SecurityMaster", "Security Master", "Review reference data, listings, and security lifecycle readiness.", "governance", "Assurance", "\uE72E", 40, ShellNavigationVisibilityTier.Primary, ["reference data", "security"], ["Symbols", "SymbolMapping", "DataQuality"]),
        Page<DataQualityPage>("DataQuality", "Data Quality", "Track validation signals, integrity issues, and remediation state.", "governance", "Assurance", "\uE73E", 50, ShellNavigationVisibilityTier.Primary, ["quality", "validation"], ["ProviderHealth", "ArchiveHealth", "Diagnostics"]),
        Page<SystemHealthPage>("SystemHealth", "System Health", "Monitor host health, dependencies, and workstation readiness.", "governance", "Operations", "\uE9D9", 60, ShellNavigationVisibilityTier.Secondary, ["health", "system"], ["Diagnostics", "ServiceManager"]),
        Page<DiagnosticsPage>("Diagnostics", "Diagnostics", "Run checks, inspect latency, and troubleshoot operator issues.", "governance", "Operations", "\uE90F", 70, ShellNavigationVisibilityTier.Secondary, ["diagnostics", "troubleshooting"], ["SystemHealth", "ServiceManager"]),
        Page<ProviderHealthPage>("ProviderHealth", "Provider Health", "Inspect provider reachability, degraded states, and recovery guidance.", "governance", "Assurance", "\uEB51", 80, ShellNavigationVisibilityTier.Secondary, ["provider health", "reachability"], ["Provider", "DataQuality"]),
        Page<FundLedgerPage>("FundBanking", "Fund Operations: Banking", "Review banking readiness and fund cash-account detail within Fund Operations.", "governance", "Fund Ops", "\uE825", 90, ShellNavigationVisibilityTier.Secondary, ["banking", "cash"], ["FundAccounts", "FundCashFinancing"]),
        Page<FundLedgerPage>("FundPortfolio", "Fund Operations: Portfolio", "Inspect fund-scoped positions and exposure detail within Fund Operations.", "governance", "Fund Ops", "\uE821", 100, ShellNavigationVisibilityTier.Secondary, ["fund portfolio", "exposure"], ["FundAccounts", "FundCashFinancing"]),
        Page<FundLedgerPage>("FundCashFinancing", "Fund Operations: Cash and Financing", "Review fund cash, financing, and liquidity metrics within Fund Operations.", "governance", "Fund Ops", "\uEAFD", 110, ShellNavigationVisibilityTier.Secondary, ["cash financing", "liquidity"], ["FundBanking", "FundPortfolio"]),
        Page<FundLedgerPage>("FundTrialBalance", "Fund Operations: Trial Balance", "Review trial-balance detail for the active fund within Fund Operations.", "governance", "Fund Ops", "\uE8D2", 120, ShellNavigationVisibilityTier.Secondary, ["trial balance", "accounting"], ["FundLedger", "FundReconciliation"]),
        Page<FundLedgerPage>("FundAuditTrail", "Fund Operations: Audit Trail", "Inspect approvals, audit references, and governance history within Fund Operations.", "governance", "Fund Ops", "\uE8D7", 130, ShellNavigationVisibilityTier.Secondary, ["audit", "approvals"], ["FundLedger", "FundReconciliation"]),
        Page<FundLedgerPage>("FundReportPack", "Fund Operations: Report Pack", "Preview governance report packs and downstream handoff readiness within Fund Operations.", "governance", "Fund Ops", "\uE8A5", 135, ShellNavigationVisibilityTier.Secondary, ["report pack", "reporting", "board pack"], ["FundCashFinancing", "FundAuditTrail", "FundTrialBalance"]),
        Page<ArchiveHealthPage>("ArchiveHealth", "Archive Health", "Review archive integrity, retention readiness, and gap signals.", "governance", "Assurance", "\uE73E", 140, ShellNavigationVisibilityTier.Secondary, ["archive", "retention"], ["Storage", "RetentionAssurance"]),
        Page<StorageOptimizationPage>("StorageOptimization", "Storage Optimization", "Tune retention, footprint, and storage efficiency.", "governance", "Assurance", "\uE713", 150, ShellNavigationVisibilityTier.Overflow, ["optimization", "retention"], ["Storage", "ArchiveHealth"]),
        Page<RetentionAssurancePage>("RetentionAssurance", "Retention Assurance", "Validate retention-policy adherence and lifecycle readiness.", "governance", "Assurance", "\uE8A5", 160, ShellNavigationVisibilityTier.Overflow, ["retention", "policy"], ["ArchiveHealth", "StorageOptimization"]),
        Page<ServiceManagerPage>("ServiceManager", "Service Manager", "Inspect background services, logs, and operational controls.", "governance", "Operations", "\uECE7", 170, ShellNavigationVisibilityTier.Overflow, ["services", "logs"], ["SystemHealth", "Diagnostics"]),
        Page<AdminMaintenancePage>("AdminMaintenance", "Admin Maintenance", "Execute privileged maintenance tasks and governance operations.", "governance", "Operations", "\uE74D", 180, ShellNavigationVisibilityTier.Overflow, ["admin", "maintenance"], ["Diagnostics", "Settings"]),
        Page<EnvironmentDesignerPage>("EnvironmentDesigner", "Environment Designer", "Draft, validate, publish, and roll back company umbrella operating models.", "governance", "Operations", "\uE70F", 185, ShellNavigationVisibilityTier.Overflow, ["environment", "designer", "lanes"], ["AdminMaintenance", "GovernanceShell"]),
        Page<MessagingHubPage>("MessagingHub", "Messaging Hub", "Inspect operator notifications and internal messaging pathways.", "governance", "Operations", "\uE715", 190, ShellNavigationVisibilityTier.Overflow, ["messaging", "notifications"], ["NotificationCenter", "ActivityLog"]),
        Page<NotificationCenterPage>("NotificationCenter", "Notification Center", "Review active notifications, alerts, and workstation events.", "governance", "Operations", "\uE7F4", 200, ShellNavigationVisibilityTier.Overflow, ["notifications", "alerts"], ["MessagingHub", "ActivityLog"], ["Alerts"]),
        Page<ActivityLogPage>("ActivityLog", "Activity Log", "Review recent workstation actions and state changes.", "governance", "Operations", "\uE823", 210, ShellNavigationVisibilityTier.Overflow, ["activity", "history"], ["NotificationCenter", "FundAuditTrail"]),
        Page<SettingsPage>("Settings", "Settings", "Adjust workstation preferences, connections, and operator defaults.", "governance", "Support", "\uE713", 220, ShellNavigationVisibilityTier.Overflow, ["preferences", "settings"], ["CredentialManagement", "KeyboardShortcuts", "Help"], ["Preferences"]),
        Page<CredentialManagementPage>("CredentialManagement", "Credential Management", "Manage provider credentials and validate secure access.", "governance", "Support", "\uE72E", 230, ShellNavigationVisibilityTier.Overflow, ["credentials", "security"], ["Settings", "AddProviderWizard"]),
        Page<KeyboardShortcutsPage>("KeyboardShortcuts", "Keyboard Shortcuts", "Review accelerator keys and workstation shortcuts.", "governance", "Support", "\uE765", 240, ShellNavigationVisibilityTier.Overflow, ["shortcuts", "keyboard"], ["Help", "Settings"]),
        Page<HelpPage>("Help", "Help and Support", "Access support resources and workstation guidance.", "governance", "Support", "\uE897", 250, ShellNavigationVisibilityTier.Overflow, ["help", "support"], ["KeyboardShortcuts", "Settings"]),
        Page<SetupWizardPage>("SetupWizard", "Setup Wizard", "Complete initial workstation setup and guided configuration.", "governance", "Support", "\uE8B0", 260, ShellNavigationVisibilityTier.Overflow, ["setup", "wizard"], ["Settings", "CredentialManagement"], hideFromDefaultPalette: true),
        Page<WorkspacePage>("Workspaces", "Workspace layouts", "Workspace layout catalog and saved-layout surface.", "governance", "Workspace layouts", "\uE8A9", 270, ShellNavigationVisibilityTier.Overflow, ["workspaces", "layouts"], ["GovernanceShell"], hideFromDefaultPalette: true),
        Page<WelcomePage>("Welcome", "Welcome", "Onboarding entry point and first-run guidance.", "governance", "Support", "\uE80F", 280, ShellNavigationVisibilityTier.Overflow, ["welcome", "onboarding"], ["SetupWizard", "Help"], hideFromDefaultPalette: true)
    ];
}
