using Meridian.Wpf.Views;

namespace Meridian.Wpf.Models;

public static partial class ShellNavigationCatalog
{
    private static readonly ShellPageDescriptor[] DataPages =
    [
        Page<DataOperationsWorkspaceShellPage>("DataShell", "Data Workspace", "Monitor providers, collection jobs, storage, quality, and data products.", "data", "Launchpad", "\uEE94", 0, ShellNavigationVisibilityTier.Primary, ["data", "data operations", "home", "workspace"], ["Provider", "ProviderHealth", "Backfill", "Storage", "DataQuality"], ["DataOperationsShell", "DataOperationsWorkspace"]),
        Page<ProviderPage>("Provider", "Providers", "Configure provider integrations and review readiness.", "data", "Operations Queue", "\uEC05", 10, ShellNavigationVisibilityTier.Primary, ["provider", "integrations", "configure"], ["ProviderHealth", "DataSources", "AddProviderWizard"], ["Providers"]),
        Page<BackfillPage>("Backfill", "Backfill", "Monitor gap-fill jobs and review blockers.", "data", "Operations Queue", "\uE896", 20, ShellNavigationVisibilityTier.Primary, ["historical", "backfill", "jobs", "monitor"], ["CollectionSessions", "DataQuality", "Storage"]),
        Page<SymbolsPage>("Symbols", "Symbols", "Review, add, and curate symbols used across workflows.", "data", "Catalog", "\uE8AB", 30, ShellNavigationVisibilityTier.Primary, ["symbol", "catalog", "search", "review"], ["SymbolMapping", "SymbolStorage", "SecurityMaster"]),
        Page<StoragePage>("Storage", "Storage", "Monitor storage health, capacity, and retention.", "data", "Platform", "\uEE94", 40, ShellNavigationVisibilityTier.Primary, ["storage", "archive", "capacity", "monitor"], ["StorageOptimization", "ArchiveHealth"]),
        Page<DataExportPage>("DataExport", "Data export", "Configure export jobs and deliver datasets.", "data", "Packaging", "\uEDE1", 50, ShellNavigationVisibilityTier.Primary, ["export", "package", "configure"], ["ExportPresets", "AnalysisExport"]),
        Page<DataSourcesPage>("DataSources", "Data sources", "Review source connectivity and feed coverage.", "data", "Operations Queue", "\uEC05", 60, ShellNavigationVisibilityTier.Secondary, ["sources", "connectivity", "review"], ["Provider", "ProviderHealth"]),
        Page<ProviderHealthPage>("ProviderHealth", "Provider health", "Inspect provider reachability, degraded states, and recovery guidance.", "data", "Operations Queue", "\uEB51", 65, ShellNavigationVisibilityTier.Secondary, ["provider health", "reachability"], ["Provider", "DataSources", "CollectionSessions", "DataQuality"]),
        Page<DataQualityPage>("DataQuality", "Data quality", "Track validation signals, integrity issues, and remediation state.", "data", "Assurance", "\uE73E", 70, ShellNavigationVisibilityTier.Secondary, ["quality", "validation"], ["ProviderHealth", "ArchiveHealth", "Diagnostics"]),
        Page<SecurityMasterPage>("SecurityMaster", "Security master", "Review reference data, listings, and security lifecycle readiness.", "data", "Assurance", "\uE72E", 80, ShellNavigationVisibilityTier.Secondary, ["reference data", "security"], ["Symbols", "SymbolMapping", "DataQuality"]),
        Page<SymbolMappingPage>("SymbolMapping", "Symbol mapping", "Reconcile vendor symbols with Meridian identifiers.", "data", "Catalog", "\uE8AB", 90, ShellNavigationVisibilityTier.Secondary, ["mapping", "vendor", "reconcile"], ["Symbols", "SecurityMaster"]),
        Page<SymbolStoragePage>("SymbolStorage", "Symbol storage", "Review symbol persistence and storage layout.", "data", "Catalog", "\uEE94", 100, ShellNavigationVisibilityTier.Secondary, ["symbol storage", "persistence", "review"], ["Symbols", "Storage"]),
        Page<ScheduleManagerPage>("Schedules", "Schedules", "Configure collection and maintenance schedules.", "data", "Platform", "\uE916", 110, ShellNavigationVisibilityTier.Secondary, ["schedule", "jobs", "configure"], ["Backfill", "CollectionSessions"]),
        Page<CollectionSessionPage>("CollectionSessions", "Collection sessions", "Monitor ingest sessions and collector state.", "data", "Operations Queue", "\uE8EF", 120, ShellNavigationVisibilityTier.Secondary, ["collector", "sessions", "monitor"], ["Backfill", "ProviderHealth"]),
        Page<PackageManagerPage>("PackageManager", "Package manager", "Review datasets, packages, and installed content.", "data", "Packaging", "\uE8B7", 130, ShellNavigationVisibilityTier.Secondary, ["packages", "content", "review"], ["DataExport", "AnalysisExport"]),
        Page<DataBrowserPage>("DataBrowser", "Data browser", "Review stored datasets and sample time-series records.", "data", "Inspectors", "\uE721", 140, ShellNavigationVisibilityTier.Overflow, ["browser", "dataset", "review"], ["DataSampling", "TimeSeriesAlignment"]),
        Page<DataCalendarPage>("DataCalendar", "Data calendar", "Review date coverage and schedule gaps.", "data", "Inspectors", "\uE787", 150, ShellNavigationVisibilityTier.Overflow, ["calendar", "coverage", "review"], ["TradingHours", "Backfill"]),
        Page<DataSamplingPage>("DataSampling", "Data sampling", "Review sample quality before export.", "data", "Inspectors", "\uF1AD", 160, ShellNavigationVisibilityTier.Overflow, ["sampling", "quality", "review"], ["DataBrowser", "DataQuality"]),
        Page<TimeSeriesAlignmentPage>("TimeSeriesAlignment", "Time series alignment", "Reconcile timestamps across feeds and intervals.", "data", "Inspectors", "\uE81E", 170, ShellNavigationVisibilityTier.Overflow, ["alignment", "timeseries", "reconcile"], ["DataSampling", "DataQuality"]),
        Page<IndexSubscriptionPage>("IndexSubscription", "Index subscription", "Configure derived index subscriptions and coverage.", "data", "Catalog", "\uE8FD", 180, ShellNavigationVisibilityTier.Overflow, ["index", "subscription", "configure"], ["Symbols", "DataSources"]),
        Page<OptionsPage>("Options", "Options", "Review options and derivatives coverage.", "data", "Catalog", "\uE7C5", 190, ShellNavigationVisibilityTier.Overflow, ["options", "derivatives", "review"], ["Symbols", "SecurityMaster"]),
        Page<AddProviderWizardPage>("AddProviderWizard", "Add provider wizard", "Configure a new provider integration step by step.", "data", "Operations Queue", "\uE710", 200, ShellNavigationVisibilityTier.Overflow, ["provider wizard", "setup", "configure"], ["Provider", "CredentialManagement"]),
        Page<ArchiveHealthPage>("ArchiveHealth", "Archive health", "Review archive integrity, retention readiness, and gap signals.", "data", "Assurance", "\uE73E", 210, ShellNavigationVisibilityTier.Overflow, ["archive", "retention"], ["Storage", "RetentionAssurance"]),
        Page<StorageOptimizationPage>("StorageOptimization", "Storage optimization", "Tune retention, footprint, and storage efficiency.", "data", "Assurance", "\uE713", 220, ShellNavigationVisibilityTier.Overflow, ["optimization", "retention"], ["Storage", "ArchiveHealth"]),
        Page<RetentionAssurancePage>("RetentionAssurance", "Retention assurance", "Validate retention-policy adherence and lifecycle readiness.", "data", "Assurance", "\uE8A5", 230, ShellNavigationVisibilityTier.Overflow, ["retention", "policy"], ["ArchiveHealth", "StorageOptimization"])
    ];
}
