using System.Text.Json.Serialization;
using Meridian.Contracts.Workstation;
using Meridian.Infrastructure.Contracts;
using Meridian.Strategies.Services;

namespace Meridian.Ui.Shared.Serialization;

/// <summary>
/// Source-generated <see cref="JsonSerializerContext"/> for workstation operations continuity contracts.
/// Per ADR-014, endpoint serialization must use source-generated metadata for these payloads.
/// </summary>
[ImplementsAdr("ADR-014", "Source-generated JSON context for workstation operations continuity contracts")]
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    PropertyNameCaseInsensitive = true,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(OperationsWorkflowStatusDto))]
[JsonSerializable(typeof(OperationsGateStatusDto))]
[JsonSerializable(typeof(OperationsGateKeyDto))]
[JsonSerializable(typeof(OperationsBrokerIntakeStateDto))]
[JsonSerializable(typeof(OperationsSecurityMasterStateDto))]
[JsonSerializable(typeof(OperationsLedgerPostingStateDto))]
[JsonSerializable(typeof(OperationsReconciliationStateDto))]
[JsonSerializable(typeof(OperationsReconciliationLaneStatusDto))]
[JsonSerializable(typeof(OperationsApprovalStateDto))]
[JsonSerializable(typeof(OperationsStartWorkflowRequestDto))]
[JsonSerializable(typeof(OperationsTransitionRequestDto))]
[JsonSerializable(typeof(OperationsSecurityMasterOverrideApprovalRequestDto))]
[JsonSerializable(typeof(OperationsGatePostureRequestDto))]
[JsonSerializable(typeof(OperationsSecurityMasterResolveRequestDto))]
[JsonSerializable(typeof(OperationsLedgerDraftRequestDto))]
[JsonSerializable(typeof(OperationsLedgerValidationRequestDto))]
[JsonSerializable(typeof(OperationsLedgerPostRequestDto))]
[JsonSerializable(typeof(OperationsLedgerJournalCandidateDto))]
[JsonSerializable(typeof(OperationsLedgerJournalLineDto))]
[JsonSerializable(typeof(OperationsJournalEntryMetadataDto))]
[JsonSerializable(typeof(OperationsReconciliationRunRequestDto))]
[JsonSerializable(typeof(OperationsAssignBreakCaseRequestDto))]
[JsonSerializable(typeof(OperationsResolveBreakCaseRequestDto))]
[JsonSerializable(typeof(OperationsSubmitApprovalRequestDto))]
[JsonSerializable(typeof(OperationsApprovalDecisionRequestDto))]
[JsonSerializable(typeof(OperationsRejectWorkflowRequestDto))]
[JsonSerializable(typeof(OperationsCloseWorkflowRequestDto))]
[JsonSerializable(typeof(OperationsReopenWorkflowRequestDto))]
[JsonSerializable(typeof(OperationsApprovalPolicyMatrixDto))]
[JsonSerializable(typeof(OperationsApprovalPolicyMatrixRowDto))]
[JsonSerializable(typeof(IReadOnlyList<OperationsApprovalPolicyMatrixRowDto>))]
[JsonSerializable(typeof(OperationsApprovalPolicyRuleUpsertRequestDto))]
[JsonSerializable(typeof(OperationsApprovalPolicyRuleUpsertResultDto))]
[JsonSerializable(typeof(OperationsApprovalPolicyRuleAuditEventDto))]
[JsonSerializable(typeof(OperationsCloseCalendarDto))]
[JsonSerializable(typeof(OperationsCloseCalendarItemDto))]
[JsonSerializable(typeof(IReadOnlyList<OperationsCloseCalendarItemDto>))]
[JsonSerializable(typeof(OperationsCloseCalendarItemUpsertRequestDto))]
[JsonSerializable(typeof(OperationsCloseCalendarItemUpsertResultDto))]
[JsonSerializable(typeof(OperationsCloseCalendarItemAuditEventDto))]
[JsonSerializable(typeof(OperationsTransitionResultDto))]
[JsonSerializable(typeof(OperationsContinuityWorkflowDto))]
[JsonSerializable(typeof(IReadOnlyList<OperationsContinuityWorkflowDto>))]
[JsonSerializable(typeof(OperationsContinuityWorkflowSummaryDto))]
[JsonSerializable(typeof(IReadOnlyList<OperationsContinuityWorkflowSummaryDto>))]
[JsonSerializable(typeof(OperationsGateDto))]
[JsonSerializable(typeof(IReadOnlyList<OperationsGateDto>))]
[JsonSerializable(typeof(OperationsTimelineEntryDto))]
[JsonSerializable(typeof(IReadOnlyList<OperationsTimelineEntryDto>))]
[JsonSerializable(typeof(OperationsWorkflowAuditDto))]
[JsonSerializable(typeof(OperationsBreakCaseDto))]
[JsonSerializable(typeof(IReadOnlyList<OperationsBreakCaseDto>))]
[JsonSerializable(typeof(OperationsDashboardSummaryDto))]
[JsonSerializable(typeof(OperationsDashboardMetricDto))]
[JsonSerializable(typeof(IReadOnlyList<OperationsDashboardMetricDto>))]
[JsonSerializable(typeof(OperationsEvidencePackageSummaryDto))]
[JsonSerializable(typeof(IReadOnlyList<OperationsEvidencePackageSummaryDto>))]
[JsonSerializable(typeof(OperationsReconciliationLaneSummaryDto))]
[JsonSerializable(typeof(IReadOnlyList<OperationsReconciliationLaneSummaryDto>))]
[JsonSerializable(typeof(OperationsApprovalDto))]
[JsonSerializable(typeof(IReadOnlyList<OperationsApprovalDto>))]
[JsonSerializable(typeof(OperationsLedgerPreviewDto))]
[JsonSerializable(typeof(OperationsReportPackReadinessDto))]
[JsonSerializable(typeof(OperationsAccountingRecordSummaryDto))]
[JsonSerializable(typeof(OperationsAccountingRecordEvidenceCategoryDto))]
[JsonSerializable(typeof(IReadOnlyList<OperationsAccountingRecordEvidenceCategoryDto>))]
[JsonSerializable(typeof(FundAuditEvidenceCategoryKeyDto))]
[JsonSerializable(typeof(FundAuditEvidenceCategorySummaryDto))]
[JsonSerializable(typeof(IReadOnlyList<FundAuditEvidenceCategorySummaryDto>))]
[JsonSerializable(typeof(FundAuditPackReadinessDto))]
[JsonSerializable(typeof(OperationsClosePackagePublicationDto))]
[JsonSerializable(typeof(EvidenceDocumentClassificationDto))]
[JsonSerializable(typeof(EvidenceExtractionStatusDto))]
[JsonSerializable(typeof(EvidenceDocumentLinkKindDto))]
[JsonSerializable(typeof(EvidenceDocumentReviewStatusDto))]
[JsonSerializable(typeof(EvidenceDocumentIntakeSourceKindDto))]
[JsonSerializable(typeof(EvidenceDocumentDto))]
[JsonSerializable(typeof(IReadOnlyList<EvidenceDocumentDto>))]
[JsonSerializable(typeof(EvidenceDocumentLinkDto))]
[JsonSerializable(typeof(IReadOnlyList<EvidenceDocumentLinkDto>))]
[JsonSerializable(typeof(EvidenceDocumentReviewStateDto))]
[JsonSerializable(typeof(EvidenceDocumentAuditEventDto))]
[JsonSerializable(typeof(IReadOnlyList<EvidenceDocumentAuditEventDto>))]
[JsonSerializable(typeof(EvidenceRequestDto))]
[JsonSerializable(typeof(IReadOnlyList<EvidenceRequestDto>))]
[JsonSerializable(typeof(EvidenceManifestDto))]
[JsonSerializable(typeof(EvidenceDocumentIntakeSourceDto))]
[JsonSerializable(typeof(EvidenceDocumentExtractionRequestDto))]
[JsonSerializable(typeof(EvidenceDocumentExtractionResultDto))]
[JsonSerializable(typeof(EvidenceVaultIdentityDto))]
[JsonSerializable(typeof(EvidenceVaultArtifactDto))]
[JsonSerializable(typeof(EvidenceVaultDocumentQueryDto))]
[JsonSerializable(typeof(EvidenceVaultDocumentEntryDto))]
[JsonSerializable(typeof(IReadOnlyList<EvidenceVaultDocumentEntryDto>))]
[JsonSerializable(typeof(EvidenceVaultDocumentReviewRequestDto))]
[JsonSerializable(typeof(EvidenceVaultDocumentReviewResponseDto))]
[JsonSerializable(typeof(EvidenceVaultIntakeRequestDto))]
[JsonSerializable(typeof(EvidenceVaultIntakeResponseDto))]
[JsonSerializable(typeof(IngestionOperationsSnapshotDto))]
[JsonSerializable(typeof(IngestionOperationDetailDto))]
[JsonSerializable(typeof(IngestionOperationActionRequestDto))]
[JsonSerializable(typeof(IngestionOperationActionResultDto))]
[JsonSerializable(typeof(StorageAssuranceSnapshotDto))]
[JsonSerializable(typeof(StorageMaintenancePreviewRequestDto))]
[JsonSerializable(typeof(StorageMaintenancePreviewDto))]
[JsonSerializable(typeof(StorageMaintenanceCommandRequestDto))]
[JsonSerializable(typeof(StorageMaintenanceResultDto))]
[JsonSerializable(typeof(OperationsCloseReadinessDto))]
[JsonSerializable(typeof(OperationsCloseReadinessComponentDto))]
[JsonSerializable(typeof(IReadOnlyList<OperationsCloseReadinessComponentDto>))]
[JsonSerializable(typeof(OperationsCloseReadinessBlockerDto))]
[JsonSerializable(typeof(IReadOnlyList<OperationsCloseReadinessBlockerDto>))]
[JsonSerializable(typeof(PrivateCapitalCloseCockpitDto))]
[JsonSerializable(typeof(PrivateCapitalCloseCockpitLaneDto))]
[JsonSerializable(typeof(IReadOnlyList<PrivateCapitalCloseCockpitLaneDto>))]
[JsonSerializable(typeof(PrivateCapitalCloseCockpitWorkflowDto))]
[JsonSerializable(typeof(IReadOnlyList<PrivateCapitalCloseCockpitWorkflowDto>))]
[JsonSerializable(typeof(PrivateCapitalCloseCockpitApprovalDto))]
[JsonSerializable(typeof(IReadOnlyList<PrivateCapitalCloseCockpitApprovalDto>))]
[JsonSerializable(typeof(PrivateCapitalNavSupportComponentDto))]
[JsonSerializable(typeof(IReadOnlyList<PrivateCapitalNavSupportComponentDto>))]
[JsonSerializable(typeof(PrivateCapitalShadowNavTieOutDto))]
[JsonSerializable(typeof(PrivateCapitalNavSupportPackageDto))]
[JsonSerializable(typeof(IReadOnlyList<PrivateCapitalNavSupportPackageDto>))]
[JsonSerializable(typeof(OperationsWorkflowBlockerDto))]
[JsonSerializable(typeof(IReadOnlyList<OperationsWorkflowBlockerDto>))]
[JsonSerializable(typeof(OperationsNextActionDto))]
[JsonSerializable(typeof(IReadOnlyList<OperationsNextActionDto>))]
[JsonSerializable(typeof(OperationsEvidenceLinkDto))]
[JsonSerializable(typeof(IReadOnlyList<OperationsEvidenceLinkDto>))]
[JsonSerializable(typeof(ReconciliationBreakQueueItem))]
[JsonSerializable(typeof(IReadOnlyList<ReconciliationBreakQueueItem>))]
[JsonSerializable(typeof(ReconciliationBreakQueueAuditEvent))]
[JsonSerializable(typeof(IReadOnlyList<ReconciliationBreakQueueAuditEvent>))]
[JsonSerializable(typeof(ReconciliationCaseworkCommand))]
[JsonSerializable(typeof(ReconciliationBulkCaseworkRequest))]
[JsonSerializable(typeof(ReconciliationBulkCaseworkResult))]
[JsonSerializable(typeof(ReconciliationCaseComment))]
[JsonSerializable(typeof(IReadOnlyList<ReconciliationCaseComment>))]
[JsonSerializable(typeof(ReconciliationTaxonomySnapshot))]
[JsonSerializable(typeof(ReconciliationCaseValidationProblem))]
internal sealed partial class WorkstationOperationsJsonContext : JsonSerializerContext;
