using System;
using System.Threading;
using System.Threading.Tasks;
using Meridian.Contracts.SecurityMaster;
using Meridian.Ui.Services;
using WpfServices = Meridian.Wpf.Services;

namespace Meridian.Wpf.ViewModels;

/// <summary>
/// ViewModel for deactivating a security in the Security Master.
/// Uses <see cref="ISecurityMasterService"/> directly for in-process deactivation.
/// </summary>
public sealed partial class SecurityMasterDeactivateViewModel : BindableBase
{
    private readonly WpfServices.LoggingService _loggingService;
    private readonly WpfServices.NotificationService _notificationService;
    private readonly ISecurityMasterService _service;
    private readonly WpfServices.IDesktopMutationAuthorization? _mutationAuthorization;

    // ── Bindable properties ─────────────────────────────────────────────────
    [ObservableProperty] private string _securityName = string.Empty;
    [ObservableProperty] private Guid _securityId;
    [ObservableProperty] private long _version;
    [ObservableProperty] private string _reason = string.Empty;
    [ObservableProperty] private bool _isBusy;
    [ObservableProperty] private string _statusText = string.Empty;

    // ── Commands ────────────────────────────────────────────────────────────
    // ConfirmCommand is generated by [RelayCommand] on ConfirmAsync (matches XAML binding).
    // CancelCommand is a simple lambda — kept as a manual IRelayCommand property.
    public IRelayCommand CancelCommand { get; }

    // ── Events ──────────────────────────────────────────────────────────────
    public event Action? CancelRequested;
    public event Action? DeactivateCompleted;

    // ── Constructor ─────────────────────────────────────────────────────────
    public SecurityMasterDeactivateViewModel(
        WpfServices.LoggingService loggingService,
        WpfServices.NotificationService notificationService,
        ISecurityMasterService service,
        WpfServices.IDesktopMutationAuthorization? mutationAuthorization = null)
    {
        _loggingService = loggingService;
        _notificationService = notificationService;
        _service = service;
        _mutationAuthorization = mutationAuthorization;

        CancelCommand = new RelayCommand(() => CancelRequested?.Invoke());
    }

    // ── Deactivation logic ──────────────────────────────────────────────────
    [RelayCommand]
    private async Task ConfirmAsync(CancellationToken ct)
    {
        // Deactivation reaches ISecurityMasterService in-process; the HTTP deactivate route requires
        // ModifySecurityMaster, so this dialog is held to the same grant and fails closed when
        // composed without an authorization seam.
        if (_mutationAuthorization is null ||
            !_mutationAuthorization.IsGranted(Meridian.Identity.Auth.UserPermission.ModifySecurityMaster))
        {
            const string refusal = "This operator is not permitted to modify the Security Master.";
            StatusText = refusal;
            _notificationService.ShowNotification("Security Master", refusal, NotificationType.Error);
            _loggingService.LogWarning("Security Master deactivation refused: this desktop session does not hold the ModifySecurityMaster permission.");
            return;
        }

        IsBusy = true;
        StatusText = "Deactivating…";

        try
        {
            var request = new DeactivateSecurityRequest(
                SecurityId: SecurityId,
                ExpectedVersion: Version,
                EffectiveTo: DateTimeOffset.UtcNow,
                SourceSystem: "WPF-UI",
                UpdatedBy: "User",
                SourceRecordId: null,
                Reason: string.IsNullOrWhiteSpace(Reason) ? "Deactivated via WPF UI" : Reason);

            await _service.DeactivateAsync(request, ct).ConfigureAwait(false);

            StatusText = "Security deactivated successfully.";
            DeactivateCompleted?.Invoke();
        }
        catch (OperationCanceledException)
        {
            StatusText = "Deactivation cancelled.";
        }
        catch (Exception ex)
        {
            _loggingService.LogError("Security Master deactivation failed", ex);
            StatusText = "Deactivation failed.";
            _notificationService.ShowNotification(
                "Security Master",
                "Failed to deactivate security.",
                NotificationType.Error);
        }
        finally
        {
            IsBusy = false;
        }
    }
}
