using System;
using System.Collections.ObjectModel;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Meridian.Contracts.SecurityMaster;
using Meridian.Ui.Services;
using WpfServices = Meridian.Wpf.Services;
using static Meridian.Contracts.Text.TextPrimitives;

namespace Meridian.Wpf.ViewModels;

/// <summary>
/// ViewModel for creating or editing a security in the Security Master.
/// Uses <see cref="ISecurityMasterService"/> directly for in-process create and amend operations.
/// </summary>
public sealed partial class SecurityMasterEditViewModel : BindableBase
{
    private readonly WpfServices.LoggingService _loggingService;
    private readonly WpfServices.NotificationService _notificationService;
    private readonly ISecurityMasterService _service;
    private readonly WpfServices.IDesktopActorSource? _actorSource;
    private readonly WpfServices.IDesktopMutationAuthorization? _mutationAuthorization;
    private JsonElement _assetSpecificTerms;

    private static readonly IReadOnlyList<string> AssetClassesList = SecurityAssetClassCatalog.AssetClasses;
    private static readonly IReadOnlyDictionary<SecurityIdentifierKind, string> IdentifierKindDisplayNames =
        new Dictionary<SecurityIdentifierKind, string>
        {
            [SecurityIdentifierKind.Ticker] = "Ticker",
            [SecurityIdentifierKind.Isin] = "ISIN",
            [SecurityIdentifierKind.Cusip] = "CUSIP",
            [SecurityIdentifierKind.Sedol] = "SEDOL",
            [SecurityIdentifierKind.Figi] = "FIGI",
            [SecurityIdentifierKind.OccOptionSymbol] = "OccOptionSymbol",
            [SecurityIdentifierKind.ProviderSymbol] = "ProviderSymbol",
            [SecurityIdentifierKind.InternalCode] = "InternalCode",
            [SecurityIdentifierKind.Lei] = "LEI",
            [SecurityIdentifierKind.PermId] = "PermId",
            [SecurityIdentifierKind.Bbgid] = "BBGID",
            [SecurityIdentifierKind.Wkn] = "WKN",
            [SecurityIdentifierKind.Valoren] = "Valoren",
            [SecurityIdentifierKind.PermTicker] = "PermTicker",
            [SecurityIdentifierKind.Ric] = "RIC",
            [SecurityIdentifierKind.Cik] = "CIK"
        };
    private static readonly IReadOnlyDictionary<string, SecurityIdentifierKind> IdentifierKindLookup =
        IdentifierKindDisplayNames.ToDictionary(static pair => pair.Value, static pair => pair.Key, StringComparer.OrdinalIgnoreCase);

    // ── Bindable properties ─────────────────────────────────────────────────
    [ObservableProperty] private string _displayName = string.Empty;
    [ObservableProperty] private string _assetClass = "Equity";
    [ObservableProperty] private string _currency = "USD";
    [ObservableProperty] private string _exchange = string.Empty;
    [ObservableProperty] private string _issuerName = string.Empty;
    [ObservableProperty] private string _primaryIdentifierKind = "Ticker";
    [ObservableProperty] private string _primaryIdentifierValue = string.Empty;
    [ObservableProperty] private bool _isEditMode;
    [ObservableProperty] private Guid? _editingSecurityId;
    [ObservableProperty] private long? _editingVersion;
    [ObservableProperty] private string _statusText = string.Empty;
    [ObservableProperty] private bool _isBusy;
    [ObservableProperty] private ObservableCollection<string> _validationErrors = [];

    public bool HasErrors => ValidationErrors.Count > 0;

    public IReadOnlyList<string> AssetClasses => AssetClassesList;
    public IReadOnlyList<string> IdentifierKinds => GetIdentifierKindsForAssetClass(AssetClass);
    public bool CanChangeAssetClass => !IsEditMode && !IsBusy;
    public bool CanEditPrimaryIdentifier => !IsEditMode && !IsBusy;
    public bool SupportsSelectedAssetClassCreateWorkflow => SecurityAssetClassCatalog.GetOrDefault(AssetClass).SupportsBasicCreateWorkflow;
    public string AssetClassEditabilityHint => IsEditMode
        ? "Asset class is fixed for existing records. Create a new security when the economic instrument class changes."
        : "Choose the canonical Security Master asset class.";
    public string PrimaryIdentifierEditabilityHint => IsEditMode
        ? "Primary identifiers for existing records stay read-only until a dedicated identifier-rotation workflow is added."
        : "Choose the canonical identifier Meridian should treat as primary at creation time.";

    // ── Commands ────────────────────────────────────────────────────────────
    // SaveCommand is generated by [RelayCommand] on SaveAsync (matches XAML binding).
    // CancelCommand is a simple lambda — kept as a manual IRelayCommand property
    // because [RelayCommand] cannot wrap a closure.
    public IRelayCommand CancelCommand { get; }

    // ── Events ──────────────────────────────────────────────────────────────
    public event Action? CancelRequested;
    public event Action<SecurityDetailDto>? SaveCompleted;

    // ── Constructor ─────────────────────────────────────────────────────────
    public SecurityMasterEditViewModel(
        WpfServices.LoggingService loggingService,
        WpfServices.NotificationService notificationService,
        ISecurityMasterService service,
        WpfServices.IDesktopActorSource? actorSource = null,
        WpfServices.IDesktopMutationAuthorization? mutationAuthorization = null)
    {
        _loggingService = loggingService;
        _notificationService = notificationService;
        _service = service;
        _actorSource = actorSource;
        _mutationAuthorization = mutationAuthorization;
        _assetSpecificTerms = CreateAssetSpecificTermsTemplate("Equity");

        CancelCommand = new RelayCommand(() => CancelRequested?.Invoke());
    }

    /// <summary>
    /// Authorization gate for this dialog's create and amend paths, which reach
    /// <see cref="ISecurityMasterService"/> in-process with no endpoint filter in between. Every
    /// HTTP route that mutates the golden record requires
    /// <see cref="Meridian.Identity.Auth.UserPermission.ModifySecurityMaster"/>; the save is held to
    /// the same grant, and fails closed when composed without an authorization seam. Checked before
    /// the actor is resolved — attribution and authorization are separate properties, and recording
    /// a named operator on a write the operator had no right to make would be worse than refusing.
    /// </summary>
    private bool IsMutationGranted()
        => _mutationAuthorization is not null &&
           _mutationAuthorization.IsGranted(Meridian.Identity.Auth.UserPermission.ModifySecurityMaster);

    private void ReportUnauthorizedWrite()
    {
        const string message = "This operator is not permitted to modify the Security Master.";
        StatusText = message;
        _notificationService.ShowNotification("Security Master", message, NotificationType.Error);
        _loggingService.LogWarning("Security Master save refused: this desktop session does not hold the ModifySecurityMaster permission.");
    }

    /// <summary>
    /// Resolves the operator to record as the author of this write. Fails closed: rather than
    /// stamping a placeholder into an audit field, a save with no authenticated desktop session is
    /// refused, so the golden record never carries a write it cannot attribute.
    /// </summary>
    private bool TryResolveActor(out string actor)
    {
        if (_actorSource is not null && _actorSource.TryGetAuthenticatedActor(out actor))
        {
            return true;
        }

        actor = string.Empty;
        return false;
    }

    // ── Initialization ──────────────────────────────────────────────────────
    public static SecurityMasterEditViewModel CreateNew(
        WpfServices.LoggingService loggingService,
        WpfServices.NotificationService notificationService,
        ISecurityMasterService service,
        WpfServices.IDesktopActorSource? actorSource = null,
        WpfServices.IDesktopMutationAuthorization? mutationAuthorization = null)
    {
        return new SecurityMasterEditViewModel(loggingService, notificationService, service, actorSource, mutationAuthorization)
        {
            IsEditMode = false,
            Currency = "USD",
            AssetClass = "Equity",
            PrimaryIdentifierKind = FormatIdentifierKind(SecurityIdentifierKind.Ticker),
            DisplayName = string.Empty,
            Exchange = string.Empty,
            IssuerName = string.Empty,
            PrimaryIdentifierValue = string.Empty
        };
    }

    public void LoadForEdit(SecurityDetailDto dto)
    {
        IsEditMode = true;
        EditingSecurityId = dto.SecurityId;
        EditingVersion = dto.Version;
        DisplayName = dto.DisplayName;
        AssetClass = dto.AssetClass;
        Currency = dto.Currency;
        Exchange = ReadJsonString(dto.CommonTerms, "exchange");
        IssuerName = ReadJsonString(dto.CommonTerms, "issuerName");
        PrimaryIdentifierValue = dto.Identifiers
            .FirstOrDefault(i => i.IsPrimary)?.Value ?? string.Empty;
        PrimaryIdentifierKind = dto.Identifiers
            .FirstOrDefault(i => i.IsPrimary) is { } primaryIdentifier
            ? FormatIdentifierKind(primaryIdentifier.Kind)
            : FormatIdentifierKind(SecurityIdentifierKind.Ticker);
        _assetSpecificTerms = dto.AssetSpecificTerms.Clone();
        StatusText = string.Empty;
        ClearValidationErrors();
    }

    // ── Save logic ──────────────────────────────────────────────────────────
    [RelayCommand]
    private async Task SaveAsync(CancellationToken ct)
    {
        ClearValidationErrors();

        if (!IsMutationGranted())
        {
            ReportUnauthorizedWrite();
            return;
        }

        IsBusy = true;
        StatusText = "Saving…";

        try
        {
            SecurityDetailDto? result;

            if (IsEditMode && EditingSecurityId.HasValue && EditingVersion.HasValue)
            {
                result = await AmendSecurityAsync(ct);
            }
            else
            {
                if (!SupportsSelectedAssetClassCreateWorkflow)
                {
                    AddValidationError($"The current basic editor can create '{AssetClass}' records only after a richer asset-specific workflow is added. Use import/API workflows for now.");
                    StatusText = "Create blocked. Select a supported asset class or use an import workflow.";
                    return;
                }

                result = await CreateSecurityAsync(ct);
            }

            if (result is not null)
            {
                StatusText = "Security saved successfully.";
                SaveCompleted?.Invoke(result);
            }
        }
        catch (OperationCanceledException)
        {
            StatusText = "Save cancelled.";
        }
        catch (Exception ex)
        {
            _loggingService.LogError("Security Master save failed", ex);
            StatusText = "Save failed. Check the validation errors.";
            _notificationService.ShowNotification("Security Master", "Save failed.", NotificationType.Error);
        }
        finally
        {
            IsBusy = false;
        }
    }

    private async Task<SecurityDetailDto?> CreateSecurityAsync(CancellationToken ct)
    {
        if (!TryResolveActor(out var actor))
        {
            ReportUnattributableWrite();
            return null;
        }

        var identifiers = new List<SecurityIdentifierDto>
        {
            new(
                Kind: ParseIdentifierKind(PrimaryIdentifierKind),
                Value: PrimaryIdentifierValue,
                IsPrimary: true,
                ValidFrom: DateTimeOffset.UtcNow)
        };

        var request = new CreateSecurityRequest(
            SecurityId: Guid.NewGuid(),
            AssetClass: AssetClass,
            CommonTerms: BuildCommonTermsJson(),
            AssetSpecificTerms: CreateAssetSpecificTermsTemplate(AssetClass),
            Identifiers: identifiers,
            EffectiveFrom: DateTimeOffset.UtcNow,
            // SourceSystem identifies the originating SYSTEM for conflict precedence, so it stays a
            // constant for this lane; UpdatedBy is the audit actor and must be the real operator.
            SourceSystem: "WPF-UI",
            UpdatedBy: actor,
            SourceRecordId: null,
            Reason: "Created via WPF UI");

        return await _service.CreateAsync(request, ct).ConfigureAwait(false);
    }

    private void ReportUnattributableWrite()
    {
        const string message = "Sign in before saving: Security Master writes are recorded against the signed-in operator.";
        StatusText = message;
        _notificationService.ShowNotification("Security Master", message, NotificationType.Error);
        _loggingService.LogWarning("Security Master save refused: no authenticated desktop operator to attribute the write to.");
    }

    private async Task<SecurityDetailDto?> AmendSecurityAsync(CancellationToken ct)
    {
        if (!TryResolveActor(out var actor))
        {
            ReportUnattributableWrite();
            return null;
        }

        var request = new AmendSecurityTermsRequest(
            SecurityId: EditingSecurityId!.Value,
            ExpectedVersion: EditingVersion!.Value,
            CommonTerms: BuildCommonTermsJson(),
            AssetSpecificTermsPatch: _assetSpecificTerms,
            IdentifiersToAdd: [],
            IdentifiersToExpire: [],
            EffectiveFrom: DateTimeOffset.UtcNow,
            SourceSystem: "WPF-UI",
            UpdatedBy: actor,
            SourceRecordId: null,
            Reason: "Amended via WPF UI");

        return await _service.AmendTermsAsync(request, ct).ConfigureAwait(false);
    }

    partial void OnAssetClassChanged(string value)
    {
        if (!IsEditMode)
        {
            _assetSpecificTerms = CreateAssetSpecificTermsTemplate(value);
        }

        var identifierKinds = IdentifierKinds;
        if (!identifierKinds.Contains(PrimaryIdentifierKind, StringComparer.OrdinalIgnoreCase))
        {
            PrimaryIdentifierKind = identifierKinds.FirstOrDefault() ?? FormatIdentifierKind(SecurityIdentifierKind.Ticker);
        }

        RaisePropertyChanged(nameof(IdentifierKinds));
        RaisePropertyChanged(nameof(SupportsSelectedAssetClassCreateWorkflow));
    }

    partial void OnIsBusyChanged(bool value)
    {
        RaisePropertyChanged(nameof(CanChangeAssetClass));
        RaisePropertyChanged(nameof(CanEditPrimaryIdentifier));
    }

    partial void OnIsEditModeChanged(bool value)
    {
        RaisePropertyChanged(nameof(CanChangeAssetClass));
        RaisePropertyChanged(nameof(CanEditPrimaryIdentifier));
        RaisePropertyChanged(nameof(AssetClassEditabilityHint));
        RaisePropertyChanged(nameof(PrimaryIdentifierEditabilityHint));
    }

    private JsonElement BuildCommonTermsJson()
    {
        var payload = new Dictionary<string, object?>
        {
            ["displayName"] = DisplayName,
            ["currency"] = Currency,
            ["exchange"] = NormalizeOptional(Exchange),
            ["issuerName"] = NormalizeOptional(IssuerName)
        };

        return JsonSerializer.SerializeToElement(payload);
    }

    private static JsonElement CreateAssetSpecificTermsTemplate(string assetClass)
        => JsonSerializer.SerializeToElement(new Dictionary<string, object?>
        {
            ["schemaVersion"] = SecurityMasterSchemaVersions.LegacyAssetSpecificTerms,
            ["classification"] = string.Equals(assetClass, "Equity", StringComparison.OrdinalIgnoreCase) ? "Common" : null
        });

    private static string ReadJsonString(JsonElement element, string propertyName)
        => element.TryGetProperty(propertyName, out var property) && property.ValueKind == JsonValueKind.String
            ? property.GetString() ?? string.Empty
            : string.Empty;

    private static IReadOnlyList<string> GetIdentifierKindsForAssetClass(string assetClass)
        => SecurityAssetClassCatalog.GetPreferredIdentifierKinds(assetClass)
            .Select(FormatIdentifierKind)
            .ToArray();

    private static string FormatIdentifierKind(SecurityIdentifierKind kind)
        => IdentifierKindDisplayNames.TryGetValue(kind, out var displayName)
            ? displayName
            : kind.ToString();

    private static SecurityIdentifierKind ParseIdentifierKind(string displayName)
        => IdentifierKindLookup.TryGetValue(displayName, out var kind)
            ? kind
            : Enum.TryParse<SecurityIdentifierKind>(displayName, ignoreCase: true, out var parsedKind)
                ? parsedKind
                : SecurityIdentifierKind.Ticker;

    private void ClearValidationErrors()
    {
        ValidationErrors.Clear();
        RaisePropertyChanged(nameof(HasErrors));
    }

    private void AddValidationError(string message)
    {
        ValidationErrors.Add(message);
        RaisePropertyChanged(nameof(HasErrors));
    }
}
