using System;
using System.Threading;
using System.Threading.Tasks;
using Meridian.Contracts.SecurityMaster;
using Meridian.Identity.Auth;
using Meridian.Ui.Services;
using WpfServices = Meridian.Wpf.Services;

namespace Meridian.Wpf.ViewModels;

/// <summary>
/// ViewModel for deactivating a security in the Security Master.
/// Uses <see cref="ISecurityMasterService"/> directly for in-process deactivation.
/// </summary>
public sealed partial class SecurityMasterDeactivateViewModel : BindableBase
{
    private readonly WpfServices.LoggingService _loggingService;
    private readonly WpfServices.NotificationService _notificationService;
    private readonly ISecurityMasterService _service;
    private readonly WpfServices.IDesktopAuthorizationSource? _operatorContext;
    private readonly WpfServices.IDesktopMutationAuthorization? _mutationAuthorization;

    // ── Bindable properties ─────────────────────────────────────────────────
    [ObservableProperty] private string _securityName = string.Empty;
    [ObservableProperty] private Guid _securityId;
    [ObservableProperty] private long _version;
    [ObservableProperty] private string _reason = string.Empty;
    [ObservableProperty] private bool _isBusy;
    [ObservableProperty] private string _statusText = string.Empty;

    // ── Commands ────────────────────────────────────────────────────────────
    // ConfirmCommand is generated by [RelayCommand] on ConfirmAsync (matches XAML binding).
    // CancelCommand is a simple lambda — kept as a manual IRelayCommand property.
    public IRelayCommand CancelCommand { get; }

    // ── Events ──────────────────────────────────────────────────────────────
    public event Action? CancelRequested;
    public event Action? DeactivateCompleted;

    // ── Constructor ─────────────────────────────────────────────────────────
    public SecurityMasterDeactivateViewModel(
        WpfServices.LoggingService loggingService,
        WpfServices.NotificationService notificationService,
        ISecurityMasterService service,
        WpfServices.IDesktopAuthorizationSource? operatorContext = null,
        WpfServices.IDesktopMutationAuthorization? mutationAuthorization = null)
    {
        _loggingService = loggingService;
        _notificationService = notificationService;
        _service = service;
        _operatorContext = operatorContext;
        _mutationAuthorization = mutationAuthorization;

        CancelCommand = new RelayCommand(() => CancelRequested?.Invoke());
    }

    // ── Deactivation logic ──────────────────────────────────────────────────
    private bool CanConfirm()
        => !IsBusy && IsMutationPermitted() && TryAuthorizeMutation(out _);

    [RelayCommand(CanExecute = nameof(CanConfirm))]
    private async Task ConfirmAsync(CancellationToken ct)
    {
        // Deactivation reaches ISecurityMasterService in-process; the HTTP deactivate route requires
        // ModifySecurityMaster, so this dialog is held to the same grant and fails closed when
        // composed without any authorization seam.
        if (!IsMutationPermitted())
        {
            ReportForbiddenMutation();
            return;
        }

        if (!TryAuthorizeMutation(out var actor))
        {
            ReportUnauthorizedWrite();
            return;
        }

        IsBusy = true;
        StatusText = "Deactivating…";

        try
        {
            var request = new DeactivateSecurityRequest(
                SecurityId: SecurityId,
                ExpectedVersion: Version,
                EffectiveTo: DateTimeOffset.UtcNow,
                SourceSystem: "WPF-UI",
                UpdatedBy: actor,
                SourceRecordId: null,
                Reason: string.IsNullOrWhiteSpace(Reason) ? "Deactivated via WPF UI" : Reason);

            await _service.DeactivateAsync(request, ct).ConfigureAwait(false);

            StatusText = "Security deactivated successfully.";
            DeactivateCompleted?.Invoke();
        }
        catch (OperationCanceledException)
        {
            StatusText = "Deactivation cancelled.";
        }
        catch (Exception ex)
        {
            _loggingService.LogError("Security Master deactivation failed", ex);
            StatusText = "Deactivation failed.";
            _notificationService.ShowNotification(
                "Security Master",
                "Failed to deactivate security.",
                NotificationType.Error);
        }
        finally
        {
            IsBusy = false;
        }
    }

    /// <summary>
    /// Whether the host posture permits a Security Master write at all. When the mutation seam is
    /// composed it decides (so a credential-free host whose MDC_ANONYMOUS_ROLE names a read-only
    /// role refuses); when only the operator seam is composed, <see cref="TryAuthorizeMutation"/>
    /// carries the whole decision; with neither seam nobody checked the write is allowed, so it
    /// refuses rather than defaulting open.
    /// </summary>
    private bool IsMutationPermitted()
    {
        if (_mutationAuthorization is not null)
        {
            return _mutationAuthorization.IsGranted(UserPermission.ModifySecurityMaster);
        }

        return _operatorContext is not null;
    }

    /// <summary>
    /// Resolves the operator to record the deactivation against. When an operator seam is composed
    /// the write must be attributable to an authorized operator; a dialog composed with only the
    /// posture seam keeps the pre-existing shell attribution for that composition.
    /// </summary>
    private bool TryAuthorizeMutation(out string actor)
    {
        if (_operatorContext is not null)
        {
            if (_operatorContext.TryAuthorize(UserPermission.ModifySecurityMaster, out actor))
            {
                return true;
            }

            actor = string.Empty;
            return false;
        }

        if (_mutationAuthorization is not null)
        {
            actor = "User";
            return true;
        }

        actor = string.Empty;
        return false;
    }

    private void ReportForbiddenMutation()
    {
        const string refusal = "This operator is not permitted to modify the Security Master.";
        StatusText = refusal;
        _notificationService.ShowNotification("Security Master", refusal, NotificationType.Error);
        _loggingService.LogWarning("Security Master deactivation refused: this desktop session does not hold the ModifySecurityMaster permission.");
    }

    private void ReportUnauthorizedWrite()
    {
        const string message = "Sign in with Security Master edit permission before deactivating a security.";
        StatusText = message;
        _notificationService.ShowNotification("Security Master", message, NotificationType.Error);
        _loggingService.LogWarning("Security Master deactivation refused: the active desktop session does not grant ModifySecurityMaster or cannot name a valid actor.");
    }

    partial void OnIsBusyChanged(bool value)
        => ConfirmCommand.NotifyCanExecuteChanged();
}
