using System;
using System.Threading;
using System.Threading.Tasks;
using Meridian.Contracts.SecurityMaster;
using Meridian.Identity.Auth;
using Meridian.Ui.Services;
using WpfServices = Meridian.Wpf.Services;

namespace Meridian.Wpf.ViewModels;

/// <summary>
/// ViewModel for deactivating a security in the Security Master.
/// Uses <see cref="ISecurityMasterService"/> directly for in-process deactivation.
/// </summary>
public sealed partial class SecurityMasterDeactivateViewModel : BindableBase
{
    private readonly WpfServices.LoggingService _loggingService;
    private readonly WpfServices.NotificationService _notificationService;
    private readonly ISecurityMasterService _service;
    private readonly WpfServices.IDesktopAuthorizationSource? _operatorContext;

    // ── Bindable properties ─────────────────────────────────────────────────
    [ObservableProperty] private string _securityName = string.Empty;
    [ObservableProperty] private Guid _securityId;
    [ObservableProperty] private long _version;
    [ObservableProperty] private string _reason = string.Empty;
    [ObservableProperty] private bool _isBusy;
    [ObservableProperty] private string _statusText = string.Empty;

    // ── Commands ────────────────────────────────────────────────────────────
    // ConfirmCommand is generated by [RelayCommand] on ConfirmAsync (matches XAML binding).
    // CancelCommand is a simple lambda — kept as a manual IRelayCommand property.
    public IRelayCommand CancelCommand { get; }

    // ── Events ──────────────────────────────────────────────────────────────
    public event Action? CancelRequested;
    public event Action? DeactivateCompleted;

    // ── Constructor ─────────────────────────────────────────────────────────
    public SecurityMasterDeactivateViewModel(
        WpfServices.LoggingService loggingService,
        WpfServices.NotificationService notificationService,
        ISecurityMasterService service,
        WpfServices.IDesktopAuthorizationSource? operatorContext = null)
    {
        _loggingService = loggingService;
        _notificationService = notificationService;
        _service = service;
        _operatorContext = operatorContext;

        CancelCommand = new RelayCommand(() => CancelRequested?.Invoke());
    }

    // ── Deactivation logic ──────────────────────────────────────────────────
    private bool CanConfirm()
        => !IsBusy && TryAuthorizeMutation(out _);

    [RelayCommand(CanExecute = nameof(CanConfirm))]
    private async Task ConfirmAsync(CancellationToken ct)
    {
        if (!TryAuthorizeMutation(out var actor))
        {
            ReportUnauthorizedWrite();
            return;
        }

        IsBusy = true;
        StatusText = "Deactivating…";

        try
        {
            var request = new DeactivateSecurityRequest(
                SecurityId: SecurityId,
                ExpectedVersion: Version,
                EffectiveTo: DateTimeOffset.UtcNow,
                SourceSystem: "WPF-UI",
                UpdatedBy: actor,
                SourceRecordId: null,
                Reason: string.IsNullOrWhiteSpace(Reason) ? "Deactivated via WPF UI" : Reason);

            await _service.DeactivateAsync(request, ct).ConfigureAwait(false);

            StatusText = "Security deactivated successfully.";
            DeactivateCompleted?.Invoke();
        }
        catch (OperationCanceledException)
        {
            StatusText = "Deactivation cancelled.";
        }
        catch (Exception ex)
        {
            _loggingService.LogError("Security Master deactivation failed", ex);
            StatusText = "Deactivation failed.";
            _notificationService.ShowNotification(
                "Security Master",
                "Failed to deactivate security.",
                NotificationType.Error);
        }
        finally
        {
            IsBusy = false;
        }
    }

    private bool TryAuthorizeMutation(out string actor)
    {
        if (_operatorContext is not null &&
            _operatorContext.TryAuthorize(UserPermission.ModifySecurityMaster, out actor))
        {
            return true;
        }

        actor = string.Empty;
        return false;
    }

    private void ReportUnauthorizedWrite()
    {
        const string message = "Sign in with Security Master edit permission before deactivating a security.";
        StatusText = message;
        _notificationService.ShowNotification("Security Master", message, NotificationType.Error);
        _loggingService.LogWarning("Security Master deactivation refused: the active desktop session does not grant ModifySecurityMaster or cannot name a valid actor.");
    }

    partial void OnIsBusyChanged(bool value)
        => ConfirmCommand.NotifyCanExecuteChanged();
}
