using System;
using System.Collections.Generic;
using Meridian.Wpf.Models;

namespace Meridian.Wpf.ViewModels;

public sealed partial class SplitPaneViewModel : BindableBase
{
    // Private-setter properties kept as manual — the generator only produces public setters.
    private PaneLayout _selectedLayout = PaneLayouts.Single;
    public PaneLayout SelectedLayout
    {
        get => _selectedLayout;
        private set => SetProperty(ref _selectedLayout, value);
    }

    private int _activePaneIndex;
    public int ActivePaneIndex
    {
        get => _activePaneIndex;
        private set => SetProperty(ref _activePaneIndex, value);
    }

    public IReadOnlyList<PaneLayout> Layouts => PaneLayouts.All;

    public event EventHandler<PaneLayout>? LayoutChanged;
    public event EventHandler<int>? ActivePaneChanged;

    // SelectLayoutCommand is generated by [RelayCommand] on SelectLayout (matches XAML binding).
    [RelayCommand]
    private void SelectLayout(PaneLayout? layout)
    {
        if (layout is null) return;
        SelectedLayout = layout;
        LayoutChanged?.Invoke(this, layout);
    }

    // SetActivePaneCommand is generated by [RelayCommand] on SetActivePane.
    [RelayCommand]
    private void SetActivePane(int? index)
    {
        if (index is null or < 0) return;
        ActivePaneIndex = index.Value;
        ActivePaneChanged?.Invoke(this, index.Value);
    }
}
