using FluentAssertions;
using Meridian.Contracts.Workstation;
using Meridian.Execution.Models;
using Meridian.Execution.Sdk;
using Meridian.Execution.Services;
using Meridian.Ledger;
using Meridian.Strategies.Promotions;
using Meridian.Ui.Shared.Services;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging.Abstractions;

namespace Meridian.Tests.Ui;

/// <summary>
/// Wave 2 Paper Trading Cockpit Acceptance Tests.
/// Validates the four acceptance gates required for the paper trading cockpit:
/// 1. Replay Confidence - Operators can verify a paper session and see evidence
/// 2. Session Persistence - Sessions survive restart with full history intact
/// 3. Risk Auditability - Control/risk outcomes are explainable from the cockpit
/// 4. Promotion Traceability - Promotion decisions have complete audit chains
/// </summary>
[Trait("Category", "Scenario")]
public sealed class Wave2PaperTradingCockpitAcceptanceTests
{
    // ---- GATE 1: REPLAY CONFIDENCE ----

    [Fact]
    public async Task ReplayConfidenceGate_OperatorCanVerifySessionWithExplicitEvidence()
    {
        // Arrange: Create a paper session with orders and fills
        await using var auditTrail = CreateAuditTrail(nameof(ReplayConfidenceGate_OperatorCanVerifySessionWithExplicitEvidence));
        var sessionService = new PaperSessionPersistenceService(
            NullLogger<PaperSessionPersistenceService>.Instance,
            auditTrail: auditTrail);

        var session = await sessionService.CreateSessionAsync(
            new CreatePaperSessionDto("strat-replay-test", "Replay Test", 100_000m));

        // Submit order and create fill
        await auditTrail.RecordAsync(
            category: "Order",
            action: "OrderSubmitted",
            outcome: "Accepted",
            actor: "operator",
            orderId: "order-1",
            correlationId: "corr-1");
        await sessionService.RecordOrderUpdateAsync(session.SessionId, new OrderState
        {
            OrderId = "order-1",
            Symbol = "AAPL",
            Side = OrderSide.Buy,
            Type = OrderType.Market,
            Quantity = 10,
            Status = Meridian.Execution.Sdk.OrderStatus.Accepted,
            CreatedAt = DateTimeOffset.UtcNow,
            LastUpdatedAt = DateTimeOffset.UtcNow
        });

        // Apply fill to portfolio
        var fill = new ExecutionFill
        {
            SessionId = session.SessionId,
            Symbol = "AAPL",
            Quantity = 10,
            FillPrice = 150.00m,
            FillType = FillType.Trade,
            FilledAt = DateTimeOffset.UtcNow
        };
        await sessionService.RecordPaperFillAsync(session.SessionId, fill);

        // Act: Verify replay with explicit evidence
        var verification = await sessionService.VerifyReplayAsync(
            session.SessionId,
            expectedFillCount: 1,
            expectedOrderCount: 1,
            ct: default);

        // Assert: Replay verification shows clear evidence
        verification.Should().NotBeNull();
        verification!.IsConsistent.Should().BeTrue("replay should match persisted state");
        verification.VerifiedFilledCount.Should().Be(1);
        verification.VerifiedOrderCount.Should().Be(1);
        var ledgerEntryCount = sessionService.GetLedger(session.SessionId)?.JournalEntryCount ?? 0;
        verification.VerifiedLedgerEntriesCount.Should().Be(
            ledgerEntryCount,
            "replay verification should include the ledger evidence generated by the fill path");
        verification.MismatchReasons.Should().BeEmpty("no mismatches found");
        verification.LastVerifiedAt.Should().BeCloseTo(DateTimeOffset.UtcNow, TimeSpan.FromSeconds(5));
    }

    [Fact]
    public async Task ReplayConfidenceGate_ShowsExplicitMismatchReasonsWhenReplayFails()
    {
        // Arrange
        await using var auditTrail = CreateAuditTrail(nameof(ReplayConfidenceGate_ShowsExplicitMismatchReasonsWhenReplayFails));
        var sessionService = new PaperSessionPersistenceService(
            NullLogger<PaperSessionPersistenceService>.Instance,
            auditTrail: auditTrail);

        var session = await sessionService.CreateSessionAsync(
            new CreatePaperSessionDto("strat-mismatch-test", "Mismatch Test", 100_000m));

        // Apply fill to portfolio
        var fill = new ExecutionFill
        {
            SessionId = session.SessionId,
            Symbol = "TSLA",
            Quantity = 5,
            FillPrice = 250.00m,
            FillType = FillType.Trade,
            FilledAt = DateTimeOffset.UtcNow
        };
        await sessionService.RecordPaperFillAsync(session.SessionId, fill);

        // Act: Verify with mismatched expected counts
        var verification = await sessionService.VerifyReplayAsync(
            session.SessionId,
            expectedFillCount: 2, // Expected 2, but only 1 applied
            expectedOrderCount: 1,
            ct: default);

        // Assert: Mismatch is reported with explicit reason
        verification.Should().NotBeNull();
        verification!.IsConsistent.Should().BeFalse("expected and actual counts don't match");
        verification.VerifiedFilledCount.Should().Be(1, "only one fill was applied");
        verification.MismatchReasons.Should().NotBeEmpty("mismatch reasons must be explicit");
        verification.MismatchReasons.Should().Contain(m =>
            m.Contains("fill") || m.Contains("count") || m.Contains("mismatch"),
            "reason should explain the fill count discrepancy");
    }

    [Fact]
    public async Task ReplayConfidenceGate_OperatorReadinessShowsReplayAsBlockingGateWhenMissing()
    {
        // Arrange: Create session but don't verify replay
        await using var provider = new ServiceCollection()
            .BuildServiceProvider();
        var readinessService = new TradingOperatorReadinessService(
            provider,
            NullLogger<TradingOperatorReadinessService>.Instance);

        // Act: Get readiness without verification
        var readiness = await readinessService.GetAsync();

        // Assert: Replay gate appears in work items as blocking
        readiness.WorkItems.Should()
            .ContainSingle(item => item.WorkItemId == "paper-session-missing")
            .Which.Tone.Should().Be(OperatorWorkItemToneDto.Critical);
    }

    // ---- GATE 2: SESSION PERSISTENCE ----

    [Fact]
    public async Task SessionPersistenceGate_SessionSurvivesRestartWithFullHistory()
    {
        // Arrange: Create session with history
        await using var auditTrail = CreateAuditTrail(nameof(SessionPersistenceGate_SessionSurvivesRestartWithFullHistory));
        var sessionService = new PaperSessionPersistenceService(
            NullLogger<PaperSessionPersistenceService>.Instance,
            auditTrail: auditTrail);

        var sessionDto = new CreatePaperSessionDto("strat-persist", "Persistence Test", 50_000m)
        {
            Symbols = ["AAPL", "MSFT", "GOOG"]
        };
        var originalSession = await sessionService.CreateSessionAsync(sessionDto);

        // Add order to history
        var orderRecord = new OrderState
        {
            OrderId = "order-persist-1",
            Symbol = "AAPL",
            Side = OrderSide.Buy,
            Type = OrderType.Limit,
            Quantity = 100,
            LimitPrice = 150.00m,
            Status = Meridian.Execution.Sdk.OrderStatus.Filled,
            CreatedAt = DateTimeOffset.UtcNow
        };
        await sessionService.RecordOrderUpdateAsync(originalSession.SessionId, orderRecord);

        // Add fill to history
        var fill = new ExecutionFill
        {
            SessionId = originalSession.SessionId,
            Symbol = "AAPL",
            Quantity = 100,
            FillPrice = 150.50m,
            FillType = FillType.Trade,
            FilledAt = DateTimeOffset.UtcNow
        };
        await sessionService.RecordPaperFillAsync(originalSession.SessionId, fill);

        // Act: Simulate restart by getting all sessions
        var allSessions = sessionService.GetSessions();
        var restoredSummary = allSessions.FirstOrDefault(s => s.SessionId == originalSession.SessionId);
        var restoredSession = restoredSummary is null ? null : sessionService.GetSession(restoredSummary.SessionId);

        // Assert: Session persisted with intact history
        restoredSession.Should().NotBeNull("session should be restored after restart");
        restoredSession!.Summary.StrategyId.Should().Be("strat-persist");
        restoredSession.Summary.InitialCash.Should().Be(50_000m);
        restoredSession.Symbols.Should().Equal(["AAPL", "MSFT", "GOOG"]);
        restoredSession.OrderHistory.Should().Contain(o => o.OrderId == "order-persist-1");
        restoredSession.FillHistory.Should().Contain(f => f.Symbol == "AAPL" && f.FilledQuantity == 100);
    }

    [Fact]
    public async Task SessionPersistenceGate_PortfolioStateConsistentAfterRestart()
    {
        // Arrange
        await using var auditTrail = CreateAuditTrail(nameof(SessionPersistenceGate_PortfolioStateConsistentAfterRestart));
        var sessionService = new PaperSessionPersistenceService(
            NullLogger<PaperSessionPersistenceService>.Instance,
            auditTrail: auditTrail);

        var session = await sessionService.CreateSessionAsync(
            new CreatePaperSessionDto("strat-portfolio", "Portfolio Test", 100_000m));

        // Apply fills
        var fills = new[]
        {
            new ExecutionFill { SessionId = session.SessionId, Symbol = "AAPL", Quantity = 10, FillPrice = 150m, FilledAt = DateTimeOffset.UtcNow, FillType = FillType.Trade },
            new ExecutionFill { SessionId = session.SessionId, Symbol = "AAPL", Quantity = -5, FillPrice = 155m, FilledAt = DateTimeOffset.UtcNow, FillType = FillType.Trade },
            new ExecutionFill { SessionId = session.SessionId, Symbol = "MSFT", Quantity = 20, FillPrice = 300m, FilledAt = DateTimeOffset.UtcNow, FillType = FillType.Trade }
        };

        foreach (var fill in fills)
        {
            await sessionService.RecordPaperFillAsync(session.SessionId, fill);
        }

        // Act: Get portfolio snapshot before restart
        var originalPortfolio = sessionService.GetSession(session.SessionId)?.Portfolio;

        // Simulate restart
        var restoredPortfolio = sessionService.GetSession(session.SessionId)?.Portfolio;

        // Assert: Portfolio matches after restart
        restoredPortfolio.Should().NotBeNull();
        restoredPortfolio!.CashBalance.Should().Be(originalPortfolio!.CashBalance, "cash position should match");
        restoredPortfolio.Positions.Count.Should().Be(originalPortfolio.Positions.Count, "position count should match");

        // Verify position details
        restoredPortfolio.Positions.Should().Contain(p => p.Symbol == "AAPL" && p.Quantity == 5);
        restoredPortfolio.Positions.Should().Contain(p => p.Symbol == "MSFT" && p.Quantity == 20);
    }

    [Fact]
    public async Task SessionPersistenceGate_LedgerContinuityAfterRestart()
    {
        // Arrange: Create session with ledger entries
        await using var auditTrail = CreateAuditTrail(nameof(SessionPersistenceGate_LedgerContinuityAfterRestart));
        var sessionService = new PaperSessionPersistenceService(
            NullLogger<PaperSessionPersistenceService>.Instance,
            auditTrail: auditTrail);

        var session = await sessionService.CreateSessionAsync(
            new CreatePaperSessionDto("strat-ledger", "Ledger Test", 100_000m));

        // Simulate ledger entries
        var fill = new ExecutionFill
        {
            SessionId = session.SessionId,
            Symbol = "AAPL",
            Quantity = 10,
            FillPrice = 150m,
            FilledAt = DateTimeOffset.UtcNow,
            FillType = FillType.Trade
        };
        await sessionService.RecordPaperFillAsync(session.SessionId, fill);

        // Act: Verify ledger entries exist and can be reconstructed
        var ledger = sessionService.GetLedger(session.SessionId);
        var ledgerEntries = ledger?.GetEntries(LedgerAccounts.Cash) ?? [];

        // Assert: Ledger can be reconstructed
        ledgerEntries.Should().NotBeEmpty("ledger should have entries after fill");
    }

    // ---- GATE 3: RISK AUDITABILITY ----

    [Fact]
    public async Task RiskAuditabilityGate_ControlOutcomeExplainableFromCockpit()
    {
        // Arrange: Create audit trail with order rejection
        await using var auditTrail = CreateAuditTrail(nameof(RiskAuditabilityGate_ControlOutcomeExplainableFromCockpit));
        var controlService = new ExecutionOperatorControlService();

        var auditEntry = await auditTrail.RecordAsync(
            category: "Order",
            action: "OrderRejected",
            outcome: "RejectedByControl",
            actor: "risk-engine",
            reason: "position-limit-exceeded",
            orderId: "order-control-1",
            scope: "AAPL:100",
            correlationId: "corr-control-1");

        // Act: Get control state and verify explainability
        var controlSnapshot = controlService.GetSnapshot();
        var auditEntries = new List<ExecutionAuditEntry> { auditEntry };

        // Assert: Audit entry has all required explainability fields
        auditEntry.Actor.Should().Be("risk-engine");
        auditEntry.Reason.Should().Be("position-limit-exceeded");
        auditEntry.Scope.Should().Be("AAPL:100");
        auditEntry.AuditId.Should().NotBeNullOrEmpty("audit entry must have stable ID");
        auditEntry.Category.Should().Be("Order");
    }

    [Fact]
    public async Task RiskAuditabilityGate_ManualOverrideIncludesActor()
    {
        // Arrange
        await using var auditTrail = CreateAuditTrail(nameof(RiskAuditabilityGate_ManualOverrideIncludesActor));

        var overrideEntry = await auditTrail.RecordAsync(
            category: "Override",
            action: "ManualOverride",
            outcome: "Approved",
            actor: "fund-manager",
            reason: "client-request",
            orderId: "order-override-1",
            correlationId: "corr-override-1");

        // Act & Assert: Override has actor and reason
        overrideEntry.Actor.Should().Be("fund-manager");
        overrideEntry.Reason.Should().Be("client-request");
        overrideEntry.OccurredAt.Should().BeCloseTo(DateTimeOffset.UtcNow, TimeSpan.FromSeconds(5));
    }

    [Fact]
    public async Task RiskAuditabilityGate_ReadinessExposesAuditControlState()
    {
        // Arrange: Create readiness service with audit trail
        await using var auditTrail = CreateAuditTrail(nameof(RiskAuditabilityGate_ReadinessExposesAuditControlState));
        await using var provider = new ServiceCollection()
            .AddSingleton(auditTrail)
            .AddSingleton<ExecutionOperatorControlService>()
            .BuildServiceProvider();
        var readinessService = new TradingOperatorReadinessService(
            provider,
            NullLogger<TradingOperatorReadinessService>.Instance);

        // Record control evidence
        var auditEntry = await auditTrail.RecordAsync(
            category: "Order",
            action: "OrderRejected",
            outcome: "RejectedByControl",
            actor: "operator",
            reason: "buying-power-constraint",
            orderId: "order-audit-1",
            correlationId: "corr-audit-1");

        // Act: Get readiness
        var readiness = await readinessService.GetAsync();

        // Assert: Control state is exposed with explainability
        readiness.Controls.Should().NotBeNull();
        readiness.Controls!.RecentEvidence.Should().NotBeEmpty("recent audit evidence should be visible");

        var evidence = readiness.Controls.RecentEvidence.FirstOrDefault();
        evidence?.Scope.Should().NotBeNullOrEmpty("evidence scope should be recorded");
        evidence?.AuditId.Should().NotBeNullOrEmpty("evidence should have audit reference");
    }

    // ---- GATE 4: PROMOTION TRACEABILITY ----

    [Fact]
    public async Task PromotionTraceabilityGate_ApprovalHasCompleteAuditChain()
    {
        // Arrange
        await using var auditTrail = CreateAuditTrail(nameof(PromotionTraceabilityGate_ApprovalHasCompleteAuditChain));
        var promotionService = new PromotionRecordService(
            NullLogger<PromotionRecordService>.Instance);

        var runId = Guid.NewGuid();
        var operatorId = "trader-001";
        var reason = "All risk checks passed, backtest P&L positive";
        var override_ = default(string?);

        // Act: Approve promotion
        var approval = await promotionService.ApprovePromotionAsync(
            runId: runId,
            operatorId: operatorId,
            reason: reason,
            manualOverrideId: override_,
            ct: default);

        // Assert: Approval has complete trace
        approval.RunId.Should().Be(runId);
        approval.OperatorId.Should().Be(operatorId);
        approval.Reason.Should().Be(reason);
        approval.Decision.Should().Be(PromotionDecision.Approved);
        approval.DecidedAt.Should().BeCloseTo(DateTimeOffset.UtcNow, TimeSpan.FromSeconds(5));
        approval.AuditReference.Should().NotBeNullOrEmpty("approval must have audit reference");
    }

    [Fact]
    public async Task PromotionTraceabilityGate_RejectionIncludesRationale()
    {
        // Arrange
        var promotionService = new PromotionRecordService(
            NullLogger<PromotionRecordService>.Instance);

        var runId = Guid.NewGuid();
        var operatorId = "controller";
        var reason = "Portfolio exposure exceeds daily limit";

        // Act: Reject promotion
        var rejection = await promotionService.RejectPromotionAsync(
            runId: runId,
            operatorId: operatorId,
            reason: reason,
            ct: default);

        // Assert: Rejection has complete rationale
        rejection.RunId.Should().Be(runId);
        rejection.OperatorId.Should().Be(operatorId);
        rejection.Reason.Should().Be(reason);
        rejection.Decision.Should().Be(PromotionDecision.Rejected);
        rejection.AuditReference.Should().NotBeNullOrEmpty("rejection must be auditable");
    }

    [Fact]
    public async Task PromotionTraceabilityGate_HistoryIsRecoverable()
    {
        // Arrange
        var promotionService = new PromotionRecordService(
            NullLogger<PromotionRecordService>.Instance);

        var runId = Guid.NewGuid();

        // Create approval
        await promotionService.ApprovePromotionAsync(
            runId: runId,
            operatorId: "trader-a",
            reason: "First review passed",
            ct: default);

        // Create rejection
        await promotionService.RejectPromotionAsync(
            runId: runId,
            operatorId: "trader-b",
            reason: "Risk check flagged concern",
            ct: default);

        // Act: Retrieve history
        var history = await promotionService.GetPromotionHistoryAsync(runId);

        // Assert: Full history is reconstructable
        history.Should().HaveCount(2, "approval and rejection should both be in history");
        history[0].Decision.Should().Be(PromotionDecision.Approved);
        history[0].OperatorId.Should().Be("trader-a");
        history[1].Decision.Should().Be(PromotionDecision.Rejected);
        history[1].OperatorId.Should().Be("trader-b");
    }

    [Fact]
    public async Task PromotionTraceabilityGate_ReadinessRequiresCompleteDecisionChain()
    {
        // Arrange: Create readiness service
        await using var provider = new ServiceCollection()
            .BuildServiceProvider();
        var readinessService = new TradingOperatorReadinessService(
            provider,
            NullLogger<TradingOperatorReadinessService>.Instance);

        // Act: Get readiness without promotions
        var readiness = await readinessService.GetAsync();

        // Assert: Promotion gate is in review required state
        var promotionGate = readiness.AcceptanceGates.FirstOrDefault(g => g.GateId == "promotion");
        promotionGate.Should().NotBeNull("promotion gate should be in readiness model");
    }

    // ---- END-TO-END OPERATOR SCENARIOS ----

    [Fact]
    public async Task EndToEndScenario_BacktestToPaperWorkflow()
    {
        // Arrange: Full workflow from backtest to paper trading
        await using var auditTrail = CreateAuditTrail(nameof(EndToEndScenario_BacktestToPaperWorkflow));
        var sessionService = new PaperSessionPersistenceService(
            NullLogger<PaperSessionPersistenceService>.Instance,
            auditTrail: auditTrail);
        var promotionService = new PromotionRecordService(
            NullLogger<PromotionRecordService>.Instance);

        await using var provider = new ServiceCollection()
            .AddSingleton(sessionService)
            .AddSingleton(auditTrail)
            .AddSingleton<ExecutionOperatorControlService>()
            .BuildServiceProvider();
        var readinessService = new TradingOperatorReadinessService(
            provider,
            NullLogger<TradingOperatorReadinessService>.Instance);

        // Act: Step 1 - Approve backtest promotion
        var backtestRunId = Guid.NewGuid();
        var approval = await promotionService.ApprovePromotionAsync(
            runId: backtestRunId,
            operatorId: "analyst",
            reason: "Backtest shows positive P&L with acceptable drawdown",
            ct: default);

        // Act: Step 2 - Create paper session
        var sessionDto = new CreatePaperSessionDto(
            backtestRunId.ToString(),
            "Backtest-Promoted-Strategy",
            50_000m)
        {
            Symbols = ["AAPL", "MSFT"]
        };
        var session = await sessionService.CreateSessionAsync(sessionDto);

        // Act: Step 3 - Execute trades
        var fill1 = new ExecutionFill
        {
            SessionId = session.SessionId,
            Symbol = "AAPL",
            Quantity = 10,
            FillPrice = 150m,
            FilledAt = DateTimeOffset.UtcNow,
            FillType = FillType.Trade
        };
        await sessionService.RecordPaperFillAsync(session.SessionId, fill1);

        await auditTrail.RecordAsync(
            category: "Trade",
            action: "Execution",
            outcome: "Filled",
            actor: "algo",
            orderId: "algo-order-1",
            correlationId: "corr-algo-1");

        // Act: Step 4 - Verify replay
        var replay = await sessionService.VerifyReplayAsync(
            session.SessionId,
            expectedFillCount: 1,
            expectedOrderCount: 0);

        // Act: Step 5 - Check operator readiness
        var readiness = await readinessService.GetAsync();

        // Assert: Full workflow is traceable
        approval.Decision.Should().Be(PromotionDecision.Approved);
        session.IsActive.Should().BeTrue();
        var sessionDetail = sessionService.GetSession(session.SessionId);
        sessionDetail?.FillHistory.Should().HaveCount(1);
        replay?.IsConsistent.Should().BeTrue("replay should verify");
        readiness.OverallStatus.Should().NotBe(TradingAcceptanceGateStatusDto.Blocked);
    }

    [Fact]
    public async Task EndToEndScenario_OperatorCanDiagnoseReplayFailure()
    {
        // Arrange: Session with replay failure
        await using var auditTrail = CreateAuditTrail(nameof(EndToEndScenario_OperatorCanDiagnoseReplayFailure));
        var sessionService = new PaperSessionPersistenceService(
            NullLogger<PaperSessionPersistenceService>.Instance,
            auditTrail: auditTrail);

        var session = await sessionService.CreateSessionAsync(
            new CreatePaperSessionDto("diag-strat", "Diagnostics Test", 100_000m));

        // Apply fill
        var fill = new ExecutionFill
        {
            SessionId = session.SessionId,
            Symbol = "GOOG",
            Quantity = 5,
            FillPrice = 2800m,
            FilledAt = DateTimeOffset.UtcNow,
            FillType = FillType.Trade
        };
        await sessionService.RecordPaperFillAsync(session.SessionId, fill);

        // Act: Verify with wrong counts
        var replay = await sessionService.VerifyReplayAsync(
            session.SessionId,
            expectedFillCount: 3, // Expected 3, got 1
            expectedOrderCount: 2); // Expected 2, got 0

        // Assert: Operator gets explicit diagnostics
        replay.Should().NotBeNull();
        replay!.IsConsistent.Should().BeFalse();
        replay.VerifiedFilledCount.Should().Be(1, "actual fill count");
        replay.VerifiedOrderCount.Should().Be(0, "actual order count");
        replay.MismatchReasons.Should().NotBeEmpty("operator must understand why replay failed");
        replay.MismatchReasons.First().Should().Contain("fill");
    }

    // ---- HELPERS ----

    private static ExecutionAuditTrailService CreateAuditTrail(string testName)
    {
        var tempDir = Path.Combine(Path.GetTempPath(), "meridian-tests", testName);
        Directory.CreateDirectory(tempDir);
        return new ExecutionAuditTrailService(tempDir, NullLogger<ExecutionAuditTrailService>.Instance);
    }
}
