using System.Text;

namespace Meridian.Storage.Packaging;

/// <summary>
/// Documentation generation and data loader script methods.
/// Database import scripts are in Scripts.Sql.cs and Scripts.Import.cs.
/// </summary>
public sealed partial class PortableDataPackager
{
    private string GenerateReadme(PackageManifest manifest, PackageOptions options)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {manifest.Name}");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(manifest.Description))
        {
            sb.AppendLine(manifest.Description);
            sb.AppendLine();
        }
        sb.AppendLine("## Package Information");
        sb.AppendLine();
        sb.AppendLine($"- **Package ID:** {manifest.PackageId}");
        sb.AppendLine($"- **Created:** {manifest.CreatedAt:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine($"- **Creator Version:** {manifest.CreatorVersion}");
        sb.AppendLine($"- **Format:** {manifest.Format}");
        sb.AppendLine();
        sb.AppendLine("## Data Summary");
        sb.AppendLine();
        sb.AppendLine($"- **Total Files:** {manifest.TotalFiles:N0}");
        sb.AppendLine($"- **Total Events:** {manifest.TotalEvents:N0}");
        sb.AppendLine($"- **Uncompressed Size:** {manifest.UncompressedSizeBytes:N0} bytes");
        sb.AppendLine($"- **Symbols:** {string.Join(", ", manifest.Symbols)}");
        sb.AppendLine($"- **Event Types:** {string.Join(", ", manifest.EventTypes)}");
        if (manifest.DateRange != null)
        {
            sb.AppendLine($"- **Date Range:** {manifest.DateRange.Start:yyyy-MM-dd} to {manifest.DateRange.End:yyyy-MM-dd}");
            sb.AppendLine($"- **Trading Days:** {manifest.DateRange.TradingDays}");
        }
        sb.AppendLine();
        sb.AppendLine("## Directory Structure");
        sb.AppendLine();
        sb.AppendLine("```");
        sb.AppendLine($"{manifest.Name}/");
        sb.AppendLine("├── manifest.json           # Package manifest with checksums");
        sb.AppendLine("├── README.md               # This file");
        sb.AppendLine("├── data/                   # Market data files");
        sb.AppendLine("├── metadata/               # Data dictionary and schemas");
        sb.AppendLine("└── scripts/                # Loader scripts for various tools");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("## Usage");
        sb.AppendLine();
        sb.AppendLine("### Python");
        sb.AppendLine("```python");
        sb.AppendLine("# See scripts/load_data.py for full example");
        sb.AppendLine("import pandas as pd");
        sb.AppendLine("df = pd.read_json('data/..../file.jsonl', lines=True)");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("### R");
        sb.AppendLine("```r");
        sb.AppendLine("# See scripts/load_data.R for full example");
        sb.AppendLine("library(jsonlite)");
        sb.AppendLine("df <- stream_in(file('data/..../file.jsonl'))");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("## Verification");
        sb.AppendLine();
        sb.AppendLine("All files include SHA256 checksums in `manifest.json` for integrity verification.");
        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine($"*Generated by Meridian v{manifest.CreatorVersion}*");

        return sb.ToString();
    }

    private string GenerateDataDictionary(PackageManifest manifest)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Data Dictionary");
        sb.AppendLine();
        sb.AppendLine($"Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine();

        if (manifest.Schemas != null)
        {
            foreach (var (eventType, schema) in manifest.Schemas)
            {
                sb.AppendLine($"## {eventType}");
                sb.AppendLine();
                sb.AppendLine("| Field | Type | Nullable | Description |");
                sb.AppendLine("|-------|------|----------|-------------|");

                foreach (var field in schema.Fields)
                {
                    sb.AppendLine($"| {field.Name} | {field.Type} | {(field.Nullable ? "Yes" : "No")} | {field.Description ?? ""} |");
                }

                sb.AppendLine();
            }
        }

        return sb.ToString();
    }

    private string GeneratePythonLoader(PackageManifest manifest)
    {
        var sb = new StringBuilder();
        sb.AppendLine("#!/usr/bin/env python3");
        sb.AppendLine("\"\"\"");
        sb.AppendLine($"Data Loader for {manifest.Name}");
        sb.AppendLine($"Package ID: {manifest.PackageId}");
        sb.AppendLine($"Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine("\"\"\"");
        sb.AppendLine();
        sb.AppendLine("import json");
        sb.AppendLine("import pandas as pd");
        sb.AppendLine("from pathlib import Path");
        sb.AppendLine("from typing import Optional, List");
        sb.AppendLine();
        sb.AppendLine("PACKAGE_DIR = Path(__file__).parent.parent");
        sb.AppendLine("DATA_DIR = PACKAGE_DIR / 'data'");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def load_manifest() -> dict:");
        sb.AppendLine("    \"\"\"Load the package manifest.\"\"\"");
        sb.AppendLine("    with open(PACKAGE_DIR / 'manifest.json') as f:");
        sb.AppendLine("        return json.load(f)");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def load_data(");
        sb.AppendLine("    symbol: Optional[str] = None,");
        sb.AppendLine("    event_type: Optional[str] = None,");
        sb.AppendLine("    date: Optional[str] = None");
        sb.AppendLine(") -> pd.DataFrame:");
        sb.AppendLine("    \"\"\"");
        sb.AppendLine("    Load market data into a pandas DataFrame.");
        sb.AppendLine("    ");
        sb.AppendLine("    Args:");
        sb.AppendLine("        symbol: Filter by symbol (e.g., 'AAPL')");
        sb.AppendLine("        event_type: Filter by event type (e.g., 'Trade', 'BboQuote')");
        sb.AppendLine("        date: Filter by date (e.g., '2024-01-15')");
        sb.AppendLine("    ");
        sb.AppendLine("    Returns:");
        sb.AppendLine("        DataFrame with matching data");
        sb.AppendLine("    \"\"\"");
        sb.AppendLine("    manifest = load_manifest()");
        sb.AppendLine("    dfs = []");
        sb.AppendLine("    ");
        sb.AppendLine("    for file_entry in manifest['files']:");
        sb.AppendLine("        # Apply filters");
        sb.AppendLine("        if symbol and file_entry.get('symbol', '').upper() != symbol.upper():");
        sb.AppendLine("            continue");
        sb.AppendLine("        if event_type and file_entry.get('eventType', '').lower() != event_type.lower():");
        sb.AppendLine("            continue");
        sb.AppendLine("        if date and file_entry.get('date', '')[:10] != date:");
        sb.AppendLine("            continue");
        sb.AppendLine("        ");
        sb.AppendLine("        file_path = PACKAGE_DIR / file_entry['path']");
        sb.AppendLine("        if file_path.exists():");
        sb.AppendLine("            df = pd.read_json(file_path, lines=True)");
        sb.AppendLine("            dfs.append(df)");
        sb.AppendLine("    ");
        sb.AppendLine("    if not dfs:");
        sb.AppendLine("        return pd.DataFrame()");
        sb.AppendLine("    ");
        sb.AppendLine("    return pd.concat(dfs, ignore_index=True)");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def get_symbols() -> List[str]:");
        sb.AppendLine("    \"\"\"Get list of symbols in the package.\"\"\"");
        sb.AppendLine("    return load_manifest().get('symbols', [])");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def get_event_types() -> List[str]:");
        sb.AppendLine("    \"\"\"Get list of event types in the package.\"\"\"");
        sb.AppendLine("    return load_manifest().get('eventTypes', [])");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("if __name__ == '__main__':");
        sb.AppendLine("    # Example usage");
        sb.AppendLine("    print(f'Symbols: {get_symbols()}')");
        sb.AppendLine("    print(f'Event Types: {get_event_types()}')");
        sb.AppendLine("    ");
        sb.AppendLine("    df = load_data()");
        sb.AppendLine("    print(f'\\nLoaded {len(df):,} records')");
        sb.AppendLine("    print(df.head())");

        return sb.ToString();
    }

    private string GenerateRLoader(PackageManifest manifest)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Data Loader for " + manifest.Name);
        sb.AppendLine("# Package ID: " + manifest.PackageId);
        sb.AppendLine("# Generated: " + DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss") + " UTC");
        sb.AppendLine();
        sb.AppendLine("library(jsonlite)");
        sb.AppendLine("library(dplyr)");
        sb.AppendLine("library(purrr)");
        sb.AppendLine();
        sb.AppendLine("# Get package directory");
        sb.AppendLine("get_package_dir <- function() {");
        sb.AppendLine("  dirname(dirname(rstudioapi::getActiveDocumentContext()$path))");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("# Load manifest");
        sb.AppendLine("load_manifest <- function() {");
        sb.AppendLine("  fromJSON(file.path(get_package_dir(), 'manifest.json'))");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("# Load data with optional filters");
        sb.AppendLine("load_data <- function(symbol = NULL, event_type = NULL, date = NULL) {");
        sb.AppendLine("  manifest <- load_manifest()");
        sb.AppendLine("  package_dir <- get_package_dir()");
        sb.AppendLine("  ");
        sb.AppendLine("  files <- manifest$files");
        sb.AppendLine("  ");
        sb.AppendLine("  # Apply filters");
        sb.AppendLine("  if (!is.null(symbol)) {");
        sb.AppendLine("    files <- files[toupper(files$symbol) == toupper(symbol), ]");
        sb.AppendLine("  }");
        sb.AppendLine("  if (!is.null(event_type)) {");
        sb.AppendLine("    files <- files[tolower(files$eventType) == tolower(event_type), ]");
        sb.AppendLine("  }");
        sb.AppendLine("  ");
        sb.AppendLine("  # Load and combine files");
        sb.AppendLine("  dfs <- map(files$path, function(p) {");
        sb.AppendLine("    full_path <- file.path(package_dir, p)");
        sb.AppendLine("    if (file.exists(full_path)) {");
        sb.AppendLine("      stream_in(file(full_path), verbose = FALSE)");
        sb.AppendLine("    } else {");
        sb.AppendLine("      NULL");
        sb.AppendLine("    }");
        sb.AppendLine("  })");
        sb.AppendLine("  ");
        sb.AppendLine("  bind_rows(compact(dfs))");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("# Get available symbols");
        sb.AppendLine("get_symbols <- function() {");
        sb.AppendLine("  load_manifest()$symbols");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("# Get available event types");
        sb.AppendLine("get_event_types <- function() {");
        sb.AppendLine("  load_manifest()$eventTypes");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("# Example usage:");
        sb.AppendLine("# df <- load_data()");
        sb.AppendLine("# df <- load_data(symbol = 'AAPL')");
        sb.AppendLine("# df <- load_data(event_type = 'Trade')");

        return sb.ToString();
    }

    private string GenerateImportScript(PackageManifest manifest, ImportScriptTarget target)
    {
        return target switch
        {
            ImportScriptTarget.Python => GeneratePythonImport(manifest),
            ImportScriptTarget.R => GenerateRImport(manifest),
            ImportScriptTarget.PostgreSql => GeneratePostgreSqlImport(manifest),
            ImportScriptTarget.ClickHouse => GenerateClickHouseImport(manifest),
            ImportScriptTarget.Spark => GenerateSparkImport(manifest),
            ImportScriptTarget.DuckDb => GenerateDuckDbImport(manifest),
            _ => $"-- Import script for {target} not yet implemented"
        };
    }
}
