using System.Text;

namespace Meridian.Storage.Packaging;

/// <summary>
/// Language-specific database import script generation (Python, R, Spark).
/// </summary>
public sealed partial class PortableDataPackager
{
    private string GeneratePythonImport(PackageManifest manifest)
    {
        var sb = new StringBuilder();
        sb.AppendLine("#!/usr/bin/env python3");
        sb.AppendLine("\"\"\"");
        sb.AppendLine($"Database Import Script for {manifest.Name}");
        sb.AppendLine($"Package ID: {manifest.PackageId}");
        sb.AppendLine($"Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine();
        sb.AppendLine("This script imports market data from the package into a PostgreSQL database.");
        sb.AppendLine("Requires: psycopg2, pandas");
        sb.AppendLine("\"\"\"");
        sb.AppendLine();
        sb.AppendLine("import json");
        sb.AppendLine("import pandas as pd");
        sb.AppendLine("import psycopg2");
        sb.AppendLine("from psycopg2.extras import execute_values");
        sb.AppendLine("from pathlib import Path");
        sb.AppendLine("from typing import Optional");
        sb.AppendLine("import os");
        sb.AppendLine();
        sb.AppendLine("# Database connection settings (override via environment variables)");
        sb.AppendLine("DB_HOST = os.getenv('DB_HOST', 'localhost')");
        sb.AppendLine("DB_PORT = os.getenv('DB_PORT', '5432')");
        sb.AppendLine("DB_NAME = os.getenv('DB_NAME', 'marketdata')");
        sb.AppendLine("DB_USER = os.getenv('DB_USER', 'postgres')");
        sb.AppendLine("DB_PASSWORD = os.getenv('DB_PASSWORD', '')");
        sb.AppendLine();
        sb.AppendLine("PACKAGE_DIR = Path(__file__).parent.parent");
        sb.AppendLine("DATA_DIR = PACKAGE_DIR / 'data'");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def get_connection():");
        sb.AppendLine("    \"\"\"Create a database connection.\"\"\"");
        sb.AppendLine("    return psycopg2.connect(");
        sb.AppendLine("        host=DB_HOST,");
        sb.AppendLine("        port=DB_PORT,");
        sb.AppendLine("        dbname=DB_NAME,");
        sb.AppendLine("        user=DB_USER,");
        sb.AppendLine("        password=DB_PASSWORD");
        sb.AppendLine("    )");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def create_tables(conn):");
        sb.AppendLine("    \"\"\"Create database tables if they don't exist.\"\"\"");
        sb.AppendLine("    with conn.cursor() as cur:");
        sb.AppendLine("        cur.execute('''");
        sb.AppendLine("            CREATE TABLE IF NOT EXISTS trades (");
        sb.AppendLine("                id SERIAL PRIMARY KEY,");
        sb.AppendLine("                timestamp TIMESTAMPTZ NOT NULL,");
        sb.AppendLine("                symbol VARCHAR(20) NOT NULL,");
        sb.AppendLine("                price DECIMAL(18, 8) NOT NULL,");
        sb.AppendLine("                size BIGINT NOT NULL,");
        sb.AppendLine("                side VARCHAR(10),");
        sb.AppendLine("                exchange VARCHAR(20),");
        sb.AppendLine("                sequence_number BIGINT");
        sb.AppendLine("            );");
        sb.AppendLine("            CREATE INDEX IF NOT EXISTS idx_trades_symbol_time ON trades(symbol, timestamp);");
        sb.AppendLine("            ");
        sb.AppendLine("            CREATE TABLE IF NOT EXISTS quotes (");
        sb.AppendLine("                id SERIAL PRIMARY KEY,");
        sb.AppendLine("                timestamp TIMESTAMPTZ NOT NULL,");
        sb.AppendLine("                symbol VARCHAR(20) NOT NULL,");
        sb.AppendLine("                bid_price DECIMAL(18, 8),");
        sb.AppendLine("                bid_size BIGINT,");
        sb.AppendLine("                ask_price DECIMAL(18, 8),");
        sb.AppendLine("                ask_size BIGINT");
        sb.AppendLine("            );");
        sb.AppendLine("            CREATE INDEX IF NOT EXISTS idx_quotes_symbol_time ON quotes(symbol, timestamp);");
        sb.AppendLine("        ''')");
        sb.AppendLine("        conn.commit()");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def import_trades(conn, df: pd.DataFrame) -> int:");
        sb.AppendLine("    \"\"\"Import trades DataFrame into database.\"\"\"");
        sb.AppendLine("    if df.empty:");
        sb.AppendLine("        return 0");
        sb.AppendLine("    ");
        sb.AppendLine("    columns = ['timestamp', 'symbol', 'price', 'size', 'side', 'exchange', 'sequence_number']");
        sb.AppendLine("    records = []");
        sb.AppendLine("    for _, row in df.iterrows():");
        sb.AppendLine("        records.append((");
        sb.AppendLine("            row.get('Timestamp') or row.get('timestamp'),");
        sb.AppendLine("            row.get('Symbol') or row.get('symbol'),");
        sb.AppendLine("            row.get('Price') or row.get('price'),");
        sb.AppendLine("            row.get('Size') or row.get('size'),");
        sb.AppendLine("            row.get('Side') or row.get('side'),");
        sb.AppendLine("            row.get('Exchange') or row.get('exchange'),");
        sb.AppendLine("            row.get('SequenceNumber') or row.get('sequence_number')");
        sb.AppendLine("        ))");
        sb.AppendLine("    ");
        sb.AppendLine("    with conn.cursor() as cur:");
        sb.AppendLine("        execute_values(cur, '''");
        sb.AppendLine("            INSERT INTO trades (timestamp, symbol, price, size, side, exchange, sequence_number)");
        sb.AppendLine("            VALUES %s");
        sb.AppendLine("        ''', records)");
        sb.AppendLine("        conn.commit()");
        sb.AppendLine("    ");
        sb.AppendLine("    return len(records)");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def import_package():");
        sb.AppendLine("    \"\"\"Import all data from the package into the database.\"\"\"");
        sb.AppendLine("    # Load manifest");
        sb.AppendLine("    with open(PACKAGE_DIR / 'manifest.json') as f:");
        sb.AppendLine("        manifest = json.load(f)");
        sb.AppendLine("    ");
        sb.AppendLine("    print(f\"Importing package: {manifest['name']}\")");
        sb.AppendLine("    print(f\"Files: {manifest['totalFiles']}, Events: {manifest['totalEvents']:,}\")");
        sb.AppendLine("    ");
        sb.AppendLine("    conn = get_connection()");
        sb.AppendLine("    create_tables(conn)");
        sb.AppendLine("    ");
        sb.AppendLine("    total_imported = 0");
        sb.AppendLine("    for file_entry in manifest['files']:");
        sb.AppendLine("        file_path = PACKAGE_DIR / file_entry['path']");
        sb.AppendLine("        if not file_path.exists():");
        sb.AppendLine("            continue");
        sb.AppendLine("        ");
        sb.AppendLine("        event_type = file_entry.get('eventType', '').lower()");
        sb.AppendLine("        df = pd.read_json(file_path, lines=True)");
        sb.AppendLine("        ");
        sb.AppendLine("        if event_type == 'trade':");
        sb.AppendLine("            count = import_trades(conn, df)");
        sb.AppendLine("            total_imported += count");
        sb.AppendLine("            print(f\"  Imported {count:,} trades from {file_entry['path']}\")");
        sb.AppendLine("    ");
        sb.AppendLine("    conn.close()");
        sb.AppendLine("    print(f\"\\nTotal records imported: {total_imported:,}\")");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("if __name__ == '__main__':");
        sb.AppendLine("    import_package()");

        return sb.ToString();
    }

    private string GenerateRImport(PackageManifest manifest)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Database Import Script for " + manifest.Name);
        sb.AppendLine("# Package ID: " + manifest.PackageId);
        sb.AppendLine("# Generated: " + DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss") + " UTC");
        sb.AppendLine("#");
        sb.AppendLine("# This script imports market data from the package into a PostgreSQL database.");
        sb.AppendLine("# Requires: DBI, RPostgres, jsonlite, dplyr");
        sb.AppendLine();
        sb.AppendLine("library(DBI)");
        sb.AppendLine("library(RPostgres)");
        sb.AppendLine("library(jsonlite)");
        sb.AppendLine("library(dplyr)");
        sb.AppendLine();
        sb.AppendLine("# Database connection settings (override via environment variables)");
        sb.AppendLine("DB_HOST <- Sys.getenv('DB_HOST', 'localhost')");
        sb.AppendLine("DB_PORT <- as.integer(Sys.getenv('DB_PORT', '5432'))");
        sb.AppendLine("DB_NAME <- Sys.getenv('DB_NAME', 'marketdata')");
        sb.AppendLine("DB_USER <- Sys.getenv('DB_USER', 'postgres')");
        sb.AppendLine("DB_PASSWORD <- Sys.getenv('DB_PASSWORD', '')");
        sb.AppendLine();
        sb.AppendLine("# Get package directory");
        sb.AppendLine("get_package_dir <- function() {");
        sb.AppendLine("  dirname(dirname(rstudioapi::getActiveDocumentContext()$path))");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("# Create database connection");
        sb.AppendLine("get_connection <- function() {");
        sb.AppendLine("  dbConnect(");
        sb.AppendLine("    Postgres(),");
        sb.AppendLine("    host = DB_HOST,");
        sb.AppendLine("    port = DB_PORT,");
        sb.AppendLine("    dbname = DB_NAME,");
        sb.AppendLine("    user = DB_USER,");
        sb.AppendLine("    password = DB_PASSWORD");
        sb.AppendLine("  )");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("# Create tables");
        sb.AppendLine("create_tables <- function(conn) {");
        sb.AppendLine("  dbExecute(conn, \"");
        sb.AppendLine("    CREATE TABLE IF NOT EXISTS trades (");
        sb.AppendLine("      id SERIAL PRIMARY KEY,");
        sb.AppendLine("      timestamp TIMESTAMPTZ NOT NULL,");
        sb.AppendLine("      symbol VARCHAR(20) NOT NULL,");
        sb.AppendLine("      price DECIMAL(18, 8) NOT NULL,");
        sb.AppendLine("      size BIGINT NOT NULL,");
        sb.AppendLine("      side VARCHAR(10),");
        sb.AppendLine("      exchange VARCHAR(20),");
        sb.AppendLine("      sequence_number BIGINT");
        sb.AppendLine("    );\")");
        sb.AppendLine("  dbExecute(conn, \"CREATE INDEX IF NOT EXISTS idx_trades_symbol_time ON trades(symbol, timestamp);\")");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("# Import trades");
        sb.AppendLine("import_trades <- function(conn, df) {");
        sb.AppendLine("  if (nrow(df) == 0) return(0)");
        sb.AppendLine("  ");
        sb.AppendLine("  # Normalize column names");
        sb.AppendLine("  names(df) <- tolower(names(df))");
        sb.AppendLine("  ");
        sb.AppendLine("  # Select and rename columns");
        sb.AppendLine("  trades_df <- df %>%");
        sb.AppendLine("    select(");
        sb.AppendLine("      timestamp = any_of(c('timestamp', 'Timestamp')),");
        sb.AppendLine("      symbol = any_of(c('symbol', 'Symbol')),");
        sb.AppendLine("      price = any_of(c('price', 'Price')),");
        sb.AppendLine("      size = any_of(c('size', 'Size')),");
        sb.AppendLine("      side = any_of(c('side', 'Side')),");
        sb.AppendLine("      exchange = any_of(c('exchange', 'Exchange')),");
        sb.AppendLine("      sequence_number = any_of(c('sequencenumber', 'sequence_number'))");
        sb.AppendLine("    )");
        sb.AppendLine("  ");
        sb.AppendLine("  dbWriteTable(conn, 'trades', trades_df, append = TRUE, row.names = FALSE)");
        sb.AppendLine("  nrow(trades_df)");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("# Main import function");
        sb.AppendLine("import_package <- function() {");
        sb.AppendLine("  package_dir <- get_package_dir()");
        sb.AppendLine("  manifest <- fromJSON(file.path(package_dir, 'manifest.json'))");
        sb.AppendLine("  ");
        sb.AppendLine("  cat(sprintf('Importing package: %s\\n', manifest$name))");
        sb.AppendLine("  cat(sprintf('Files: %d, Events: %s\\n', manifest$totalFiles, format(manifest$totalEvents, big.mark = ',')))");
        sb.AppendLine("  ");
        sb.AppendLine("  conn <- get_connection()");
        sb.AppendLine("  create_tables(conn)");
        sb.AppendLine("  ");
        sb.AppendLine("  total_imported <- 0");
        sb.AppendLine("  for (i in seq_len(nrow(manifest$files))) {");
        sb.AppendLine("    file_entry <- manifest$files[i, ]");
        sb.AppendLine("    file_path <- file.path(package_dir, file_entry$path)");
        sb.AppendLine("    ");
        sb.AppendLine("    if (!file.exists(file_path)) next");
        sb.AppendLine("    ");
        sb.AppendLine("    event_type <- tolower(file_entry$eventType)");
        sb.AppendLine("    df <- stream_in(file(file_path), verbose = FALSE)");
        sb.AppendLine("    ");
        sb.AppendLine("    if (event_type == 'trade') {");
        sb.AppendLine("      count <- import_trades(conn, df)");
        sb.AppendLine("      total_imported <- total_imported + count");
        sb.AppendLine("      cat(sprintf('  Imported %s trades from %s\\n', format(count, big.mark = ','), file_entry$path))");
        sb.AppendLine("    }");
        sb.AppendLine("  }");
        sb.AppendLine("  ");
        sb.AppendLine("  dbDisconnect(conn)");
        sb.AppendLine("  cat(sprintf('\\nTotal records imported: %s\\n', format(total_imported, big.mark = ',')))");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("# Run import");
        sb.AppendLine("import_package()");

        return sb.ToString();
    }

    private string GenerateSparkImport(PackageManifest manifest)
    {
        var sb = new StringBuilder();
        sb.AppendLine("#!/usr/bin/env python3");
        sb.AppendLine("\"\"\"");
        sb.AppendLine($"Apache Spark Import Script for {manifest.Name}");
        sb.AppendLine($"Package ID: {manifest.PackageId}");
        sb.AppendLine($"Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine();
        sb.AppendLine("This script loads market data from the package into Spark DataFrames.");
        sb.AppendLine("Requires: pyspark");
        sb.AppendLine("\"\"\"");
        sb.AppendLine();
        sb.AppendLine("import json");
        sb.AppendLine("from pathlib import Path");
        sb.AppendLine("from pyspark.sql import SparkSession");
        sb.AppendLine("from pyspark.sql.types import (");
        sb.AppendLine("    StructType, StructField, StringType, DecimalType, LongType, TimestampType");
        sb.AppendLine(")");
        sb.AppendLine();
        sb.AppendLine("PACKAGE_DIR = Path(__file__).parent.parent");
        sb.AppendLine("DATA_DIR = PACKAGE_DIR / 'data'");
        sb.AppendLine();
        sb.AppendLine("# Schema definitions");
        sb.AppendLine("TRADE_SCHEMA = StructType([");
        sb.AppendLine("    StructField('Timestamp', TimestampType(), False),");
        sb.AppendLine("    StructField('Symbol', StringType(), False),");
        sb.AppendLine("    StructField('Price', DecimalType(18, 8), False),");
        sb.AppendLine("    StructField('Size', LongType(), False),");
        sb.AppendLine("    StructField('Side', StringType(), True),");
        sb.AppendLine("    StructField('Exchange', StringType(), True),");
        sb.AppendLine("    StructField('SequenceNumber', LongType(), True)");
        sb.AppendLine("])");
        sb.AppendLine();
        sb.AppendLine("QUOTE_SCHEMA = StructType([");
        sb.AppendLine("    StructField('Timestamp', TimestampType(), False),");
        sb.AppendLine("    StructField('Symbol', StringType(), False),");
        sb.AppendLine("    StructField('BidPrice', DecimalType(18, 8), True),");
        sb.AppendLine("    StructField('BidSize', LongType(), True),");
        sb.AppendLine("    StructField('AskPrice', DecimalType(18, 8), True),");
        sb.AppendLine("    StructField('AskSize', LongType(), True)");
        sb.AppendLine("])");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def create_spark_session(app_name: str = 'MarketDataImport') -> SparkSession:");
        sb.AppendLine("    \"\"\"Create a Spark session.\"\"\"");
        sb.AppendLine("    return SparkSession.builder \\");
        sb.AppendLine("        .appName(app_name) \\");
        sb.AppendLine("        .config('spark.sql.session.timeZone', 'UTC') \\");
        sb.AppendLine("        .getOrCreate()");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def load_manifest():");
        sb.AppendLine("    \"\"\"Load the package manifest.\"\"\"");
        sb.AppendLine("    with open(PACKAGE_DIR / 'manifest.json') as f:");
        sb.AppendLine("        return json.load(f)");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def load_trades(spark: SparkSession):");
        sb.AppendLine("    \"\"\"Load all trade data into a Spark DataFrame.\"\"\"");
        sb.AppendLine("    manifest = load_manifest()");
        sb.AppendLine("    trade_files = [");
        sb.AppendLine("        str(PACKAGE_DIR / f['path'])");
        sb.AppendLine("        for f in manifest['files']");
        sb.AppendLine("        if f.get('eventType', '').lower() == 'trade'");
        sb.AppendLine("    ]");
        sb.AppendLine("    ");
        sb.AppendLine("    if not trade_files:");
        sb.AppendLine("        return spark.createDataFrame([], TRADE_SCHEMA)");
        sb.AppendLine("    ");
        sb.AppendLine("    return spark.read.json(trade_files, schema=TRADE_SCHEMA)");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def load_quotes(spark: SparkSession):");
        sb.AppendLine("    \"\"\"Load all quote data into a Spark DataFrame.\"\"\"");
        sb.AppendLine("    manifest = load_manifest()");
        sb.AppendLine("    quote_files = [");
        sb.AppendLine("        str(PACKAGE_DIR / f['path'])");
        sb.AppendLine("        for f in manifest['files']");
        sb.AppendLine("        if f.get('eventType', '').lower() in ('bboquote', 'quote')");
        sb.AppendLine("    ]");
        sb.AppendLine("    ");
        sb.AppendLine("    if not quote_files:");
        sb.AppendLine("        return spark.createDataFrame([], QUOTE_SCHEMA)");
        sb.AppendLine("    ");
        sb.AppendLine("    return spark.read.json(quote_files, schema=QUOTE_SCHEMA)");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def load_all_data(spark: SparkSession):");
        sb.AppendLine("    \"\"\"Load all data from the package (infers schema).\"\"\"");
        sb.AppendLine("    return spark.read.json(str(DATA_DIR / '**' / '*.jsonl'))");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def save_to_parquet(df, output_path: str, partition_by: list = None):");
        sb.AppendLine("    \"\"\"Save DataFrame to Parquet format.\"\"\"");
        sb.AppendLine("    writer = df.write.mode('overwrite')");
        sb.AppendLine("    if partition_by:");
        sb.AppendLine("        writer = writer.partitionBy(*partition_by)");
        sb.AppendLine("    writer.parquet(output_path)");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("def main():");
        sb.AppendLine("    \"\"\"Main entry point.\"\"\"");
        sb.AppendLine("    manifest = load_manifest()");
        sb.AppendLine("    print(f\"Loading package: {manifest['name']}\")");
        sb.AppendLine("    print(f\"Files: {manifest['totalFiles']}, Events: {manifest['totalEvents']:,}\")");
        sb.AppendLine("    ");
        sb.AppendLine("    spark = create_spark_session()");
        sb.AppendLine("    ");
        sb.AppendLine("    # Load trades");
        sb.AppendLine("    trades_df = load_trades(spark)");
        sb.AppendLine("    print(f\"\\nLoaded {trades_df.count():,} trades\")");
        sb.AppendLine("    trades_df.printSchema()");
        sb.AppendLine("    trades_df.show(5)");
        sb.AppendLine("    ");
        sb.AppendLine("    # Load quotes");
        sb.AppendLine("    quotes_df = load_quotes(spark)");
        sb.AppendLine("    print(f\"\\nLoaded {quotes_df.count():,} quotes\")");
        sb.AppendLine("    quotes_df.printSchema()");
        sb.AppendLine("    quotes_df.show(5)");
        sb.AppendLine("    ");
        sb.AppendLine("    # Example: Save to Parquet with partitioning");
        sb.AppendLine("    # save_to_parquet(trades_df, 'output/trades.parquet', ['Symbol'])");
        sb.AppendLine("    ");
        sb.AppendLine("    spark.stop()");
        sb.AppendLine();
        sb.AppendLine();
        sb.AppendLine("if __name__ == '__main__':");
        sb.AppendLine("    main()");

        return sb.ToString();
    }
}
